### ISSUE TITLE
Add caseID to graphML/CSV export filename

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#1003]
Add case ID to the filename for the graphML/CSV (when implemented) export on clients.

**Comment by rebeccamadsen** [comment]
Should the filename match what Server generates for the filename or just have the case ID?

Server does '`caseID`\_`sessionUuid`.graphml', when it exports files separately, and '`protocolName`.graphml' when exporting as one. The csv files are similar, e.g.: '`caseID`\_`sessionUuid`_attributeList.csv' for separate interviews or '`protocolName`_attributeList.csv' for the union of all interview networks.

**Comment by jthrilly** [comment]
> Should the filename match what Server generates for the filename or just have the case ID?

Yes, let's have it match for consistency's sake. Obviously on client there is no union, of course.
