### ISSUE TITLE
Support CSV Export from Network Canvas

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#1007]
Will resolve the NC side of #1005 

Add CSV export support to Network Canvas.

**Comment by rebeccamadsen** [comment]
Will CSV export in NC also be only one protocol at a time, like graphml? Is this going to be offered just from the final screen of a protocol, or the Session list?

**Comment by jthrilly** [comment]
> Will CSV export in NC also be only one protocol at a time, like graphml?

The intent is to eventually support multiple network export for both, through zip creation. Since CSV export contains multiple files, and these might be hard to work with/transfer to and from mobile devices, this would be a good time to implement that zipping process? It would then hopefully be quite simple to apply it to multiple file export of both formats in a future issue. What do you think?

> Is this going to be offered just from the final screen of a protocol, or the Session list?

Initially this is for the final screen, but as/when we implement multiple file export it can be added to the session list, too.

Just another thing I wanted to note: I said in the OP that this will resolve #1005, but if we make the changes I discussed in the GraphML export issue (implement storing ego data through extending GraphML) we can also close that issue through that means.

**Comment by jthrilly** [comment]
Closed in https://github.com/codaco/network-exporters/pull/4
