### ISSUE TITLE
No snap package nor appimage since 5.1.0 (linux)

### ISSUE THREAD

**Issue by lleleux** [codaco/Network-Canvas#1019]
Hi,

How to install the 5.1.0 version on ubuntu ? I cannot find the snap package nor the appimage in the release assets. In the 4.2.0 version there was a snap and appimage, in the 5.0.0 only an appimage, and in the 5.1.0 nothing for linux.

Regards,

Laurent

**Comment by jthrilly** [comment]
Hi @lleleux !

Thanks for letting us know about this - you are quite right that we didn't publish linux versions for the last release. We have been experiencing issues related to the linux packaging, and weren't aware that we had users that were interested in linux support at this stage.

I will update the Network Canvas and Architect releases with Linux versions. Server is unfortunately not able to run when packaged as a snap at the moment for unknown reasons. However, I would recommend running the apps from source for the most stable experience.  Let me know if you would like support getting this to work.

**Comment by jthrilly** [comment]
I have updated the snap packages, but I didn't add them to the release. You should be able to get them from the snap store in the usual way.

I noticed that MDNS is not working for the packaged version of Network Canvas - I hope this won't cause you issues. If it does, you will need to run from source, as I described in my previous post.

**Comment by lleleux** [comment]
Thank you for the update !
I will install this today.
Laurent
