### ISSUE TITLE
Implement name generator interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#121]

**Comment by jthrilly** [comment]
Spec incoming...

**Comment by jthrilly** [comment]
## Prompts
An array of objects, where each object describes a question prompt, and associated variables (and values) to be stored on newly created nodes.

In the case of multiple prompts, the question prompt box becomes swipeable. Only one question is active at any given time. 

``` javascript
prompts: [
  {
    title: 'Within the past 6 months, who have you felt close to?',
    variables: [
      {
        label: 'special_category',
        value: 46
      },
      {
        label: 'close_friend',
        value: true
      }
  }
];
```

## Panels
An array of objects, where each describes a side panel to be shown. Maximum of two total side panels (ONE of type ‘existing’). 

Available panel types are:
-  **Existing** 
  Shows all nodes in the network, apart from those visible in the main name generator grid (that is, those that have just been elicited in response to the current prompt). Allows these existing nodes to be ‘selected’, which assigns the current prompts variables and values to a given node. Ask me to demo this if you aren’t clear.
- **Roster/Previous**
  Allows for a predefined list of nodes to be shown. This list could be preprogrammed in when the interview protocol was designed, or could be the result of loading some other data (for example, the output of a previous visit). Nodes in this panel can be dragged into the current interview by dragging them from the panel into the main name generator grid.

``` javascript
panels: [
  {
    type: 'previous',
    title: 'People from your previous visit',
    draggable: true
  }, {
    type: 'existing',
    title: 'People you already mentioned',
    selectable: true
  }
];
```

## Form
A definition of the form to be used when creating a new node. This form has traditionally been shown in a modal overlay.

This needs to be looked at separately, as we will need generic form building capabilities elsewhere in the app, so we will need to build something. If you know of any existing tools to help us with this, please let me know.

The features we need are:
- Specify form fields, their types, and validation rules.
- Specify custom form fields. These would provide their own markup, validation methods, and interaction handlers (serialization for when the form is submitted, for example)

``` javascript
form: {
  title: 'Add a person you know',
  fields: {
    name: {
      title: 'Name',
      type: 'text',
      placeholder: 'Name',
      required: true
    },
    label: {
      title: 'Nickname',
      type: 'text',
      placeholder: 'Nickname',
      required: true
    }
  }
}
```

**Comment by jthrilly** [comment]
@jamieshark this is a wip, but it gives you something concrete to implement. As I said on slack, don't worry too much about how these things will connect with the front end, although if you want to separate some of this out into components I can certainly build on those (good candidates for that would be the 'node grid', the name generator form, the question prompt that becomes a swiper, and the side panels, since all of these will be reused). Ping me for further details about any of them.

**Comment by wwqrd** [comment]
> This list could be preprogrammed in when the interview protocol was designed, or could be the result of loading some other data (for example, the output of a previous visit).

@jthrilly As in specific the person being interviewed? Are there any existing thoughts on how this data might get provided to the app?

**Comment by wwqrd** [comment]
@jthrilly This panels section seems like it could be slimmed down a bit to me.

The main panel is going to be handled by the interface right, `NameGenInterface` say, and will be non configurable.

Then it sounds like there is only one more panel, the 'sidebar', which has a title and a filter.

Suggest this bit look like:

```js
panel: {
  title: 'People from your previous visit',
  filter: (node) => { ... }
};
```

**Comment by wwqrd** [comment]
So there **are** multiple panels and these are unrelated to the main view.

Still, suggest we make the config more generic, and this would open up the possibility of showing sub-categories of existing/previous nodes, if wanted - or mixing the two together.

```js
panels: [
  {
    title: 'People from your previous visit',
    draggable: true,
    filter: (node) => { return node.attributes.previous; }
  }, {
    title: 'People you already mentioned',
    selectable: true
    filter: ...
  }
];
```

**Comment by jthrilly** [comment]
Okay, great suggestion.

I would like to see a hybrid of both. I want built in panels, as specified in the existing example above. These are essentially just "shortcuts" to the above syntax. 

Then we have a `type: custom` option, which lets the user use the syntax you have come up with.

The reason I want both is that I don't want to encumber intermediate users with syntactic complexity that isn't needed, and I also want to keep the API as simple as possible for the general use case. For example, 99% of protocols will use the panel presets. If we change the API of the panels, we can update the interface module that implements them without breaking their use in the protocol files.

**Comment by jthrilly** [comment]
So something like:

``` javascript

panels: [
  'current',
  {
    title: 'Custom panel',
    draggable: true,
    filter: (node) => { return node.attributes.previous; }
  }
];
```

**Comment by wwqrd** [comment]
Okay, probably want to blend them a bit more? For custom titles etc.

```js
panels: [
  {
    title: 'People from your previous visit',
    draggable: true,
    filter: 'previous'
  }, {
    title: 'People who like ice cream',
    selectable: true
    filter: (node) => { return node.attributes.likeIcecream; }
  }
];
```

**Comment by jthrilly** [comment]
I've updated the panel spec to clarify.
