### ISSUE TITLE
Implement form builder component

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#123]
- [x] Takes a JSON/configuration object and builds a form from it
- [x] Includes individual input validation
- [x]  Allows for custom input controls
- [x] Style components

**Comment by jthrilly** [comment]
Examples: 
- https://github.com/blackjk3/react-form-builder
- https://github.com/Kinto/formbuilder

**Comment by jthrilly** [comment]
@jamieshark I've tagged you in this because there is going to be a tricky bit of back and forth between you and steve on this because the styles are obviously quite integral to the functionality. You might want to synchronize.

**Comment by jthrilly** [comment]
@jamieshark - let me know when the input components are implemented, and I'll close this issue.

**Comment by jamieshark** [comment]
## Estimate (8)
- Style components (2)
- Import UI Components into Form Builder (6)

**Comment by jthrilly** [comment]
## Estimate (12)
- Style components (4)
- Import UI Components into Form Builder (8)

**Comment by rebeccamadsen** [comment]
Estimate (12)
--

- Style components (4)
- Import UI Components into Form Builder (8)

**Comment by jamieshark** [comment]
Just finished up styling the components via https://github.com/codaco/Network-Canvas-UI/pull/12

I have a question regarding storing the form data with multiple checkboxes. Let's say we have two checkboxes that have names of `likesDogs`, `likesCats`, `likesBirds` all under the question of `preferredPets`.

Is it preferable to have the form data stored as `{ preferredPets: ['likesDogs', 'likesCats', 'likesBirds'] }` or `{ preferredPets: { likesDogs: true, likesCats: false, likesBirds: true } }`

Does that make sense?

**Comment by wwqrd** [comment]
It depends on the question, but there are cases where `likesCats: false` is an explicit attribute you want associated with a node (rather than needing to infer it from what is absent). @jthrilly Correct me if I'm wrong.

**Comment by jamieshark** [comment]
https://github.com/codaco/Network-Canvas/pull/197/files - Here's the PR replacing the inputs!
