### ISSUE TITLE
Roster-based name generator

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#127]
# Description
This interface is a variant of the name generator, that allows respondents to choose from a pre-defined list of alters instead of creating them from scratch.

A typical use would be in a setting where all actors in a network are known (such as a classroom).

We have no interface mockups available for this interface, since it was conceived off after our design consultation.

There are _three_ proposed interfaces for this, which suit different network sizes and configurations. We can create three interfaces, or we can bundle this functionality into one interface with some logic for switching between them. 

## Auto complete box
This will be suitable for large rosters, where it would be impractical to show all potential network members at once.

Essentially, the new node form is replaced by an autocomplete input, which is triggered after x keystrokes and only allows options from the predefined list to be selected. It is important to note that the autocomplete text might contain place names rather than simply people names, so this matching might need to work across multiple node properties.

## Node select
This interface will be suitable for smaller rosters, where it is practical to show all potential network members at once.

The participant will be able to select any nodes on this screen, with those selected being brought into the current interview.

## Pre-populating the interview
This is not really a roster interface, but is included here for clarity. Some interview protocols will want to include an entire external network from the start. That is, they will not ask the participant to nominate any alters - all alters will automatically be included from the start. In these cases, the alters will be stored within the protocol file directly when it is loaded. 

#Specification 
To be determined. 

# Progress

- [x] Implement side panels in existing name generator.
- [x] Implement node list select interface (#265)
- [x] Implement auto complete name generator (#264)

**Comment by jthrilly** [comment]
Discussed this week was the need to have roster based name generation.

This needs to support different types of actor (i.e people, venues).

**Comment by michellebee** [comment]
Some thoughts from meeting with school psychology phd students: 

1. roster-based name gen should be optimized for working with schools and/or organizations.  typical scenerios will be:
 - students nominating other students
 - teachers nominating students with whom they have a particular relationship with.
 - we may also want to support observers reporting the relationships they see other children having with each other. this might bypass the namegen stage entirely and go straight to the alter layout/alter connection stages.

2. we should have functionality for both name autocomplete and a pull down list for those that need/require it.

3. it will be important to be able to sort rosters by particular variables - for school research, these variables will likely include: name of school; grade; last name of teacher or some other identifier to find the classroom. 
- we will likely want to autosort rosters by data input by the researcher or interviewee in the stage0/intro screen.

**Comment by pfsj** [comment]
> we should have functionality for both name autocomplete and a pull down list for those that need/require it.

> it will be important to be able to sort rosters by particular variables - for school research, these variables will likely include: name of school; grade; last name of teacher or some other identifier to find the classroom.

For the 'pull down list', would it be possible to borrow from our development of the longitudinal component from RADAR? This would include using a sidebar, similar to the one in the longitudinal version, with all possible nodes listed that is sortable/instant searchable on the left hand side of the screen. For example, if I typed 'Pa' in this sidebar, only nodes with first or last name starting with "Pa" would appear in the sidebar. If nothing is typed, this list would also be scrollable just like the longitudinal version is. These nodes could be dragged and dropped into the given name gen just like the longitudinal version.

> we may also want to support observers reporting the relationships they see other children having with each other. this might bypass the namegen stage entirely and go straight to the alter layout/alter connection stages.

My PhD advisor Jenna Neal would be very mad at me if this feature wasn't included. She uses it all the time to construct "cognitive social structures" in her work. Although I worry about spending too much time on this, given how this feature would simply allow for automatically creating nodes for all individuals on a roster and skipping the name generator I think(?) it would be relatively easy to implement.

**Comment by jthrilly** [comment]
@pfsj can you say more about how exactly the cognitive social structures process works? The nodes are predefined, and the edges are the focus of the interview? Could have implications for #126 and also require supporting pre-populating interviews with nodes/edges (which would presumably happen in the architect app).

**Comment by pfsj** [comment]
Precisely, it's commonly used to examine things like "hang out" networks in classrooms. All individuals provide data on the perceived connections between their classmates (in addition to their own connections to those individuals), very similarly to how individuals provide data on the perceived connections between alters in a traditional personal network interview. This data is aggregated within the whole network using some rule of aggregation (Carter has a great Bayesian modeling method for doing this). Incidentally, this also gets around the missing data problem which is rather common in classrooms given that it's common for a sizable minority of parents to refuse to consent to research for their children.

As for how it would function in the suite, I would imagine it would happen similarly to any roster feature where a roster is supplied in the Architect and some setting is toggled that indicates you want to include all rostered individuals in the network. When the interview is started, you are correct that this would automatically add those nodes to the network and, as Michelle notes, this would skip the name generator phase. Most commonly, it would also lead directly straight to the layout phase where all members of the roster (e.g., classroom) are arranged and subsequently to as many edge creation stages that are required to capture the required data.

**Comment by pfsj** [comment]
@jthrilly Writing this up did make me realize that the roster use case does demand special consideration on the data storage side. Although, these same demands will be necessary whenever my entity resolution grant gets funded and we need to accommodate that use case as well.

**Comment by jthrilly** [comment]
Good thinking. I would suggest making an issue in the Server repo, and referencing it here just to remind you later.

**Comment by lizmcconnell** [comment]
From focus group on July 7, 2017: Explore what formats we would be using for small, medium, and large networks. For example, may use review and select for smaller rosters and recall for larger rosters. Need to think about if this might shape user experiences of other screens down the line. Also need to think about how this works longitudinally: do they pull in the data from their last visit?

**Comment by rebeccamadsen** [comment]
Do we show the auto complete vs node select vs prepopulate interface based on some number of nodes, or as a specification in the protocol? Are we overloading the "new node" button, or have some other button in its place? Can nodes that were added via any of these methods be "edited" by users, and if so, does it change a local copy and not the master copy? If the users can edit, do they need a way to revert to the master version for a person?

I assume each of these interfaces we would be creating the lists to show or match against in the protocol? What information would we need about the people on the lists, or does that vary?

For the prepopulate version, where would the nodes on the list appear? One of the side panels? Or in the main node list? For one or all of the prompts? Can users delete from the list, and if so do they need a way to revert to the original list? Are new nodes part of this interface?

**Comment by jthrilly** [comment]
> Do we show the auto complete vs node select vs prepopulate interface based on some number of nodes, or as a specification in the protocol? 

This is something that is part of the protocol specification and that will be up to the researcher to make the correct choice regarding. We will be writing guides to help with this.

>Are we overloading the "new node" button, or have some other button in its place? Can nodes that were added via any of these methods be "edited" by users, and if so, does it change a local copy and not the master copy? If the users can edit, do they need a way to revert to the master version for a person?

The roster nodes will have some attributes already, but will be editable once they are brought into the interview as with any other node. Properties they have that are not defined in the variable registry will not be editable, by definition, since there will be no way to create a form that maps an input to these variables.


> I assume each of these interfaces we would be creating the lists to show or match against in the protocol? What information would we need about the people on the lists, or does that vary?

I don't understand this question. Can you clarify @rebeccamadsen?

> For the prepopulate version, where would the nodes on the list appear? One of the side panels? Or in the main node list? For one or all of the prompts? Can users delete from the list, and if so do they need a way to revert to the original list? Are new nodes part of this interface?

This would be in the side panels, yes. This mode is basically the same behavior we have currently implemented.

**Comment by rebeccamadsen** [comment]
> I don't understand this question.

I think you kind of answered it already. Just that the lists will defined in the protocol and variable registry. Will we ever need more than one list  of nodes in the protocol? e.g. if they want to have one list for auto-complete but a second list for pre-populating?

**Comment by jthrilly** [comment]
Those lists will be contained in the data key of the protocol. Think of it this way: if I have a network stored in the data key (`{ nodes: [], edges: []}`), I can use that in an autocomplete box, I can show it in a side panel, or I can just show those nodes as a list. I could have _three_ networks defined in the data key, and use a different one for each.

**Comment by rebeccamadsen** [comment]
Some sketches. So "prepopulate" seems like functionality we have:
![img_20171207_114053292](https://user-images.githubusercontent.com/16093053/33726903-695793c0-db44-11e7-949c-ec96483193b7.jpg)

If both "node select" and "auto complete" make use of the "Add node" button, then it seems like those options and the current "add node" dialog are exclusive to each other, so the protocol would need to specify one of those three choices. Unless I am missing something there?

Node select could be kind of like a mix between the "add node dialog" and a "selectable" node list, though I'm not sure if we want to select one node or multiple:
![img_20171207_114112676](https://user-images.githubusercontent.com/16093053/33726901-691895a8-db44-11e7-94c8-7aea60661fd3.jpg)

And auto complete has several possible directions. As an input field, it could show the matches in a dropdown style list, or in a node view. But a node view has problems in that you don't see much detail so it may be possible to confuse one node with another. I lean towards a list view for this reason. Again, I have the question as to whether users will be adding multiple nodes at once, or just one "match":
![img_20171207_114125925](https://user-images.githubusercontent.com/16093053/33726902-69396a08-db44-11e7-9560-9e0627b0555d.jpg)

I think the "matching" or "filtering" mechanism has a few different approaches, but personally lean towards keeping the matching somewhat simple to start with. I think we ought to search across text based node fields for matches to the text the users type, but maybe not mess with the ordering of matches shown. If we want a delimiter, I lean towards using a space; not having a delimiter is fine too, but it would mean a space becomes part of the search. This is the difference between whether "Some name" matches "Some other name" or just "Some name"; or whether "Some name" matches a node with "some" in one field and "name" in another.

There are probably plugins we could use, but I lean towards keeping it simple until we've got a better handle use cases.
