### ISSUE TITLE
How do we implement touch interaction (i.e drag and drop for nodes)?

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#128]

**Comment by jthrilly** [comment]
Don't worry about the assignment @wwqrd, just a placeholder because I know you're working on this. Feel free to close if you think you have a handle on it, or provide more technical details of your implementation when you do it.

**Comment by wwqrd** [comment]
Touch, we're good, we can use hammer.

Drag, I've found a great library, with which we could implement our own version of drag and drop.

But before going down that route I think it'd be a good idea to experiment with something specifically designed for drag and drop, such as: http://react-dnd.github.io/react-dnd/docs-overview.html.

**Comment by wwqrd** [comment]
I tried loading the app in the iOS simulator today and it seems like react-router `<Link>` doesn't work? Is this something that behaves differently on devices? Assuming Cordova/Webkit view would be able to handle this to some extent?

**Comment by jthrilly** [comment]
I've not noticed this issue, and no, it should work exactly the same. The issue could be related to the use of hashHistory vs. browserHistory in react-router. We had an issue open at one point covering that. I will look into it.

**Comment by jthrilly** [comment]
Fixed this in 8cf888579f6abdaeb1db5de1ba0c6edbaa95c1b2

**Comment by jthrilly** [comment]
Looks resolved to me. Closing.
