### ISSUE TITLE
Develop a template for network canvas interface modules

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#136]

**Comment by jthrilly** [comment]
Can we design modules in such a way as they can tell the NC Architect app which parameters they expose automatically? i.e user plugs in v1.2 of namegenerator module, it exposes the data it will process, and the builder app exposes these variables as configurable.

**Comment by racpa** [comment]
We can use higher-order components and leverage the [recompose library](https://github.com/acdlite/recompose
)

**Comment by jthrilly** [comment]
Closing this as I believe we have achieved the goal of the issue.
