### ISSUE TITLE
App auto updating

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#152]
# Electron app update process for Alpha

## Purpose
We need to be able to push updates to our test sites, and ultimately our users, seamlessly and without effort. Initially we will tackle this issue for the electron app, and then move to address this process within android/cordova later.

## Functionality
- The app should track the state of the GitHub repository.
- Either using tags, a special branch, or something else, the app should be aware when a new version is available.
- It should be able to download, extract, perform any post- tasks, and then restart the app (if needed).
- This is taking place in the electron environment, so node is available. The specifics of how this works will need to be researched. If there are multiple solutions, let's talk about them!

**Comment by racpa** [comment]
## Electron
- As I have limited experience with Electron the immediate results bring up [Electron's autoUpdater](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md) and the likely solution being [Nuts](https://github.com/GitbookIO/nuts)
## Cordova
- [CodePush](https://github.com/Microsoft/code-push) is what I have utilised for react-native/cordova.

**Comment by jthrilly** [comment]
Thanks @racpa.

I've taken a quick look, and it seems you are correct that these are the best pre-made options. Do you have any thoughts on if it would make sense to build our own functionality instead? What are the pros and cons?

One of the things I dislike about Squirrel and Nuts is that they seem to require a release server. Yes, they can be minimal stateless apps (like, something we could host for free somewhere) but it still adds maintainability issues to our project. We need to remember that we are only funded for another 4 years, and the project infrastructure must be robust enough to keep working after that.

With that said, we have access to a decent VPS. If we need a release server, we can certainly do it.

Either way, next steps seem to be to explore this functionality in a feature branch. What do you need from me to make that happen? i.e would you like VPS access to explore that, or are you happy experimenting with heroku?

**Comment by jthrilly** [comment]
Also interested in the opinions of @codaco/network-canvas-team more broadly on this.

**Comment by racpa** [comment]
## Release-Server
- Heroku could be used, but on the free tier it will eventually have downtime.  Will the VPS eventually be unavailable in the future? 

## Alternatives
The problem that may eventually arise with a custom solution are the differences installing onto different platforms.  Luckily we could more than likely bootstrap other open-source alternatives for a custom-fit to track github-releases.  

### New Builder
- We could use a completely new [electron builder](https://github.com/electron-userland/electron-builder) that comes complete with [autoUpdating ](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater)using GH([Example](https://github.com/iffy/electron-updater-example)).

### AutoUpdater solutions
- Otherwise, I have to look into what the current electron dependencies are capable of. We could probably build on top / draw inspiration from this [electron-simple-updater](https://github.com/megahertz/electron-simple-updater) or [electron-gh-releases](https://github.com/jenslind/electron-gh-releases)

**Comment by jthrilly** [comment]
> Heroku could be used, but on the free tier it will eventually have downtime.
Exactly. This is not the best solution for us.

> Will the VPS you provide me with be unavailable in the future?
Eventually, yes. We will fund it for as long as we can with the money we have left at the end of the project, but one day it will go offline. We should aim to not depend on it, if possible.

> The problem that may eventually arise with a custom solution are the differences installing onto different platforms. Luckily we could more than likely bootstrap other open-source alternatives for a custom-fit to track github-releases.
So, I think you're talking about platform specific versions of our node dependencies, right? If so, I'm not clear on how electron handles this. I know there are installers, which I presume handle node package installation, since node is bundled with electron. Anyway, It hasn't impacted us yet, because we haven't done any platform specific stuff. I haven't looked into it, but I think the only things we would do would be things like file dialogues, and hopefully electron abstracts these for us, so we won't actually end up with anything platform specific in our deps. Good to be aware of though.

## Next Steps

So, I like the look of electron-builder, but I worry that it is overkill. I think that having this work through a CI system would be great (which we don't currently have, but can get through GitHub education), and would certainly tie in to testing and generally higher quality dev practices, but is it introducing needless complexity?

I'd like you to look into these options in a little bit more depth than I have time to do directly, and then make a recommendation. Then, we can work on getting this up and running in a feature branch. That sound good?

It seems like whichever way to cut it, we need to get signing certificates for macOS and Windows (#158). Let me know once the decision is made, and I will look into purchasing these.

**Comment by wwqrd** [comment]
We could look into setting up something like [Dokku](https://github.com/dokku/dokku) on the VPS. That way we use the resources we have available, but also pave the way for future users beyond the scope of the budget to run the release server on their own Heroku instance with minimal effort.

**Comment by jthrilly** [comment]
So I don't envisage anyone else will be running a release server for this project. Nobody is likely to be interested enough to do so. And really, why, on a fundamental level, do we need one? GitHub provides an API for tracking releases.

**Comment by racpa** [comment]
I initially created a feature branch with nuts, which I have killed due to your previous statement regarding a release-server.

Electron-builder's documentation is quite succinct.  But transitioning to this would require some redundant work as there are already packager build scripts.  I assume they could just be copied into one script using electron-builder's API, which would trigger a chain for CI.

I created a new local feature branch which is taking a GH approach.

**Comment by rebeccamadsen** [comment]
Auto app updating is outside my current experience, but my last project used CI -- specifically CircleCI (with docker). It integrated with github, so whenever someone committed code, tests also kicked off. I did not set it up, though, so it was a bit of a black box where docker and circleCI connected.

**Comment by wwqrd** [comment]
@jthrilly if nothing else something like dokku might make it easier for us to deploy our own code. Say the choice is between setting up something like that, and writing `systemd` service configurations for each app on the VPS? Making it somewhat compatible with Heroku-like services is an added bonus.

Either way, we can can script deployments (of the server) using CI like you suggest @rebeccamadsen. There was talk of using Travis for this I think? Though I think the overall discussion here is about sending out updates to end users in the vein of software updates, which I'm not sure could be handled by CI?

**Comment by jthrilly** [comment]
Am I going crazy, or is there a specific reason that we need anything other than 'some code' that checks GitHub using their API for a release, and downloads and extracts it? CI seems like another issue entirely.

**Comment by jthrilly** [comment]
Just heard from @racpa that we are going with electron-simple-updater, which basically does exactly this.

**Comment by wwqrd** [comment]
I like the sound of that. Less moving parts!

**Comment by rebeccamadsen** [comment]
+1

**Comment by racpa** [comment]
Simple-updater does the job, and publishing to GH is capable with another add-on.  The drawbacks now are more in the electron packager/build scripts for them to spit out the proper files.
