### ISSUE TITLE
Categorical bin interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#156]

**Comment by katebanner** [comment]
Feedback @berniehogan collected at SMS July 2017:

 The categorical bins are not testing very well at all. People don’t get the interactivity. The way people are removed is unclear. Also, first in, last out sort order for both categorical and ordinal could potentially be an issue. @berniehogan feel free to elaborate further.

**Comment by rebeccamadsen** [comment]
This seems similar to the ordinal bin, I think, though it's possible the sorting isn't required, or maybe we need filtering, or some other difference I haven't thought of. So this:

```
{
  "id": "catBin1",
  "type": "CategoricalBin",
  "label": "Categorical Bin",
  "subject": {
    "entity": "node",
    "type": "person"
  },
  "prompts": [
    {
      "id": "contactType",
      "text": "Contact type categorical variable",
      "variable": "contactType",
      "//": "Categorical variables have valid options defined in variable registry.",
      "bucketSortOrder": [
        {
          "property": "nickname",
          "direction": "desc"
        }
      ],
      "binSortOrder": [
        {
          "property": "nickname",
          "direction": "desc"
        },
        {
          "property": "age",
          "direction": "desc"
        }
      ]
    },
    {
      "id": "discussType",
      "text": "Discussion type variable, with a much longer prompt than the previous prompt. Please also note that this prompt uses the color override to style these bins differently than the main prompt.",
      "variable": "discussType",
      "color": "cat-color-seq-4"
    }
  ]
}
```

However, I notice in the wiki that a [categorical variable](https://github.com/codaco/Network-Canvas/wiki/Variable-Types) is "An unordered group of options, where values can comprise _any number_ of options." Is that accurate for the categorical bin as well? Any number of options? That definitely affects the interface design if a node can be placed in any number of categories.

I'm not sure what interactivity users didn't get. Is it clicking on a category to drill down and see what nodes they put there? Clicking to remove? Or something else? If it is just the removing from a category part, maybe we could instead have users drop a node outside the drilled down category to remove it, or alternatively provide a "deselect" icon they can drag to (similar to the trash bin) that just removes the category (placing it back in the unsorted list). Or I can see what else I can think up while working on the rest of the interface.

Is there a limit on the number of categories one interface could hold? I'm guessing not?

**Comment by jthrilly** [comment]
> However, I notice in the wiki that a [categorical variable](https://github.com/codaco/Network-Canvas/wiki/Variable-Types) is "An unordered group of options, where values can comprise _any number_ of options." Is that accurate for the categorical bin as well? Any number of options? That definitely affects the interface design if a node can be placed in any number of categories.

In theory, any number of options is possible. In practice, we will limit this interface to some practical number of options. The mockups showed 8, and I think that's more than generous.

In the prototype, I implemented a very silly algorithm to try to maximise the size of the containers, given the number. For the real thing, I think we should be able to use CSS to increase the size of the bins if there are fewer options. 

On that note, I also think we can use the FLIP animation technique to handle the interaction for tapping a bin to see its contents. I will create a mockup of the sort of thing I am thinking and attach it here. Steve is the person to speak to about FLIP.



> I'm not sure what interactivity users didn't get. Is it clicking on a category to drill down and see what nodes they put there? Clicking to remove? Or something else? If it is just the removing from a category part, maybe we could instead have users drop a node outside the drilled down category to remove it, or alternatively provide a "deselect" icon they can drag to (similar to the trash bin) that just removes the category (placing it back in the unsorted list). Or I can see what else I can think up while working on the rest of the interface.

It was that there was no discoverability for the "remove node from bin" functionality (you have to tap the bin to expand it, and that wasn't obvious). The other issue was that you dragged a node into a bin,  but you tapped a node to remove it. The discoverability thing can be put aside for now, and we can address the inconsistent interaction by allowing a node to be dragged out of a bin, and either back into the bucket, or directly into another bin. I'll try and integrate this into a mockup.

**Comment by rebeccamadsen** [comment]
Okay. Makes sense. Does this interface only consider the case where each node fits only one category? So, we wouldn't be using this interface to ask about someone's ancestry, for example, because someone might have (theoretically) German, Swedish, Welsh, and English ancestors and fit multiple categories?

**Comment by jthrilly** [comment]
> Okay. Makes sense. Does this interface only consider the case where each node fits only one category? So, we wouldn't be using this interface to ask about someone's ancestry, for example, because someone might have (theoretically) German, Swedish, Welsh, and English ancestors and fit multiple categories?

I think that sort of question would lend itself better to an alter-form, or even being added to the new node form.
