### ISSUE TITLE
Map Interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#157]

**Comment by jthrilly** [comment]
@michellebee noted that someone had expected that because nodes were draggable on all other interfaces, they would also be present on the map screen. 

Should we implement a 'node bucket' type interface (similar to the planned functionality for the sociogram #126) that allows nodes to be 'dropped' onto map polygons?

**Comment by katebanner** [comment]
@berniehogan wanted to introduce Kumu.io as a nice (but not amazing) tool for creating live maps based on data. He thinks Polinode is better.

**Comment by katebanner** [comment]
Ability to select multiple polygons
https://github.com/codaco/Network-Canvas/issues/202

**Comment by jthrilly** [comment]
This interface has been postponed indefinitely pending further funding.
