### ISSUE TITLE
Demo version for teaching purposes

### ISSUE THREAD

**Issue by lizmcconnell** [codaco/Network-Canvas#182]
From focus group on July 7, 2017: Participant observed more teaching social networks classes at the undergraduate level and is very interested in using Network Canvas as a teaching tool. Use might include generating data in class and then downloading data that students can analyze and work with. This could be very similar to the demo version we currently have.

**Comment by jthrilly** [comment]
This requires a specification from the team. @katebanner - an agenda item for a next team meeting?

I think we should implement this as the "demo protocol" within the app, to kill two birds with one stone, as it were.

**Comment by jthrilly** [comment]
@berniehogan - could you copy and paste the teaching protocol that you put together here, just for reference and so the other developers have access?

**Comment by jthrilly** [comment]
Ongoing project, with the first version being implemented in #322
