### ISSUE TITLE
Name generator panels should have a fixed width, and contents should wrap

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#186]
The name generator panels grow in width, and nodes within it are on one line rather than being wrapped.

<img width="1907" alt="screen shot 2017-08-03 at 1 43 05 pm" src="https://user-images.githubusercontent.com/1387940/28922356-bb393dd4-7851-11e7-805f-267a4a1bcb5a.png">

**Comment by jthrilly** [comment]
Almost fixed in latest commits. Needs a fixed width to ensure it doesn't shrink with less than three nodes in a panel.

## Time estimate: 0.5

**Comment by wwqrd** [comment]
What are you seeing? I've get a 3 column fixed width when I look at it?

**Comment by wwqrd** [comment]
Actually, I see that slight shrinkage too

**Comment by wwqrd** [comment]
Okay so on second approach, I see why it was implemented with the dynamic width, so the panel width can animate away when empty. So a little more thought is necessary.

Estimate (2)

**Comment by jthrilly** [comment]
Just to add that I would prefer not to animate width, since it isn't GPU accelerated. Can we stick to animating position (transform) and opacity? Use scale if you absolutely need to.

**Comment by wwqrd** [comment]
Okay, I've gotten this working as expected. Unfortunately I can't see a way around altering the width since removing the panels changes the layout (which opacity and transform won't do). I've added the translateZ gpu hack, along with the more forward compatible 'will-change' property, to help with rendering.

**Comment by jthrilly** [comment]
So this is ready to test? Moving to the review queue. Nice!

**Comment by wwqrd** [comment]
Straight on master :shipit:
