### ISSUE TITLE
Scrollable fade obscures the top of nodes

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#188]
The fade effect we are using obscures the top of nodes placed in that container. The original implementation placed the fade behind the title of the container so that nodes scrolled out of view behind this element. The new implementation probably calls for more top padding in the actual node container, since the header is now visually separated. We will need to balance this visually, probably by reducing the padding in the title row.

<img width="369" alt="screen shot 2017-08-03 at 1 46 42 pm" src="https://user-images.githubusercontent.com/1387940/28922619-d2e0bca4-7852-11e7-9634-850f9ac1d1b5.png">

# Tasks

- [ ] Update `behaviour/scrollable` to not obscure first components unless scrolled

**Comment by wwqrd** [comment]
The original `Scrollable` component took account of this by using pseudo elements and detecting the onscroll event. Rather than adding padding, I'd suggest we go back to doing in that way?

**Comment by jthrilly** [comment]
Is there a reason that we moved away from it? If not, then absolutely. My gut feeling is that detecting the event is relatively messy and could potentially introduce stutters. I would also be concerned about how it would look visually...

In the example above, if the scroll event was triggered, wouldn't that make the fade effect appear suddenly on top of the nodes?

**Comment by wwqrd** [comment]
It shouldn't (didn't) stutter, the check is throttled and only performed on the scroll event, and the transition is animated. It was changed so that we can use webkit mask for real opacity (whereas before it was covered with an opaque gradient). I'm hoping we may be able to animate the mask.

**Comment by wwqrd** [comment]
So it seems we can't animate the mask (using css), I've pushed up a change which alters the mask instantaneously, which I think actually is pretty un-noticeable. We could revert to the pseudo-element opaque masks for animation, but that has the overhead of requiring the background color to be declared for each scrollable component.

**Comment by jthrilly** [comment]
So is this in master? Ready to review now?

**Comment by wwqrd** [comment]
Yep!
