### ISSUE TITLE
Panels should have a configurable color highlight (4)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#189]
Side panels should use different accent colors (the colored strip along the bottom) to differentiate them. This should be a parameter of the panel component that is configurable, but it might make sense to define some default colors. 

I propose:

- _Existing nodes in this session_ - mapped to default node color
- _Panels showing nodes from an external data source_ - mapped to primary action color

These colors should map to the palette definitions.

<img width="379" alt="screen shot 2017-08-03 at 1 52 22 pm" src="https://user-images.githubusercontent.com/1387940/28922788-71adb850-7853-11e7-8072-f4782eaa23a4.png">

# Tasks

~~- [ ] Add node color palettes to sass `palette()`~~
~~- [ ] Update node list to use appropriate palette for different node types~~
- [x] Update panel (NodeList/NodeProvider) to have a "highlight" property. Default value is primary action color. Multiple panels will automatically default to different colors from one another. (4)

**Comment by wwqrd** [comment]
## Estimate (3)

- Add node color palettes to sass `palette()` (1)
- Update node list to use appropriate palette for different node types (2)

**Comment by jthrilly** [comment]
Clarification: the color accent is _per panel_ and does not necessarily correspond to the color of the nodes within it.


# Estimate: 4
- Add node color palettes to sass palette() - This is already being dealt with here: #169 
- Update node list to use appropriate palette for different node types - This is incorrect. Propose:
- Update panel to have a "highlight" property. Default value is primary action color. Multiple panels will automatically default to different colors from one another. (4)

**Comment by rebeccamadsen** [comment]
Default to different colors? Is there a max number of panels we expect, or would we generate hex values when we run out of our color scheme?

**Comment by jthrilly** [comment]
@rebeccamadsen - check out the primary, secondary, and tertiary colors in the style guide. We've got loads to cycle through. 

Also, for practical reasons, we will only normally have two panels on an individual screen,

**Comment by wwqrd** [comment]
Sorry, for the confusion, the terminology was correct though:

We need to update NodeList https://github.com/codaco/Network-Canvas/blob/master/src/components/Elements/NodeList.js, to change the colors.

`Panel` is just a UI element which can contain anything, and `Node` doesn't have any knowledge of it's context.

Another alternative would be to create a new component which wires up the two (Panel, and NodeList) for you.
