### ISSUE TITLE
Fonts don't load correctly on iOS, and perhaps elsewhere (2)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#190]
Our custom font does not load correctly on iOS, and perhaps other platforms. The developer console shows the files were looked for at `file://fonts/`.

This is probably an issue with web pack config, but if it is platform specific could also be to do with security settings.

<img width="1137" alt="screen shot 2017-08-03 at 7 30 12 pm" src="https://user-images.githubusercontent.com/1387940/28937275-43526238-7882-11e7-97b2-1fb831c78b3d.png">

![screen shot 2017-08-03 at 7 30 07 pm](https://user-images.githubusercontent.com/1387940/28937325-6d8d76a0-7882-11e7-9d35-657f4bd91a4d.png)

# Tasks

- [x]  Update webpack build to include fonts from UI package (2)

**Comment by wwqrd** [comment]
Related issue: https://github.com/codaco/Server/issues/13 Think this should be on the UI project.

**Comment by jthrilly** [comment]
Do you mean you think the fonts themselves should be within the UI project? I'm not sure how that would work.

**Comment by wwqrd** [comment]
As far as I understand it the fonts already are in the UI project, and something about that not working is affecting both `Network Canvas` and `Server`.

**Comment by jthrilly** [comment]
Oh! The fonts are also in `/public` so they need to go away from _somewhere_.

**Comment by wwqrd** [comment]
## Estimate (2)
- Update webpack build to include fonts from UI package (2)

**Comment by rebeccamadsen** [comment]
Estimate (2)
--

- Update webpack build to include fonts from UI package (2)

**Comment by jthrilly** [comment]
# Estimate: 1

**Comment by jthrilly** [comment]
The fonts do not load inside Cordova, so this issue is still open.

**Comment by jthrilly** [comment]
Scratch that. Was testing off of the wrong branch. 💩
