### ISSUE TITLE
Local interview protocol doesn't load in built version of the app (6)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#192]
The built version of the app looks for the local interview protocol at `http://localhost:3000/`, which obviously doesn't work outside of our dev server setup. 

We need a way of loading the local protocol across all our platforms. I have temporarily pointed the app to our remote protocol hosted on GitHub, but we need this to work in offline settings.

# Tasks

- [ ] Update `ducks/modules/protocol` to allow support local file access (desktop) (4)
- [ ] Update local file access to support cordova (2)

**Comment by jthrilly** [comment]
## Total estimate: 4

**Comment by wwqrd** [comment]
## Estimate (4)

- Update ducks/modules/protocol to allow support local file access (desktop) (2)
- Update local file access to support cordova (2)

**Comment by jamieshark** [comment]
## Estimate (4-6)
- Update ducks/modules/protocol to allow support local file access (desktop) (2-4)
- Update local file access to support cordova (2)

**Comment by rebeccamadsen** [comment]
Estimate (6)
--

- Update ducks/modules/protocol to allow support local file access (desktop) (4)
- Update local file access to support cordova (2)
