### ISSUE TITLE
Start/setup screen (3)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#193]
We need a more polished initial setup screen for the alpha. Obviously, this isn't going to last, so no need to make it too perfect. 

# Tasks

- [x] Some introductory text and branding (2)
- [x] A choice between loading the local demo interview protocol, and a remote protocol (1)

**Comment by jthrilly** [comment]
## Total Estimate: 3

 - Some introductory text and branding. (2)
 - A choice between loading the local demo interview protocol, and a remote protocol. (1)

**Comment by jamieshark** [comment]
# Estimate (2)
- Some introductory text and branding (1)
- A choice between loading the local demo interview protocol, and a remote protocol (1)

**Comment by rebeccamadsen** [comment]
Estimate (3)
--

-  Some introductory text and branding. (2)
-  A choice between loading the local demo interview protocol, and a remote protocol. (1)
