### ISSUE TITLE
Audio instructions for each interface

### ISSUE THREAD

**Issue by katebanner** [codaco/Network-Canvas#201]
From demo feedback meeting with Cui Yang on 7/28/2017:
Cui suggested that researchers who work with low literacy populations would benefit from the ability to record audio instructions for each screen. One suggestion was to give researchers the ability to record their own voice reciting the instructions, another was for researchers to have the ability to upload an audio file with certain parameters.  

Team discussed this point on the 8/4 team meeting and it was decided that this is not priority since we are not offering a self-administered product; however, good to keep in mind if this issue arises again in outreach activities.

**Comment by jthrilly** [comment]
Could be implemented within #218
