### ISSUE TITLE
Ability to select multiple polygons

### ISSUE THREAD

**Issue by katebanner** [codaco/Network-Canvas#202]
From demo feedback meeting with Cui Yang on 7/28/2017:
Suggestion that we allow selection of multiple polygons on the mapping interface, rather than just one square as we do on RADAR. Cui mentioned this in the context of "the neighborhoods where you know them or meet up". Also, could be important for homeless participants who do not necessarily have a fixed location.

**Comment by jthrilly** [comment]
Should be in #157
