### ISSUE TITLE
Tapping a side panel's title should expand it, and minimize/hide any other panels

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#207]
Vertical space is limited, particularly on 4:3 aspect ratio devices. This feature would add the ability to "collapse" a panel into its heading, creating additional room when two panels are present.

**Comment by jamieshark** [comment]
subtasks
- [ ] SASS to facilitate panel expanding/contracting
- [ ] Implement expansion/contraction in the parent component (Panels) taking into account #236 
- [ ] Create tests
