### ISSUE TITLE
New node form improvements

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#215]
Some enhancements to the new node modal.
- [ ] Mobile form UI for the add new node form

The 4:3 aspect ratio experience for the new node modal is currently missing. It will likely require significant work to implement. The key difference from the existing modal is that it aims to avoid obscuring the inputs by only displaying one at a time, with next/previous functionality to navigate through the form.

- [ ] The new node modal should optionally remain open while adding new nodes. It can still be closed manually by the user. 

This came from feedback that some users wanted to keep entering names quickly, without wanting to click the "add new node" button each time. Two obvious approaches to implementation: (1) a checkbox or additional button that says "add another" rather than "submit". (2) A configuration property for the interface that makes the default "submit" button keep the form open, perhaps with some sort of notification/nudge when the forum has been submitted to let the user know the node was added.

**Comment by wwqrd** [comment]
Is "New node form stays open while adding new nodes. Closed manually by the user." still an issue?

**Comment by wwqrd** [comment]
Split into two tasks:
https://github.com/codaco/Network-Canvas/issues/235
https://github.com/codaco/Network-Canvas/issues/234
