### ISSUE TITLE
Instruction Interface

### ISSUE THREAD

**Issue by katebanner** [codaco/Network-Canvas#218]
Bernie's feedback from Ben/Jenny 6/9/2017:
It should be much more obvious when the person first lands on the screen what to do. I think that a preceding screen with a simple animation and the text:

"On the next screen, drag the nodes onto the circle. Arrange the nodes such that..." 

Ben and Jenny, just like many others, saw the animated gif and this helped to make sense of the edge generation. I propose that we consider more of these canned interactions on screens to precede the screen.

**Comment by jthrilly** [comment]
# Purpose
An interface that contains arbitrary text and (optionally) animated GIFs/images. To be used to allow researchers to explain an upcoming task, or to introduce a concept.

# Specification

To avoid complexity, I suggest we structure which with some number of "content boxes" (3?), which can either contain text or an image.

``` 
{
  title: "Title for the screen"
  content: [
    "<p>Some arbitrary text content that can contain <strong>HTML</strong> tags.</p>" // Limited to n characters/words, and with HTML generated in architect.
    myImageResource, // Could this be a base 64 encoded image? If not, we will need to address external protocol assets (discussed in a separate GH issue
    "<p>Some additional content.</p>"
  ]
}

**Comment by jthrilly** [comment]
Just a reminder that a full implementation of this issue depends on a resolution to #238. We can however implement the layout logic and the fundamental API without this.

**Comment by jthrilly** [comment]
<img width="2032" alt="screen shot 2018-01-29 at 3 31 22 pm" src="https://user-images.githubusercontent.com/1387940/35518460-8fa134d4-0509-11e8-8209-0a6c2193a43d.png">
<img width="2032" alt="screen shot 2018-01-29 at 3 31 14 pm" src="https://user-images.githubusercontent.com/1387940/35518461-8fb93a34-0509-11e8-94e5-9d7922588cee.png">

**Comment by wwqrd** [comment]
That spec looks fine to me.

I'll limit the content items to 2, which is enough for a large video/graphic and a description.

Alternative layouts might be necessary if we start to expand the number of items in content. But we decided to postpone that for now.
