### ISSUE TITLE
Touch/mouse movement optimization

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#228]
Several views are updated based on mouse/touch movement, they are mostly unoptimised.

Some possible improvements we could make to improve performance are:

- Throttle methods calls from events:
  ```
  constructor() {
    ...
    // Limit calls to 24 p/s
    this.calledOnMousMove = throttle(this.calledOnMouseMove, 1000/24);
  }
  ```
- Use `shouldComponentUpdate()` in the component lifecycle to determine if a redraw is necessary.
- Use `requestAnimationFrame()` where applicable.
- Limit calls to reducers 
- Use memoized selectors on calculated properties
  ```
  mapStateToProps(state, props) {
    // We need to create new selectors per component to correctly memoize
    const getPropertyFromState = createSelector(
      [firstSelector, someOtherSelector],
      (list, properties) => find(list, properties),
    );

    return function(state, props) {
      return {
        myProperty: getPropertyFromState(state, props);
      } 
    };
  };
  ```

**Comment by jamieshark** [comment]
Maybe introducing a middleware that has a `.debounce` on certain properties would also help?

**Comment by wwqrd** [comment]
@jamieshark You mean rather than limiting actions in the first place? Cool idea! Rx.js is already used for the async stuff, and could definitely be used for throttling too.

**Comment by jthrilly** [comment]
@wwqrd - I think a lot of these issues have been dealt with through other changes we have made. In general, performance is much improved across the board, and rate limiting has been applied where appropriate. Can we close this?

**Comment by wwqrd** [comment]
Yeah I think we can close this for now, if we do another round of optimisations that could be a separate issue.
