### ISSUE TITLE
Hard coded node creation/edit form title

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#231]
Currently the node edit form is titled "Add a person". This is because the title is stored in the protocol form params, perhaps this should be updated to dynamically generate a title more like:

```
const title = `${verb} ${nodeType}`;

// or

const title = (verb, nodeType) => `${verb} ${nodeType}`;
```

Or this kind of update could be tackled when we look at i18n.

**Comment by jthrilly** [comment]
Relevant to #132
