### ISSUE TITLE
Simplify menu syntax

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#232]
# Purpose

Adding new elements to the menus, like utility functions requires additional code inside the respective menu components, that would probably make more sense inside App. Using a more react-like syntax might clarify usage and allow us to better place responsibilities.

# Specification

Use more React-like syntax, where concerns are nested less deeply. And callbacks can be handled elsewhere.

e.g.

```
// In App.js
<Menu>
  <MenuItem onClick={doThing()} />Do thing</MenuItem>
  <MenuItem onClick={doOtherThing()}>Do other thing</MenuItem>
</Menu>
```

**Comment by rebeccamadsen** [comment]
MenuItems became nested under MenuContent when we made part (but not all) of the [menu scrollable](https://github.com/codaco/Network-Canvas/commit/c431cefcb6a80e3490cbb13fe4f3fa079a1e71e9).

**Comment by rebeccamadsen** [comment]
Would this negate the need for the custom menu items? Or is this instead of adding menu items to the custom list in redux? Is this just for the session menu, or the stage menu as well?

**Comment by wwqrd** [comment]
Hmm, that's interesting about scrollable forcing a kind of composition. Not ideal. Perhaps we should make a scrollable component?

If we also add an item props to session/stage menu we could essentially leave the rest as is.
