### ISSUE TITLE
Mobile form UI for the add new node form

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#234]
# Purpose

The 4:3 aspect ratio experience for the new node modal is currently missing.  The key difference from the existing modal is that it aims to avoid obscuring the inputs by only displaying one at a time, with next/previous functionality to navigate through the form.

There is an example of a wizard style form in the Redux Form docs (http://redux-form.com/6.7.0/examples/wizard/), but we will probably want to make this work with CSS only if possible.

![05network_canvas_addperson_contexts_4x3](https://user-images.githubusercontent.com/1387940/30067785-b3245892-9253-11e7-827c-ab96931e0277.jpg)

# Specification

- [x] Update Form component to automatically generate a wizard style form from the protocol.

**Comment by jamieshark** [comment]
Just as a note, I would also +1 only using CSS, as it would prevent re-rendering the form elements as well. I think this would be fairly easy to implement.

**Comment by jthrilly** [comment]
I'm not sure everything here is possible using CSS, but certainly the basic look is. The component doesn't need to track state (progress through this wizard is okay to lose if the app were to crash or reset). Perhaps updating the modal component to have content "pages", with an optional "full screen" mode, and then updating the form to place an input in each content page is the way to go. The modal can then handle the page transition logic, and the form doesn't need to be changed.
