### ISSUE TITLE
Allow continuous addition of nodes

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#235]
# Purpose

The new node modal should optionally remain open while adding new nodes. It can still be closed manually by the user.

# Description
This came from feedback that some users wanted to keep entering names quickly, without wanting to click the "add new node" button each time. Two obvious approaches to implementation: (1) a checkbox or additional button that says "add another" rather than "submit". (2) A configuration property for the interface that makes the default "submit" button keep the form open, perhaps with some sort of notification/nudge when the forum has been submitted to let the user know the node was added.

# Tasks
- [x] Add "Add another" button to the new node form to allow continuous additions.

**Comment by rebeccamadsen** [comment]
Would the nodes get added all together at the end, when the user is finished, or one at a time?

**Comment by jthrilly** [comment]
One at a time would be the idea.
