### ISSUE TITLE
Upgrade to v2 spec of react transition group.

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#236]
# Purpose

There are certain limitations to the old react transition spec which effect how animations work in our app. For example, only one kind of animation is allowed within each group. In `<NodeList>` whereas ideally we might animate the "ghost" new node instantly, and the initial nodes staggered, we have the same animation for both, which is a bit jarring.

https://github.com/reactjs/react-transition-group

**Comment by jthrilly** [comment]
Staggered animation for node entry could look like this: https://examples.framerjs.com/#animation-staggered.framer

**Comment by jthrilly** [comment]
Hi fidelity mockup of staggered node animation:

![panel animation](https://user-images.githubusercontent.com/1387940/34522221-890f36aa-f089-11e7-9f7f-f918dd2b22bb.gif)
