### ISSUE TITLE
New Menu System

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#245]
## Purpose

The current animation between interview stages is a simple fade out/in. It is functional, but could be improved.

We have feedback indicating that creating a better sense of space within the app would improve comprehension. Additionally, we have developed an interview overview in the Architect software that shows the interview in a top-down timeline. This seems to have been well received. Reconciling these two points, we came to the conclusion that we should experiment with a vertical scroll animation between stages, and a timeline component to visualize progress through the interview.

## Mockups
![timeline mockup](https://user-images.githubusercontent.com/1387940/31546223-48a3acae-b01a-11e7-87e4-4b9dfabab987.png)

## Specification

- A timeline should be rendered on the left of the screen, with a circle representing each stage in the interview. The timeline scrolls automatically as the interview progresses, but cannot be scrolled manually by the user. The top of the timeline scrolls off the top of the screen, but the bottom visually originates in the "next stage" button - until the end of the interview is reached, at which point the user sees the 'terminal' of the timeline.
- If an interview stage contains sub tasks (such as multiple prompts), the timeline should represent each as a segment of the circle for the current stage. As the user progresses through the prompts/tasks, these segments should fill in with the primary action color. 
- The next button should trigger forwards navigation through the interview. In a change from previous behavior, clicking "next" on a stage with multiple tasks/prompts will advance the prompt to the last prompt, before subsequently advancing the stage.
- Tapping/clicking on the timeline itself, or swiping in from the left edge of the screen, will open a secondary menu view that will allow the researcher to move to any specific stage.

**Comment by jthrilly** [comment]
Michelle asks if the prompt swiper could/should also work vertically. She is concerned about the dissonance between the vertical movement of the menu and the horizontal prompts swipers. 

Suggestion: instead of the mini-dots, a pie chart that fills as progress happens through the stage.

**Comment by jthrilly** [comment]
A note that this issue depends on #276 having been completed.

**Comment by rebeccamadsen** [comment]
Is the mini-dots/pie chart thought with respect to the pips for prompts up above the prompt text, or in the side timeline? Is this a principle prototype, or just the image seen here in this issue? Is there a previous button in this design still?

**Comment by pfsj** [comment]
1) The mini-dots/pie chart are supposed to represent the pips for prompts. Although they are still shown in this mockup, I'm not sure if the pips will make it into the final system if we have the same functionality on the new menu via the mini-dots/pie chart.

2) This is just a mockup image for this issue.

3) We'll most likely have to discuss the back button with Josh. There will obviously have to be some way to navigate both directions but backwards navigation, which is likely a less common scenario, could also be accomplished other ways such as scrolling up and/or clicking on the 'timeline'.

**Comment by wwqrd** [comment]
> Michelle asks if the prompt swiper could/should also work vertically. She is concerned about the dissonance between the vertical movement of the menu and the horizontal prompts swipers.

It definitely could work vertically, it'd give less physical room for swiping. We could also support both (vertical and horizontal) touch events?

**Comment by bryfox** [comment]
I'm noticing one minor thing that I think would be nice to improve on in future iterations. When stages have multiple prompts and I advance to the next stage, prompt 0 of the previous stage appears briefly as the stage transition starts (part of the UPDATE_SESSION action). This is most noticeable with elements that don't animate, such as ordinal bins with different colors and the classmates cardLists (both seen in the development protocol).

**Comment by jthrilly** [comment]
> I'm noticing one minor thing that I think would be nice to improve on in future iterations. When stages have multiple prompts and I advance to the next stage, prompt 0 of the previous stage appears briefly as the stage transition starts (part of the UPDATE_SESSION action). This is most noticeable with elements that don't animate, such as ordinal bins with different colors and the classmates cardLists (both seen in the development protocol).

I've noticed this, too. Its like you get a brief flash of the initial stage state, whatever that may be.
