### ISSUE TITLE
Changes to drag and drop behavior in name generator

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#246]
After user testing we have decided to change the drag and drop behaviour on the name generator interface.

The changes are as follows:

- When a node drag starts, the droppable area _immediately_ highlights. Current behaviour is that the droppable area highlights when the node is over it.
- The behaviour for the "people you already mentioned" panel is changing from "tap to select", to "drag into the node list". That is, instead of the user tapping a node to nominate it when it is in this panel (causing it to be come highlighted), the user will instead drag nodes from this panel into the main node list, as is done with the "people from your previous visit" panel.

Other changes:
- The panel title should be a configurable property
- The color of nodes in the side panels should be a configurable property.
- The node should not immediately be removed from its container when it is being dragged. There should be a blank space where the node was, which disappears once the node is dropped.

**Comment by rebeccamadsen** [comment]
> When a node drag starts, the droppable area immediately highlights

Do we also want to have some other change to indicate when they are over the droppable area, or do is the visual cue of the node they are dragging being on top of the area enough? I know we don't highlight the trash bin in any other way right now.

> The behaviour for the "people you already mentioned" panel is changing from "tap to select", to "drag into the node list"

Does this mean that nodes in the "people you already mentioned" panel will not be deletable any more?
 How does this affect deleting nodes that are on multiple screens? I think right now deleting a node removes it from any of the screens, but wanted to make sure this is what we want.

> The panel title should be a configurable property...color of nodes

Configurable in the protocol, is that right? Do we want to have a default, or to expect these to be defined?

> There should be a blank space where the node was

Or possibly an inactive version of the node, or a node with a `-` to parallel the `+` one?

**Comment by jthrilly** [comment]
> Do we also want to have some other change to indicate when they are over the droppable area, or do is the visual cue of the node they are dragging being on top of the area enough? I know we don't highlight the trash bin in any other way right now.

The trash bin should actually scale when a node is over it, but doesn't currently. With regards to this, it would certainly be cool if we could do it as a two stage thing: immediately highlight valid droppable regions when the drag starts, and then further highlight when the node is over a valid region. Perhaps the initial highlight could use white and the hover highlight sea serpent? 

> Does this mean that nodes in the "people you already mentioned" panel will not be deletable any more?
No, it should be possible to delete the node still by dragging it to the bin.

> How does this affect deleting nodes that are on multiple screens? I think right now deleting a node removes it from any of the screens, but wanted to make sure this is what we want.
Yes it is. One node shown in multiple screens.

> Configurable in the protocol, is that right? Do we want to have a default, or to expect these to be defined?
I started to sketch this out in the new documentation: https://github.com/codaco/Network-Canvas/wiki/Name-Generator

Please refer also to the implementation in the 'flatter protocol' branch (just merged) which should say more. This might already have been implemented within that, come to think of it.

> There should be a blank space where the node was

I think in terms of the 'tactility' of this interaction, it makes more sense to have a blank space. Otherwise it makes a node seem like some sort of 'quantum object' that can be in two places at once until it is resolved.

**Comment by rebeccamadsen** [comment]
> Yes it is. One node shown in multiple screens.

Okay, so a user creates a node. And then on the next prompt drags the node from "already mentioned" over. Now it is on two prompts in the main area. Is it also on "already mentioned" panel for either of those two screens, or just for any other prompts?

And, what if they change their mind about the second prompt, but still want that node on the first prompt? They would need to delete it and return to the first prompt to recreate the node? 

> makes a node seem like some sort of 'quantum object'

Schroedinger's node! Yes! Although a blank space does not show if there is only one node, or it was at the end of the list... I assume this applies to a node whether it is being dragged from the main area or from a side panel.

**Comment by jthrilly** [comment]
> Okay, so a user creates a node. And then on the next prompt drags the node from "already mentioned" over. Now it is on two prompts in the main area. Is it also on "already mentioned" panel for either of those two screens, or just for any other prompts?

The main panel is for nodes that were created on that screen, _or_ dragged in from the already mentioned panel. 

In the scenario you describe, the node would _not_ be in the panel for the first prompt because it is in the main panel. It is in the main panel because it was created on that prompt. It would also _not_ be in the side panel on the second prompt, because it has been brought into the main panel, which is effectively the same as having been created on that screen.

Hope that clears it up.

> And, what if they change their mind about the second prompt, but still want that node on the first prompt? They would need to delete it and return to the first prompt to recreate the node?

I think this is a valid point that I hadn't considered. Deleting seems like the wrong way to go. The most obvious thing would be if you could drag it back into the side panel. Either that, or another 'bin' that perhaps just says "remove from list".

**Comment by jthrilly** [comment]
> Maybe if you delete a node from the main area that came from the "already mentioned" panel it ought to also "return" to that panel? In other words, it would not delete from any other prompts?

Nah, that breaks the concept of 'deletion'. If we drag a node to the bin, it is removed _from the interview_. That means it can only continue to exist if it is present in an external data source (as you correctly describe with the external data panel). 

I think here, we need to be able to drag from the main panel back into the people you already mentioned panel to remove them from it.

**Comment by rebeccamadsen** [comment]
That puts the cognitive load on the user to remember if they got a node from a side panel though? I guess highlighting the panel as a droppable area when they start dragging a node will help, especially if we can highlight it only when it could belong there. Is the external data panel also a droppable area then, or no because deleting the node makes it show up there?

**Comment by jthrilly** [comment]
The external data one isn't droppable for the reason you described.

And yes, you're spot on about the cognitive load - but that is precisely why we are implementing the drop zone highlighting. Perhaps part of this could even be that drop zones can have a text label inside them when they are highlighted. This would let us have the side panel dropzone update to say "drag to remove from main list" or something similar. 

Anyway, let's see how this evolves with implementation.

**Comment by rebeccamadsen** [comment]
> The color of nodes in the side panels should be a configurable property.

Is this separate from the strip of color at the bottom of the side panels, or related? There is a "highlight" option for panels, but that is just used for the bottom border color.

**Comment by jthrilly** [comment]
Yes, it is different. This is about the node colors, not the border. 

I wanted this option so that the user could define a node color for nodes shown in the external data panel, where it otherwise wouldn't have a 'type'. Nodes that have a 'type' also have a color associated with them in the variable registry, but because the data for the external panel is coming from elsewhere, it might not have a type attribute, and even if it did it might not correspond to a type defined in the variable registry.
