### ISSUE TITLE
can't delete/move nodes after adding nodes in mobile

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#250]
In cordova, after adding a new node, nodes can no longer be deleted. UPDATE_ACTIVE_ZONES has an empty `zones` array, even when directly over the trash can icon. Nodes can be deleted before you add anything, and if you add a node from the previous list box you can still delete nodes, it seems to just happen after creating a new node.

I think this is present in the mobile view in Chrome, but it is more...elusive...and might or might not be connected. If you add a node in regular view, and then toggle to a responsive/mobile view in developer tools, then you cannot delete nodes and also cannot add nodes from a previous visit. However, refreshing the browser eliminates the issue again, unless you toggle back to regular view and create a new node. Also, I think the position of the zones may just be off in Chrome, because I can delete nodes about 200-300 pixels to the right of the trash can. And I cannot add nodes from the previous visit either, unless I am almost on the edge of the screen.

The Chrome oddness alone I might just dismiss, because it only happens when I toggle between views. But in cordova I am not changing any views to get this behavior.

**Comment by rebeccamadsen** [comment]
I'm pretty sure I've narrowed this a little. Just having the keyboard open/close in cordova triggers several UPDATE_ZONE events (two for opening, two for closing the keyboard), and the x/y positions of the MAIN_NODE_LIST get off during this (in my case, the x is 602.35 and the y is -25.67).

In Chrome, it is just toggling back and forth between responsive view and regular view that also triggers several UPDATE_ZONE events, and ends up changing the x/y of MAIN_NODE_LIST.

It makes sense for zones to update, but I'm not clear why they don't revert back to the previous values.

**Comment by rebeccamadsen** [comment]
And if I drag a node to that position (35 x and 513 y), delete still works.

**Comment by wwqrd** [comment]
Hmm, I had a look into this too.

I tried a few things:
- ~~Changing the rate limiting on the update function from `throttle` (leading edge), to `debounce` (trailing edge). Hopefully we catch the last event.~~
- ~~Upping the rate limit.~~
- Looked into other iOS specific events, came across `orientationchange`, which appears to fix it in the iOS emulator. Please could you confirm this fixes it for you @rebeccamadsen?

I think it's worth keeping the `debounce` change anyway, but the rate limit should be set as low as possible.

The chrome debug issue I was aware of, but decided against looking into because: it isn't a use case; might be a quirk of emulation; we can work around it (by restarting the app in between simulated aspect ratios).

**Comment by jthrilly** [comment]
Works for me. 

Also, `orientationchange` should work on android.

**Comment by rebeccamadsen** [comment]
Hmm. Debounce and the higher rate limit do funny things to the mouse pointer on Android's input fields. Orientationchange is better on android than [resize events;](https://www.andreasnorman.com/dealing-androids-constant-browser-resizing/) the problems go away if I comment out the `window.addEventListener('resize', this.updateZone);` line. However, that means that resizing Chrome or electron windows won't correctly update the zones, right?

**Comment by jthrilly** [comment]
Just a note that I suggested to Steve that we wrap the call to the updateZone function on the resize event in a setTimeout of about 1s. A hack, yes. But we don't have a good idea of why this behavior is happening at the moment, and I don't want to invest too much time in digging into it right now.

**Comment by wwqrd** [comment]
A setTimeout version is in the `fix/zones-for-resize` branch and ready to merge. Seems to fix it for my Android sim.
