### ISSUE TITLE
layout of nodes in sociogram

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#255]
In the sociogram, opening the menu shifts the positions of the nodes relative to their edges and the background.

Menu closed:
![image](https://user-images.githubusercontent.com/16093053/32065043-9ce83e9a-ba49-11e7-8ddb-8ca796b1fbe0.png)

Menu open:
![image](https://user-images.githubusercontent.com/16093053/32064990-749d27ac-ba49-11e7-97af-18a71941d168.png)

**Comment by jthrilly** [comment]
Is this a new problem? I don't recall seeing it in the final release. I suspect it is a regression.

**Comment by rebeccamadsen** [comment]
I'm fairly sure it is new; we hammered the release enough that we should have seen this. But I am not sure where it was introduced since I don't usually add edges and toggle the menu.

**Comment by rebeccamadsen** [comment]
I narrowed it down to[ this commit](https://github.com/codaco/Network-Canvas/commit/bb7b6a851ef609967aff58cbddc944c1608da8aa) and commenting out [this line](https://github.com/codaco/Network-Canvas/blob/66061a76c1bbdbba487e8ba868e5e6f8332cb5e0/src/containers/Elements/NodeLayout.js#L32) "fixes" this particular bug. However, this line definitely is need for other things, like the nodes scattering when you change prompts in the sociogram and resizing the window, so this is not the solution. It looks like menu toggling changes the height, width, x and y, yet we don't really want to update the layout on a menu toggle?

**Comment by wwqrd** [comment]
Sorry about the terrible commit name.

This is part of a set of performance updates aim at reducing the number of redraws. This line was introduced to ensure the nodes are redrawn when the window is resized.

In theory we do want to change based on height/width/x/y changes, so maybe we could update the node rendering to work in a transformed component? (I think that would possibly be in `src/containers/LayoutNode.js`?)

It may be that the code that is used to calculate height/width/x/y, is outputting the wrong values for the transformed div. So some kind of relative/percentage based positioning should counter that.
