### ISSUE TITLE
Remove suffix "interface" from interface definitions

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#268]
Currently our interfaces are named things like `NameGeneratorInterface`, but are also located in the subfolder `interfaces`. I think we should have one or the other, but not both. 

My preference is to remove the suffix 'interface'. This could be done at the same time as the reorganization happening in #174.

**Comment by wwqrd** [comment]
`<SociogramInterface />` which contains a `<Sociogram />`, that sort of thing could get confusing? I think this is part of the reorganisation task? #174

**Comment by jthrilly** [comment]
Already linked the reorganization task, but I agree that it is part of that. 

In your example above, a more accurate naming would be a `<Sociogram />` contains a `<ConcentricCircles />` component. The sociogram is the entirety of the interface, not any one component of it.
