### ISSUE TITLE
Implement "Add Count" button

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#269]
Two of the roster interfaces need a submit button which reflects the number of items to add.

Mockup:

![addcountbutton](https://user-images.githubusercontent.com/39674/34160794-60ca0bb4-e49c-11e7-9cb0-87717600fcbe.png)

Requirements:

- Display dynamic count up to a reasonable limit (999?)
- Dynamic background color based on node type

**Comment by jthrilly** [comment]
I think 99 is fine for the limit. The software is really designed for networks up to 40 nodes.

**Comment by bryfox** [comment]
@jthrilly for node colors... I see [color definitions in the UI repo](https://github.com/codaco/Network-Canvas-UI/blob/master/src/styles/global/core/_color-dictionary.scss), but nothing specific to node types. In the style guide I see "Node Colors" but nothing too specific. Can you point me in the right direction please?

**Comment by rebeccamadsen** [comment]
Node colors aren't there by "type" in the ui, but in the palette, we have node-alt-1/node-alt-1--dark through node-alt-9.

**Comment by jthrilly** [comment]
At some point we need to think about a way to link those `node-alt-x` definitions up to human readable colors, but for now, the property in the variable registry (and by extension the value used by this button) should be updated to use the `node-alt-x` format.
