### ISSUE TITLE
Implement skip logic

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#276]
## Purpose
Skip flow logic allows the researcher to define a logical statement that is to be evaluated at interview time that determines if a given interview stage should be shown or skipped.

We devised a system for defining these logical statements (see the wiki). We need to implement their evaluation within Network Canvas.

**Comment by wwqrd** [comment]
The code to perform these queries already exists here: https://github.com/codaco/Architect/blob/master/src/utils/query.js and the protocol format is generated here: https://github.com/codaco/Architect/blob/master/src/components/Rules.js (needs documenting).

With both of these it should just be a case of integration with Network Canvas.
