### ISSUE TITLE
Name Generator: panels do not animate their collapsed/open state on safari and iOS

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#282]
As the title says, the side panels on the name generator do not animate their collapsed and open state on iOS or Safari. 

I haven't investigated, but it is hopefully just a CSS bug we can work around.

**Comment by wwqrd** [comment]
Looks like the flex properties aren't animatable on those browsers, maybe that'll get implemented one day, but in the meantime I'll try and find a work around. `max-height` seems to be a good candidate.

**Comment by jthrilly** [comment]
Relevant Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=180435
