### ISSUE TITLE
Name generator: staggered animations do not work correctly when switching between prompts

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#283]
Changing prompt on the name generator should trigger animation on all node lists where the contents have changed. This includes the main node list, and the side panels.

The animation is defined as: (replaced by mockup in next post)

~~All nodes in the container simultaneously animate out, with a scale(0) and opacity(0) of duration medium.~~

~~The changed nodes then animate in, in a staggered fashion, using the reverse animation but of duration fast.~~

Currently (speaking purely from a visual perspective), the main node list implements the "in" animation somewhat correctly, but with inconsistent time gaps between incoming nodes, and some visual glitches (nodes appearing instantly, or flashing in and then out). It does not seem to implement the out animation.

The side panels seem to show a brief "in" animation the first time they are shown, but do not animate after that. I can't be positive, but I believe the contents of the side panel are not updating correctly (will investigate this further and write up a separate bug if so).

On iOS this is particularly noticeable, and it might even be that some of the transitions are not functioning on iOS at all (we can test in safari).

If this is going to be fixed, we should take the opportunity to upgrade this animation to use animejs and the v2 api of react-transition group (as per issue #236).

**Comment by jthrilly** [comment]
Hi fidelity mockup of intended animation:

![panel animation](https://user-images.githubusercontent.com/1387940/34522316-f0b3910c-f089-11e7-8979-5cb68f1f43a3.gif)

**Comment by wwqrd** [comment]
Note: use easeOutElastic for easing.
