### ISSUE TITLE
Tap input lag on iOS

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#284]
We have somehow reintroduced a tap latency on iOS. This is noticeable when opening the menu, tapping buttons, and even when selecting nodes on the sociogram in order to create edges. The gap is consistent (around 300ms), which makes me think this is the classic 'fast click' issue resurfacing.

**Comment by wwqrd** [comment]
Looked into this but didn't get to the bottom of it.

- confirmed the issue in ios simulator
- checked `react-tap-event-plugin` was up-to-date and it was (3.0.2 which supports react 16)
- considered the possibility that `react-tap-event-plugin` and `react-fastclick` were conflicting, which inconclusive.

**Comment by jthrilly** [comment]
I'm taking a look.

**Comment by jthrilly** [comment]
I have narrowed this down to commit 90e76d56433e24f8bda19770a5fad19b58786255, which is where we introduced React 16. Really sad times.

I'll investigate further tomorrow.

**Comment by wwqrd** [comment]
Tried rolling back `16.2.0` to `16.0.0`, which didn't help either.

Interesting to note that it doesn't affect all components.
