### ISSUE TITLE
Drag and drop: delay in dropped node appearing

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#285]
There is a significant (1+ second) delay between a node being dropped and it appearing in its new location. This delay also appears when a node being dragged leaves a drop zone, but this time it affects the time it takes for the "ghost node" (placeholder node) to disappear. It would be great if we could reduce this or eliminate it entirely.

On a related note, the 'ghost' node always appears at the end of the node list, but the node list is sorted alphabetically by nickname (and I believe will soon have a sort parameter - @rebeccamadsen?). This means that once the node is dropped, it likely won't appear where the ghost node is positioned. There are several possible solutions to this, but I think the simplest is to remove the placeholder node entirely, and rely on the existing visual indicators of a valid drop target (which we can make more explicit if we need to).

**Comment by wwqrd** [comment]
This is a declared with `<StaggeredTransitionGroup />` in `<NodeList />` https://github.com/codaco/Network-Canvas/blob/master/src/components/Elements/NodeList.js#L42,L48

We could probably refine that to play more nicely with adding/removing nodes but I'd suggest we bundle this issue with https://github.com/codaco/Network-Canvas/issues/236
