### ISSUE TITLE
Nodes aren't rendered correctly on electron when screen width is greater than screen height

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#289]
## Correct rendering (Safari and Chrome desktop)
<img width="2560" alt="screen shot 2018-01-04 at 1 35 02 pm 3" src="https://user-images.githubusercontent.com/1387940/34566108-4d169ed2-f155-11e7-9269-35ce6600f223.png">

## Incorrect rendering (Electron desktop)
<img width="2560" alt="screen shot 2018-01-04 at 1 35 02 pm" src="https://user-images.githubusercontent.com/1387940/34566109-4d2e3772-f155-11e7-9bfe-a30804c8787a.png">

**Comment by rebeccamadsen** [comment]
Is there a specific screen resolution you see this on? I can't seem to duplicate this.

**Comment by jthrilly** [comment]
This was on my external displays. I will do more testing and try to pin down a reproducible case.

**Comment by jthrilly** [comment]
I'm not able to reproduce anymore. Could have been a one-off glitch, or could have been a bug in Electron since the version has been bumped since. I'll test again on my 5k displays, but closing for now.
