### ISSUE TITLE
modals are not opening from session menu

### ISSUE THREAD

**Issue by jamieshark** [codaco/Network-Canvas#297]
If you click on the "Check for Update" menu button, it is expected to trigger a modal to show up. Currently, the redux action `OPEN_MODAL` is firing, but the modal itself doesn't appear.

**Comment by jamieshark** [comment]
In my branch https://github.com/codaco/Network-Canvas/tree/server/server-discovery, i have a fix for this. The problem was that the modals were being included as children inside the Session menu, and `this.props.children` weren't currently being rendered in `components/Menu.js`.

**Comment by wwqrd** [comment]
Resolved in #324
