### ISSUE TITLE
`addOrUpdateNode` may no longer be needed

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#301]
In master branch, `src/ducks/modules/network.js` includes "add or update" functionality which doesn't appear to be used any more. Should it be removed, or is there a case for using it in the future?

**Comment by jthrilly** [comment]
How strange. I'm sure there was a purpose for it at some point, but I can't for the life of me think what it would be now. I think it is safe to remove now in a new branch, or in any in-progress branches.

**Comment by rebeccamadsen** [comment]
We used it briefly before the big refactor on drag/drop. I'm pretty sure we aren't currently using it.

**Comment by jthrilly** [comment]
Let's remove.
