### ISSUE TITLE
Incorrect state of Nodes on prompt change (edge cases)

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#305]
NodeList#componentWillReceiveProps() involves some nested state setting and timeout-driven animations. I'm opening this issue to better understand what's happening here.

- <strike>It appears that I need to specifically cache label strings on nodes, in the case where the displayed field differs between prompts, but that shouldn't be necessary.</strike> Update: This separate issue was moved to #311.
- It appears that double-clicking the prompt can produce an incorrect state, where a node appears both in 'already mentioned' and 'nodesForPrompt'

Here's one way to reproduce the latter:

1. Reset Session
2. Load demo protocol
3. On Name generator...
4. Prompt0: Drag one or more nodes to the main list
5. Click prompt swiper to advance to Prompt1
6. Click prompt swiper to advance to Prompt2
7. Double-click prompt swiper to advance through Prompt0 to Prompt1

**Comment by bryfox** [comment]
#### 1. setState called within timeouts may result in incorrect state.

The NodeList is shared between prompts. To make animations work, rendering is driven from component state rather than directly from prompts. Timeouts are used to clear and then show nodes. If a user's second click is faster than the timeout, then the (previous) state will overwrite the 'new' state. If the 'new' state doesn't also trigger a timeout, then the displayed state will be inconsistent until further user action.

Solution: remove timeouts; adjust transition code to make animations continue working as expected.

#### 2. "undefined" labels during transition

NodeList state is updated aynchronously from props. The display label formatter/callback is formatting a node from an 'old' prompt (see above). The formatter could theoretically use the promptId to look up the correct `displayLabel` for the node it's formatting, but (at least presently) it would need to check 

Solution: ideally, NodeList's rendering will be driven from props, so that everything is driven from React props as expected. I'm working on getting transitions to work correctly here.

#### 3. potential for "undefined" labels

Given that currently:

- a prompt's nodes (`networkNodesForPrompt`) are driven from the prompt's `additionalAttributes` in the protocol definition,
- a protocol `dataSource` is associated with a prompt, not a stage (a network can consist of different node types), and
- no business logic prevents a protocol from re-using `additionalAttributes` between prompts

...a prompt's displayLabel property may refer to a field that doesn't exist on one or more nodes.

<img width="622" alt="undefined" src="https://user-images.githubusercontent.com/39674/35745990-4061d560-0813-11e8-9931-9f7bd823b52f.png">

**Comment by bryfox** [comment]
I've renamed this issue to better describe the problem, and I'll be PRing changes to address numbers 1 and 2 from the previous comment. @jthrilly If you feel there's a need to address the third case (perhaps even just documentation), then I can open a new issue.

**Comment by jthrilly** [comment]
Can you do a new issue Bryan? I think we will want to resolve it one way or another. 

I'm thinking we implement logic for when a specified label is undefined such as the following: (1) attempt to look up the label for the node type as defined in the variable registry, and failing that (2) use the first property, or failing that (3) use the node id.

**Comment by bryfox** [comment]
I opened #311 to cover that.

**Comment by jthrilly** [comment]
Needs testing since #443 has been merged.

**Comment by bryfox** [comment]
"setState called within timeouts may result in incorrect state" is still an issue & reproducible with the steps in the description.

**Comment by jthrilly** [comment]
@bryfox is the unknown label issue resolved at least?

**Comment by bryfox** [comment]
I'm reviewing and will re-open #311 if it's still an issue.

**Comment by jthrilly** [comment]
It seems that the undefined label element of this has been resolved. 

I propose we fix the other aspect of this by preventing another prompt change until the first prompt has finished transitioning. The timing is so short that I don't think this will be a big nuisance to the user. 

Any other potential fixes?

**Comment by bryfox** [comment]
Yes, see https://github.com/codaco/Network-Canvas/pull/313#issuecomment-363499525
