### ISSUE TITLE
Use CSS variables wherever possible to allow easy customization of the app

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#309]
At present we define many variables for re-use throughout the app, using SASS, JavaScript - or both at the same time. Examples of this include our colors, our animation parameters, and some component sizes. This has a few effects:

- We require a build system to synchronize shared SASS and JavaScript variable values. 
- Once compiled, SASS mixins such as used by our palette and color system are harder to override. End users will need to write a lot of custom CSS, or else use the UI repo as a dependency for their own custom SASS based stylesheet.

Instead, I propose that we move to using CSS variables wherever possible. These can be set and read within javascript, and can be overridden with a simple custom stylesheet targeting only the CSS variables.

### Implementation details
- Global (project wide) variables will be implemented in the `:root` element, allowing for easy overriding.
- Components may create and use internally scoped variables by defining them within the block scope definition for that component (using our BEM system). I've done this for the spinner component to create size variations, so take a look for an example of why you might want to do this.
- We should modify continue to modify variable values based on media queries, such as breakpoints. For example, our `--node-base-size` is initially set at 200px, but changes to 160px for smaller screens.
- Colors: we should continue to use static SASS variables to define our network canvas named colors (although these too can be come CSS variables if we wish). Examples of these named colors are "network-canvas-coral", "mustard", "cyber-grape", and so on. However, the palette definitions (which provide a mapping of a color to a specific use within the app - such as "primary node color") will be transitioned to global CSS variables, and set to our existing color definitions as a default.
- Animation parameters (duration and easing) will be moved to global CSS variables. We can use `calc()` within our CSS to create derivative properties, such as `--animation-duration-slow: calc(var(--animation-duration-standard) * 0.66)`.

### Implementation tasks
- [x] Update color system in Network-Canvas-UI, including removing existing build/compilation system.
- [x] Update Network Canvas-UI components, and Network-Canvas components to use new color system.
- [x] Update animation definitions to use CSS variables, including removing the duplication present in the Javascript side.
- [x] Update animation implementation in UI and NC to use new CSS variables. There will be more work on the React side with this, since our react transition group stuff uses animation values directly.

**Comment by jamieshark** [comment]
Okay, so the plan is to replace the mapping that we have now in `_color-dictionary.scss` with variables e.g. @include color-set('neon-coral', #e2215b) will become $neon-coral: #e2215b. And instances of the `color()` and `palette()` function will be replaced with the values of the variables themselves? or are we still keeping the `palette()` mappings?

**Comment by jthrilly** [comment]
Basically, yes. We could keep _our_ colors as SASS variables to minimize clutter in the :root selector. The main thing is to move the palette functionality (which maps colors to uses) to CSS variables.

Ideally there should be few/no direct uses of `color()` within network canvas. Where you find them, these should be replaced by palette references (create a new palette entry with an appropriate name, if needs be).

**Comment by jamieshark** [comment]
so we might have something like
Network-Canvas-UI
```
:root {
  --node-base: #e2215b;
}
```
Network-Canvas (or other app)
```
$neon-coral: #e2215b;
:root {
  --node-base: $neon-coral;
}
```
?

**Comment by jthrilly** [comment]
The UI repo has our default colors in it, defined in sass and then used to set the initial value of the CSS variables representing the palettes. 

The user stylesheet will just contain a list of overrides of those `:root` css variables.

**Comment by jamieshark** [comment]
In the UI repo, colors and palette values are being set as global CSS variables. 

In Network Canvas, values that were using SCSS functions like `transparentize` or `darken` have been given their own global variable value.

All other instances of the `color` and `palette` function compile down to using the css global variable.
