### ISSUE TITLE
iOS asset loading issues

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#327]
In the demo protocol, the new instruction interface should display an image and have an audio playback feature.

On an iPad running iOS 11, the audio player displays "Error" and cannot play.

![device](https://user-images.githubusercontent.com/39674/35981974-9a84feca-0cbc-11e8-9483-227ad446dfbd.jpeg)

Additionally, on the latest simulator, images don't show on either the instructions or sociogram.

![simulator](https://user-images.githubusercontent.com/39674/35982035-c8434678-0cbc-11e8-8648-c374be04ff01.png)

Tested: master branch @ 13cbb3a after re-running `npm run dist:ios`.

**Comment by rebeccamadsen** [comment]
I see something similar running android in the simulator. Loaded demo in android, on instruction interface image/audio are not loaded. Also on sociogram, the duck image is not loading, and on console I see this error:
```Failed to load resource: net::ERR_FILE_NOT_FOUND
Uncaught (in promise) FileErrorcode: 1__proto__: Object
index.html#/protocol:1 
```
It looks great in Chrome and Electron, which means I can't find a better error message, sadly.

**Comment by wwqrd** [comment]
Audio not working on an actual device either.

**Comment by wwqrd** [comment]
Factory protocols are loading assets from the imported protocol location. So only assets that are present (say from an older import) are available. Looking into a fix.
