### ISSUE TITLE
setState warning message

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#328]
On Chrome, I see this warning message whenever I leave the sociogram stage:

```
proxyConsole.js:56 Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.
```

It doesn't seem to affect anything...

**Comment by bryfox** [comment]
This is worth fixing now; I'll take it. The animationFrames aren't being cancelled, so we end up having N sets of `trackSize()` running continuously (N == number of times you navigate to the sociogram).
