### ISSUE TITLE
search field covered up by keyboard

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#332]
On Android simulator, I noticed that the search field in the autocomplete roster is completely covered up by the soft keyboard. I can't see what I'm typing in the field at all without closing the keyboard, which defeats the purpose. Obviously this is not an issue in Electron or Chrome.

This is not a bug, as this was the design of this feature from initial concept. If I only want to type a character or maybe even two, this may not be a problem. But longer words are prone to mistake without the visual feedback of what I've already typed.

**Comment by bryfox** [comment]
Thanks, I'll take a look. I would expect the UI to shift/scroll as on iOS; it sounds unusable as-is.

**Comment by bryfox** [comment]
Looks like our `<preference name="Fullscreen" value="true" />` config disables the auto-scrolling feature (c.f. [stackoverflow](https://stackoverflow.com/questions/23934689/phonegap-android-keyboard-covers-input-elements-scrolling-is-disabled)).

With fullscreen set to false, the status bar is displayed, but inputs behave as I would expect without further changes. 

![fullscreen-false](https://user-images.githubusercontent.com/39674/35986587-6e6f459c-0cc7-11e8-9241-3b5aaba4c6d7.png)

Other solutions suggested above include a [plugin](https://github.com/ionic-team/cordova-plugin-ionic-keyboard) which fires additional dom events, manually scrolling the interface in response to focus inputs.

I'm going to argue for fullscreen=false. With fullscreen=true, we have other problems to solve:

Once the keyboard is shown, then the status bar & navigation bar appear anyway, and remain. (At least that's what I see in an 8.0 tablet emulator.)

Those bars seem to cover the content view, so once that happens, layouts with items pushed to the edge are obscured. (Example... left: fullscreen=true, right: fullscreen=false).

![fullscreen-and-not](https://user-images.githubusercontent.com/39674/35987544-fc89ea2e-0cc9-11e8-8757-e5df3c002cc4.png)

Other fields like the protocol import may have the same issue depending on screen resolution, installed, keyboard, and keyboard settings, e.g.:

![keyboard-setting](https://user-images.githubusercontent.com/39674/35987692-6c41378c-0cca-11e8-8a69-fb426299dc57.png)

That said, maybe there's an argument for 'fullscreen' I'm not aware of. Thoughts?

**Comment by jthrilly** [comment]
The argument for fullscreen was purely that the bars at the top and bottom were ugly. This is clearly more important, so I'm happy to go with disabling it.

One question: on iOS we are able to have a transparent titlebar, which helps with this. The latest iOS also has a self-hiding dock. Is it possible to have a self-hiding navigation (bottom) panel, and/or a transparent notification bar? This would make having fullscreen disabled a lot less painful.

**Comment by wwqrd** [comment]
Am I right in thinking allowing rotation is off limits? This could also solve the problem!

**Comment by bryfox** [comment]
Looks like using any of the translucent flags disables the auto-focus/scroll. However, if we bump our min SDK version to 21 (which I think is fine), we can set arbitrary colors on both bars.

I think self-hiding bars could be accomplished by writing a plugin. Right now cordova applies the 'fullscreen' settings when window focus changes (and so the bars don't disappear on blur). Theoretically we could hide on blur events. I'm not sure how that would work with external keyboards. Might be worth investigating in the future.

![grapebars](https://user-images.githubusercontent.com/39674/36031017-6076411a-0d77-11e8-95d3-e5ace10e01da.png)

![grapebars-scroll](https://user-images.githubusercontent.com/39674/36031019-659c6b9c-0d77-11e8-8e46-5aec7938d804.png)

**Comment by bryfox** [comment]
Additionally, the nav bar can be 'dimmed' (here also with the custom color) to make the buttons less apparent:

![dimmed](https://user-images.githubusercontent.com/39674/36031160-cac94ea4-0d77-11e8-830e-796080f1ce5d.png)

As with the hiding, to get this to re-dim after the keyboard leaves would require a plugin.

**Comment by jthrilly** [comment]
Okay, I'm happy with the color bars option if everyone else is. Dimmed buttons are cool, but if we need a plugin to keep them dimmed I don't think we should bother. 

Min SDK 21 is totally fine. Our min SDK should really track the latest release actually (so 26). 

Did you try it with our actual background color and decide it didn't work? That would be my preference.

**Comment by bryfox** [comment]
Now that I look again, I might suggest using actual BG color for the top status bar, and black for the bottom nav.

Rationale: we want the status bar to be ignored; we want the nav buttons to look like part of the phone chrome and not part of the app. (Especially without/until back button integration.)

**Comment by jthrilly** [comment]
Sounds good!
