### ISSUE TITLE
Protocol load error displays could be improved

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#333]
When a protocol fails to load (or process to completion), the error message presented in the GUI may be unhelpful (e.g., `[Object object]`). The basic test case is to enter a custom URL and tap load protocol.

Note, I see a reasonable error message on electron for 404s, although the displayed URL ("stuk.github.io/jszip/documentation/howto/read_zip.html") looks like developer documentation...

I wonder if having our own generic error message for all of these cases is preferable (or perhaps one for network/server and one for processing).

## [Electron] When URL is a directory

![electron-folder](https://user-images.githubusercontent.com/39674/35983045-381b8238-0cbf-11e8-9dc2-f678d153c438.png)

## [iOS] URL that 404s

![ios-404](https://user-images.githubusercontent.com/39674/35983496-2320f1c8-0cc0-11e8-88af-22cf263617f9.png)

(Any 404 should do, but URL tested was the default, minus the final "s".)

## [Electron] SSL trust error

This may not be an issue in practice, but can be reproduced by importing from a server using a self-signed cert (e.g., the dev server in https mode). In this case, no error is presented. There's an uncaught error in the console and the app spinner displays indefinitely until the app is reloaded.

**Comment by jthrilly** [comment]
The `<Dialog />` component has `additionalInformation`, which adds this to a textarea. This could be enhanced to be scrollable, and to allow easy copy and paste for bug reporting. 

Could take place as part of #321

**Comment by wwqrd** [comment]
This part of the app is all handled with promises, with a catch all for errors.

We could either expand this catching functionality to better interpret the errors coming in.

Default to a plain text message for now "Sorry for the inconvenience etc.

The *actual* error is still logged to the regular console.

**Comment by jthrilly** [comment]
I would be in favor of expanding the catching to interpret the platform specific errors better. I also think we should keep debug info in there for errors that are unexpected. Combining the two would mean basically "parsing" the error format specific to each platform, and putting it in a format that can be displayed in the `additionalInformation` box (which is the pattern I want to use for extra debug information - @wwqrd  is going to be creating an issue on improving this design later today).

To go along with that, we should have a series of human readable text responses for the most common errors. For example:

- 404 - "We couldn't find a Network Canvas protocol at the location you gave us. Check the location, and try again."
- Invalid path/URL - "The location you gave us doesn't seem to be valid. Check the location, and try again."
- No network connection/network errors? "Your device doesn't have an active internet connection, so we weren't able to fetch your protocol at this time. Connect to a network, and try again."

etc.
