### ISSUE TITLE
[iOS] protocol import field does not always display keyboard

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#334]
iPad/iOS 11. No hardware keyboard.

When I tap the protocol import text field to focus, the keyboard shows but the view doesn't always scroll up as expected (so that the input field would be visible). User has to dismiss keyboard and re-tap the field.

This happens maybe 1/3-2/3 of the time.

May be an issue deeper in the stack, but I only see it on this field, and cannot reproduce elsewhere (e.g., on the filter input for Roster list).

![field-focus](https://user-images.githubusercontent.com/39674/35984806-2ff45a0e-0cc3-11e8-955c-66512ec8399d.jpeg)

(edit: removed incorrect statement about logs.)

**Comment by bryfox** [comment]
This appears to be related react "controlled component" inputs, but possibly only within a redux form? 

- Replacing the field with a plain input (same styling) does not have the issue
- Replacing the ReduxFormField on that screen with a standalone controlled component input still has the issue
- The controlled component input on the RosterList does not have the issue.

**Comment by jthrilly** [comment]
Keep sharing anything you find Bryan. I have a feeling this issue will crop up elsewhere.

**Comment by bryfox** [comment]
This is not an issue with UIWebView, nor localhost running in mobile safari; only WKWebView.

[This cordova issue](https://issues.apache.org/jira/browse/CB-12037?jql=project%20%3D%20CB%20AND%20labels%20%3D%20wkwebview-known-issues%20AND%20text%20~%20%22input%22) about [a removed pref](https://developer.apple.com/documentation/uikit/uiwebview/1617967-keyboarddisplayrequiresuseractio) seemed related, but I tried the stated workaround [as implemented by ionic](https://github.com/ionic-team/cordova-plugin-ionic-webview) and could still reproduce the problem — even though that webview allows me to set focus programatically/arbitrarily.

So I still really don't know what's happening. If there's a timing issue involved, it doesn't seem to be because of iOS preventing artificial focus.

**Comment by bryfox** [comment]
It's not timing; it's position. Depends a bit on the device/sim used (as layout can vary slightly), but tapping around the top of (or just above) the field causes the issue in the screenshot; tapping the bottom area does not.

Removing `display: flex;` from the app__content makes things display as expected; otherwise, changing height-affecting display properties on various elements on the screen can worsen or improve the situation. I guess the flex layout calculations confuse whatever logic is in the webview to scroll the viewport when a field takes focus.

I think I can probably fix the height of `setup` or something to fix this field, but in terms of a general solution (so this issue doesn't crop up elsewhere), we may need to look at the overall app layout.

**Comment by jthrilly** [comment]
So there are actually two issues in play? This is what I am getting from what you've written:

- `keyboardDisplayRequiresUserAction` isn't in WKWebView: the ionic webview implements the `keyboardDisplayRequiresUserAction` "hack" that fudges this.
- When using that webview you _also_ need to remove the flex styling in order to actually fix the issue.

So does removing `display: flex` achieve nothing in the default WkWebView? Or was the missing property a red-herring?

One of our longer standing discussions has been about changing the top-level app layout (menu system -> interface containers -> interface 'blocks') to use `display: grid`, and reserve `flex` for within component positioning, which seems to be the industry consensus. Since the issue here is with `.app__content`, which is one of the top-level containers, so that wouldn't help, but can you just confirm?

For this release I think we should fix the height by whatever means, and create an issue to followup with this when we have more time to investigate potential solutions. Let's get something out of the door and move on to other small fixes.

**Comment by bryfox** [comment]
Sorry, no... only the layout/height is an issue. I'll work on a short-term fix for this release; it'll be css-only.

iOS preventing field focus (`keyboardDisplayRequiresUserAction`) was the wrong tree I spent too long barking up. (I thought this had something to do with setting state & controlled components.) The swizzled WKWebview (as in the iconic plugin) is a hack to support programmatically focusing fields, but has no effect here.

**Comment by jthrilly** [comment]
That's fine. Let's carry on with the fix as above, then.

**Comment by bryfox** [comment]
`display: flex` was also a red herring; removing it changed the layout enough that it didn't trigger the issue when I tested.

This is an iOS issue. AFAICT now, the scroll calculation is simply driven by the touch coords that brought focus to the input. If the touch is above keyboard height, no scrolling happens. And since the touch area is a little larger than the input, you can have the input hidden completely. We got unlucky.

Reduced case for a 12.9" iPad in mobile safari:

```
<!DOCTYPE html>
<div style="height: 335px"></div>
<input type="text">
```

![sim-12 9](https://user-images.githubusercontent.com/39674/36155617-d9eea270-10a2-11e8-9869-608d6d03e51b.png)

I don't see a possible fix. The best I can do is to tweak styling so that this doesn't affect the home screen with today's iPads using standard keyboards, which is probably valuable only for short-term evaluation. I'm not seeing the issue now on master with my iPad [Air 2], which is what the original screenshot was from, so the 'worst' case seems to be the 10.5", which is still visible.

![10 5](https://user-images.githubusercontent.com/39674/36156897-78bc3478-10a6-11e8-9d8a-abaa240733c3.png)

I'm inclined to close this & file a radar unless you think otherwise.

**Comment by jthrilly** [comment]
Let's go with that, then. What a shame. Hopefully Apple pays more attention to your RADAR than they have to mine in the past.

Great investigation though!
