### ISSUE TITLE
Special characters are accepted as valid names / nicknames

### ISSUE THREAD

**Issue by jamieshark** [codaco/Network-Canvas#336]
<img width="265" alt="screenshot 2018-02-08 10 45 03" src="https://user-images.githubusercontent.com/5520141/35985830-23554fca-0cbd-11e8-9296-95c95c40419d.png">

Maybe not a bug, but could be something to consider to sanitize / validate these.

**Comment by jthrilly** [comment]
I think this is 'by design', since it doesn't break any validation rules, and the user is free to create those to their specification. As long as special chars don't cause bugs/break editing nodes, etc. I think we are ok.

What do others think?

**Comment by rebeccamadsen** [comment]
I don't think that is a problem here since it isn't being evaluated? The user can download their data to a file; is there a security issue then?

**Comment by bryfox** [comment]
Escaping seems to work correctly for data export, at least for this simple test: `<data key="name">&lt;/graphml&gt;</data>` (tested iOS & mac)

**Comment by jthrilly** [comment]
Yep, I'm happy to leave this as-is.
