### ISSUE TITLE
Name generator doesn't use default form for node type

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#353]
If no `form` property is specified in the NameGenerator configuration object, the interface does not follow the expected logic, and the app crashes.

Expected logic is as follows:

- Use the `form` property to look up a form in the protocol file, and use it.
- If no form property is found, use the node type specified in the `subject.type` property, and try to use a form with that name (the "default node form" for that node type - this should always be present and will be created by Architect).
- (optional) if that fails, use error boundaries to manage an exception, and give the user an error message they can send us to help with debugging.

**Comment by bryfox** [comment]
- [x] fall back to `subject.type`
- [ ] Surface error message
- [ ] Update docs?

I've pushed the `subject.type` fallback to the `fix/node-form` branch.

I haven't done error handling yet. We know enough in this case to present a message/solution to the architect without sending us debugging info. (Though really, this should happen in the Architect before the protocol was exported?) Having a boundary makes sense for uncaught exceptions; it looks like that would be almost top-level in this case; it may be better served as a separate PR.

The code I removed seemed to [follow what was documented](https://github.com/codaco/Network-Canvas/wiki/Name-Generator#interface-specific-api): looking for a `creates` property. Should I update the docs too?

**Comment by jthrilly** [comment]
I think the docs describe the intended behaviour, which was implemented incorrectly. Therefore there's no need to update them. Or have I missed something?

**Comment by bryfox** [comment]
Docs: 

> Network Canvas will try to locate a form with the same name as the node type specified in `creates`.

If I'm reading the issue description correctly, then we now try to locate a form with the same name as the node type specified in the `subject.type` property.

Should docs by updated to replace `creates` with `subject.type`?

**Comment by jthrilly** [comment]
Yes! Sorry, I forgot that we also renamed `creates` to `subject`. Please do update the docs accordingly.

**Comment by bryfox** [comment]
Docs updated. [Diff.](https://github.com/codaco/Network-Canvas/wiki/Name-Generator/_compare/69d9d491749cb5dfdb8a16f344da5127c193dd35...34e9e1940fd543d7f48ff21f2b87daeab3edc40c)

**Comment by bryfox** [comment]
#370 was merged. I opened #373 to cover the messaging part of this.
