### ISSUE TITLE
Prompt content should support emphasis, and bold weight

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#354]
Prompt content should support the rendering of _emphased_ and **bold** text so that researchers can adjust the visual emphasis of their question prompts.

**Comment by rebeccamadsen** [comment]
With markup or html tags or something else?

**Comment by jthrilly** [comment]
Good question! There is an interesting looking `<Markdown />` component I was looking at the other day that might be a good fit. That might be a cool way of adding this functionality without having to (1) build a GUI in Architect for formatting, and (2) having to sanitize user input. The cost would be rendering HTML from markup each time a prompt is rendered.

**Comment by jthrilly** [comment]
Considering we are implementing markdown in the information interface (and will get a dependency from this), I think Markdown is the way to go here. Should be as simple as adding the correct component to the prompt component.
