### ISSUE TITLE
Download protocol timeout

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#356]
What should we do when a download hangs or is extremely slow? Currently a user would be stuck on the loading screen.

Two enhancements we could make are:
- Include a timeout based on the size of the file
- Include a 'cancel' button on the loading screen

**Comment by wwqrd** [comment]
```javascript
const withTimeout = secondsToComplete =>
  (action) => {
    const timeout = new Promise((resolve, reject) => {
      setTimeout(() => reject(timeoutError(new Error())), secondsToComplete * 1000);
    });

    return (...args) =>
      Promise.race([
        action(args),
        timeout,
      ]);
  };

// Usage:

const myMethod = () => Promise.resolve();
const myMethodWithTimeout = withTimeout(10)(myMethod); // wait 10 seconds max for myMethod to complete.

myMethodWithTimeout
.then(() => {
  // success
})
.catch((error) => {
  // timeout or original method failed
});
```

**Comment by bryfox** [comment]
Download is a one-time cost. I imagine some users would accept long latency if they're "pre-downloading" the protocol ahead of any sessions and happen to be on a connection we might consider slow. I think I'd vote for cancellation over timeout for that reason.

See also the discussion in #684 (about the import step, which is behind the same loading screen). Stateful feedback (progress bar + messaging like "downloading...", "importing asset1"...) could also be useful.

**Comment by rebeccamadsen** [comment]
Related to #727.

**Comment by jthrilly** [comment]
This needs reimplementing following changes.
