### ISSUE TITLE
nodeBinSortOrder should be an optional parameter with a sane default

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#357]
Currently the Sociogram interface fails if no `nodeBinSortOrder` parameter is provided. 

Instead, the interface should use the `subject.type` and `subject.entity` configuration properties to look up the `labelProperty` for the given node type in the variable registry, and sort using that parameter by default.

**Comment by rebeccamadsen** [comment]
We mean `displayVariable` in the registry, I think?
