### ISSUE TITLE
Node form doesn't open with consecutive Namegenerators

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#360]
If you place two Name Generator interfaces next to each other in an interview, the new node form does not open on the second of the two. Navigating directly to the second interface on a fresh load allows the modal to open as normal.

This seems to be to do with the modal unregistering after the second interface has loaded (just based on looking at the console activity).

**Comment by rebeccamadsen** [comment]
The modal is registering in the ComponentWillMount method in src/behaviours/modal.js and unregistering in ComponentWillUnmount. Unfortunately, these seem to be happening [asynchronously](https://stackoverflow.com/a/47563198) from each other now, and each NameGenerator uses the same symbol to refer to the modals, so the first NameGenerator unregisters the modal after the second one registers it. Bumping the registration to ComponentDidMount didn't seem to help.

We could use a unique id for the form names as a workaround. Perhaps "EDIT_NODE" plus the stage id? That seems to solve it in my initial testing, if we are happy with that.

**Comment by jthrilly** [comment]
I think that's a great workaround, since stages shouldn't be using the same symbols as each other anyway. Could you implement this @rebeccamadsen?
