### ISSUE TITLE
Use relative font sizing (rem units)

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#361]
At present we have a mixture of hard coded and relative font-sizing throughout the NC and UI styles. We should standardize on relative units, and use a CSS variable (see #309) to set the base app font size.

**Comment by jthrilly** [comment]
Could be done along with other CSS changes in #309

**Comment by rebeccamadsen** [comment]
Is the scope here just fonts, or are we trying to move all "em" and "px" values to "rem" everywhere?

**Comment by jthrilly** [comment]
Great question!

I like the idea of all of our units being based off of either viewport units or relative to the root font-size variable wherever possible. Certainly things like margin and padding of containers should adapt to this to make sure we don't have ugly font rendering.

At a minimum I think we need a corresponding PR in NC to also implement this.
