### ISSUE TITLE
nested optional properties need to be optional

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#364]
As mentioned in #359:

- `content` is specified as optional for information interface, but `items` is actually required (at least an empty array)
- `sortOptions` is optional for `NameGeneratorList`, but errors out if you leave it off (needs an empty object).
- `searchOptions` is optional for `NameGeneratorAutoComplete`, but errors if you leave it off (needs an empty object)

**Comment by jamieshark** [comment]
https://github.com/codaco/Network-Canvas/pull/424
