### ISSUE TITLE
Node occlusion on the sociogram screen 

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#371]
The layout screen currently permits one to place a node anywhere on the canvas. However, some UI elements are floating on top. This means that when you drop a node over the panel in the lower left hand corner it will stay there and can no longer be clicked or retrieved without "resetting" all of the node places. 

Some options: 
1. The panel in the lower left can itself be dragged around. 
2. There's a hit window such that if the node is dropped within that window it goes back to the original coordinates from which it arrived. 
3. It's laid on top of the dialog window. 

I believe Josh was promoting the second behaviour. He asked me to submit this as a bug. 

![screenshot 2018-02-14 17 59 49](https://user-images.githubusercontent.com/1711620/36219952-f2a61dde-11b0-11e8-81f3-adf308461ae1.png)

**Comment by pfsj** [comment]
The area where Nodes originate from in the top right corner should also probably be ineligible for dropping nodes until there are no remaining nodes to be added. They currently get placed behind the remaining nodes and cannot be selected until all nodes are removed which seems awkward. 

<img width="1440" alt="screen shot 2018-02-22 at 2 37 04 pm" src="https://user-images.githubusercontent.com/10948594/36562854-e01bb024-17dd-11e8-854c-a1f5071dd2cd.png">

**Comment by rebeccamadsen** [comment]
Knowing that the collapsing instructions issue was also proposed, is this the preferred solution? That the prompt window and the node bin are hit zones that can't be dropped on? Is the reset button also a hit zone, or is it too small to be of concern?

**Comment by jthrilly** [comment]
I think collapsing instructions are also desired, but node occlusion does need to be looked at as well. However, given that we haven't specified this very well I am going to bump the feature to the next release.

**Comment by wwqrd** [comment]
Relates to: https://github.com/codaco/Network-Canvas/issues/469

**Comment by wwqrd** [comment]
Just some technical background first: drop areas are defined as x, y, width, height, and have no concept of occlusion.

I think probably the best way to handle this would be to add the concept of *Obstacles*, this could be added to components we want to block movement.

Before any move or drag events are fired, we could check if they fall within any of these regions, if so they won't set off the drop region events.

**Comment by rebeccamadsen** [comment]
Related ideas from #614:

> We could also connect this up to MonitorDragSource and auto hide [the instruction panel and origin bucket]

> It's almost like we need a "show desktop" button or a "placement mode".

**Comment by bryfox** [comment]
From https://github.com/codaco/Network-Canvas/pull/660#issuecomment-420601384, the ideal behavior is: 

- Nodes hovering over an exclusion zone should enter an invalid state
- If dropped on an exclusion zone, they should animate back to their last valid position
