### ISSUE TITLE
Reset interface removes edges as well as resets XY coordinates

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#372]
Is it an expected behaviour that "Reset Interface" also removes the edges? 

I've had to reset the user interface because of the node occlusion issue that I mentioned in issue #371 But I did not expect that it would eliminate the edges. In this sense it is an interaction bug. I can see the reasons why one would want to remove the edges, but I can also see reasons why one would want to keep the edges. When in doubt, I err on the side of whatever would frustrate the user the least. 

Note, I'm working off an older version (4.0.0 alpha) . This bug might no longer be the case.

**Comment by jthrilly** [comment]
The intention behind the button was to reset _everything_ on this interface, not just the layout. Unless you think that it would be more useful to keep edges?

There's a bug in alpha-2 that means this button now _only_ deletes coords and edges, but leaves other properties intact.

**Comment by berniehogan** [comment]
Hmmm...I would have thought that "interface" should be considered separate from "data". Otherwise, we don't really have a meaningful boundary for what gets reset. This is especially the case on many of our screens where edges / node selects etc... are on different screens / stages than the initial node layout. This means that a person might have to enter considerable data again. 

I realise that this could lead to some weird interface issues if the edges are drawn on the node layout screen and thus the edges start to appear when the nodes are being laid out. But that's an edge case as we almost always separate out the node layout task and the edge generation task sequentially.

**Comment by jthrilly** [comment]
Ah, I see! I think we were assuming that there wouldn't be an exposed user interface element in the final version for resetting this interface (and the button we have now is just for testing/debugging). Are you saying that you think there should be? Do you have a proposal for how it would work?

I think from what you've said you're saying that a 'reset' option more generally should be specific to the prompt you are on within an interface. I think that makes sense.

**Comment by rebeccamadsen** [comment]
So right now the reset only applies to the Sociogram interface. I just want to clarify my understanding. So is the "reset" proposed to act like an "undo" in that it returns the state to how it was when the prompt was navigated to (meaning the program needs to remember how things were on prompt load), or that any possible action (positioning, edges, highlights) available to that prompt are returned to initial state generally? e.g. if positioning can be set on a given prompt, but the user did not move any nodes, does a reset still move nodes back to the node sorting bin?

**Comment by jthrilly** [comment]
I think ultimately the ability to reset the values set on the current sociogram prompt will be some sort of hidden advanced option, and not a public user interface element. 

For the time being, it would be good if the reset button could implement this. It needs to look at the configuration for the current prompt, and remove any values set. These include `edges.create`, `layout.layoutVariable`, and `highlight.variable` (if `highlight.allowHighlighting` is true).
