### ISSUE TITLE
"isNumericOnly" warning

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#375]
With the teaching protocol, the first time you open the edit node or add node form in Chrome we get a console warning:
```
Warning: React does not recognize the `isNumericOnly` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isnumericonly` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by ToggleInput)
```
Most likely this is coming from one of the fields we are using in the teaching protocol that we haven't used elsewhere.

**Comment by jamieshark** [comment]
I think this might be coming from the UI TextInput component. I'll investigate!
