### ISSUE TITLE
"playsinline" warning

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#377]
On Chrome, the teaching protocol "Drawing Ties" screen gives this warning:
```
proxyConsole.js:56 Warning: Invalid DOM property `playsinline`. Did you mean `playsInline`?
    in video (at Video.js:7)
    in Video (created by mapProps(Video))
    in mapProps(Video) (created by lifecycle(mapProps(Video)))
```
I don't see this on Electron or Android.

**Comment by wwqrd** [comment]
I was mistaken, looks like React 16 simply passes though unknown props, so technically this is working as it should.
