### ISSUE TITLE
Android emulator videos

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#379]
On Android emulator, the videos do not play. See the "Drawing Ties" screen in the teaching protocol for an example. Fortunately it plays on devices, so this is not urgent, and possibly something not to fix at all.
```
Refused to load the image 'android-webview-video-poster:default_video_poster/-141442556822233072' because it violates the following Content Security Policy directive: "img-src asset: 'self' data: cdvfile: file:".

index.html#/protocol:1 Uncaught (in promise) FileError
```

**Comment by wwqrd** [comment]
How do I recreate this bug? Is it a specific protocol?

**Comment by rebeccamadsen** [comment]
The teaching protocol has a video on the "Drawing Ties" screen. When I get to that screen in the android emulator, it briefly shows video controls and then even those disappear.

**Comment by wwqrd** [comment]
Adding `android-webview-video-poster:` to the img-src Content Security Policy makes the error go away (and is potentially something we should keep), but doesn't resolve the issue of videos not playing.

With no errors, the video tag rendering, and the data url populated, I'm temped to agree with you in maybe leaving this as-is.
