### ISSUE TITLE
Global app settings

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#390]
The ability for the app to set and read settings, that persist between restarts and are independent of interview protocol.

Candidates for this sort of setting:

- Window state/position.
- Animation enabled/disabled.
- Assume device has physical keyboard

**Comment by bryfox** [comment]
From #474, paired server information (currently persisted via redux, and resettable) may make sense to add here as well.

**Comment by jthrilly** [comment]
This is implemented in the settings menu.
