### ISSUE TITLE
Implement a way to toggle the dev tools with a keyboard shortcut during development

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#403]
We sometimes need to ask users for a stack-trace to help with debugging, but our compiled app disables the debug console.

We should implement either a keyboard shortcut, menu item, or both, to allow the dev tools to be opened.

**Comment by rebeccamadsen** [comment]
With Chrome the keyboard shortcut to open devtools should work, right? Is this just needed for Electron? How are we disabling the debug console -- just by not including the menu item? e.g., should [toggleDevTools](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentstoggledevtools) work?

**Comment by bryfox** [comment]
I can confirm toggleDevTools does still work in our production electron builds.

And I think the intent was (at least) for alpha releases — we want to hide dev tools by default, but give technical users a way to investigate and report console errors.
