### ISSUE TITLE
Name Generator: trigger followup prompt for missing attributes.

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#404]
Adding a node from an external data source (via panel, or roster) should optionally trigger the new node form to allow missing attributes to be added, if required.

**Comment by rebeccamadsen** [comment]
Optionally trigger, meaning this would be specified in the protocol? If so, default would trigger or not trigger the form?

**Comment by jthrilly** [comment]
Meaning it would be something the user could enable or disable. Maybe an interface attribute like `forceMissingData`

**Comment by jthrilly** [comment]
When I reflect on this, it seems that this functionality can be covered through the use of a per-alter form in addition to the roster generation screen. Closing.
