### ISSUE TITLE
GraphML exporting doesn't work for the teaching protocol

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#406]
Numerous reports that exporting as graphML doesn't work when using the teaching protocol. This functionality needs a review, since it has likely become out of sync since we implemented the variable registry and changed several APIs.

**Comment by rebeccamadsen** [comment]
Any specific feedback on how it fails to work? I can create a network and download a graphML file that I think looks correct in Gephi, so additional info on what isn't working or what the network looks like when it fails would be helpful.

Probably the "key" types could be updated to check the variableRegistry first before trying to figure out the type, but I don't think that should break anything.

**Comment by rebeccamadsen** [comment]
Okay, so we need to
- [ ] check if variable type exists in the variableRegistry when creating `key`s
- [ ] have better handling for `layout` variables

**Comment by rebeccamadsen** [comment]
Should data export in NC happen for the current session only, or for all existing sessions? It's currently happening for the current session only, with no network info in the file while on the start screen.

**Comment by jthrilly** [comment]
> Should data export in NC happen for the current session only, or for all existing sessions? It's currently happening for the current session only, with no network info in the file while on the start screen.

The data export should happen on a per-session bases as things are currently designed. Essentially, the graphML export is a stop gap feature that we wanted in for testing purposes. Eventually, exporting will be handled either at the start screen level (I don't think we have made an issue for this yet, but it could be tagged on to #550). 

Until then, let's fix it up for per-session exporting. Wayyyy down the line we will want to think about submoduling this so that it can be shared between Server and NC as one file format encoder of many.
