### ISSUE TITLE
Pinch to zoom works on Windows 

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#428]
With two fingers on the touchscreen, pinch to zoom works on windows tablets, when it shouldn't. This is on both the Surface and the Yogabook.

**Comment by jthrilly** [comment]
Looks like this might take a bit of thinking about: https://stackoverflow.com/questions/29929411/disable-pinch-zoom-in-webkit-or-electron#29994607

**Comment by bryfox** [comment]
Can I assume the goal is to disable zoom on all platforms? On macOS, the `webFrame.setVisualZoomLevelLimits(1, 1);` approach seems to work (i.e. disable zooming, which is currently enabled). Unfortunately, I can't test on a Windows tablet, but I could issue a PR with this change for others to test.

**Comment by jthrilly** [comment]
I think this is worthwhile, Bryan - thanks.

One question: could we manipulate this property to allow user directed scaling of the UI? For example, Slack supports the standard cmd +/cmd - shortcuts to let the user determine the zoom. I think this functionality would be very useful when dealing with various DPI and resolution issues across devices.

**Comment by bryfox** [comment]
Adding the standard menu items should support zoom in that way. I'll open a PR with both of the above for testing.
