### ISSUE TITLE
Font sizing on windows is inconsistent

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#429]
On the Yogabook (a 1080p screen), when the native display resolution is at 150% the sizing of the Network Canvas elements are too large to be reasonably viewed. When the resolution is at 100% the elements are fine but the font is too small. 

By contrast, on the Surface, when working at 200% native display resolution (admittedly on an older version of Windows 10) the font size is fine and the elements are at a visible size. 

I can't tell if this is a feature, a bug or something that must be explained in the configuration manual.

**Comment by jthrilly** [comment]
Related to #361
