### ISSUE TITLE
Feature request: collapsing instructions 

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#430]
The node occlusion issue on the sociogram screen presents a challenge. do we prevent people from dropping on the left hand side? The box of instructions seems to be collapsible if you click the green bar (as the name generator collapses, e.g., 'Your classmates' in the teaching protocol). But this bar neither closes nor is movable. This means that one can drop a node in behind that square and it cannot be retrieved. There's no 'undo'. The reset button resets everything and not just the layout on that page. 

Putting the text at the top of the sociogram really warps the layout and pushes everything down, which is not idea on standard sized sccreens  for laptop and mobile. I propose that the instructions are altered so that they say 'instructions' at the top, and have the green bar at the bottom, then they can be collapsed just like the other panels. However, in this case, they should collapse downwards so that it is a tab at the bottom and not upwards so that it is a rectangle roughly 25% from the bottom of the screen.

**Comment by jthrilly** [comment]
Existing bug #371 also addresses this.
