### ISSUE TITLE
Client "name"

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#435]
Upon startup, Network Canvas should prompt the user to give the device a memorable name, or else generate one automatically (think google docs). This name can then be used by Server to help identify devices when pairing/managing paired devices.

Potentially integrate with #388 and #390

**Comment by bryfox** [comment]
As of #488, the app automatically assigns a best-effort name based on environment info. I'm leaving this open, since we'll want to allow (or prompt) this default to be customized as noted in #73.

**Comment by bryfox** [comment]
Should this be modal? i.e., the user is confronted with the name input before doing anything else? If so, is the user-given name required?

Or perhaps this input could be combined with some of the other settings mentioned in #390 on a separate settings/prefs screen?

**Comment by jthrilly** [comment]
This is implemented as part of the settings menu
