### ISSUE TITLE
Edge still exists when a node is deleted

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#437]
When a node is deleted, existing edges with that node are not deleted. This means that when a node with that same "id" is added again (which can happen if all the nodes are deleted), the edge just shows up in the sociogram. It also means that any queries against the network can use edges the user can't even see as part of a matching query for skip logic.

I think deleting any edges with the deleted node would probably make sense for both of these situations.

**Comment by wwqrd** [comment]
ids were originally intended to be optionally specified by researchers, i.e. in roster lists, because they may be fixed across interviews / prior data. uids are used internally by NC. So from this perspective `id` should be used in edges.

I'm not sure if #415 changes that? It's definitely related.

**Comment by bryfox** [comment]
OK, thanks. So `id` is user data, and `uid` is for internal management. To implement this feature, I believe edges should store both — the reducer would use `uid`s to associate edges with their nodes. Does that sound right?

**Comment by wwqrd** [comment]
I'd be tempted to use a thunk and operate on the ids - it seems cumbersome to have two relationships that need to be kept in sync?

I've always been a bit dubious of the inherent duplicitousness of two ids on nodes, perhaps there's a clearer way to implement it that would allow us to use uids throughout. Say, an optional `externalId` which is transposed on export?

**Comment by bryfox** [comment]
> that would allow us to use uids throughout

#415 specifies a way for an arbitrary field to be used as an ID, which is a more general case of the `id` convention. That `id` is optional: if it's specified, we'll use it for the `uid`; else we'll generate one (== content digest).

One option: The app only needs to care about `uid`. `id`, `clinicId`, `myPrimaryKey`, etc, are just user data like any other. `uid` does not need to be kept in sync; it's immutable (as are user-defined IDs defined to be). Edge export doesn't care about the property name (`"from":3,"to":2`); as long as `uid`s equate to user-provided `id`s, edge semantics are preserved.

---

I'm assuming above that we don't want to pollute the ID space of node data, but if that's what we do want [use case?], then we could either:
- transpose on export, as you said
- use the user-defined PK field (defaulting to 'uid'), and generate IDs when missing

**Comment by wwqrd** [comment]
Ahh I see #415 seems to specify that this external id *is* uid. It can be optionally specified in nodes for externalData, otherwise we generate one? In that case it sounds like we are removing ids entirely and you are right that we should switch over edges to use uids.
