### ISSUE TITLE
On NameGenerator, when adding/editing a new node, changes can be lost accidentally

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#461]
On NameGenerator, when adding/editing a new node, changes can be lost accidentally by clicking outside of the modal.

Changes are lost when reopening form.

**Comment by wwqrd** [comment]
This may be a broader question about the modal windows throughout the app.

**Comment by jthrilly** [comment]
This was addressed in Server by removing the ability to close a dialog by clicking the background. We should do the same here.

**Comment by wwqrd** [comment]
This will be resolved by the changes for https://github.com/codaco/Network-Canvas/issues/707
