### ISSUE TITLE
Standardize <esc> behavior

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#466]
Current behaviors:

- Pressing `esc` closes the stages sidebar
- Pressing `esc` does not close the session sidebar
- Pressing `esc` closes the 'autocomplete' form/modal
- Pressing `esc` does not close the add & edit form/modal
- If autocomplete & stages sidebar are both open, pressing `esc` closes both

**Comment by rebeccamadsen** [comment]
I think with the original design of the menus, both settings and session menu ought to have captured the `esc` event if open (not the autocomplete or modals), although I'm not entirely sure how that fits in with [the new menu system](#245).
