### ISSUE TITLE
Node or edge is repositioned incorrectly after "offscreen" drop

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#469]
[Desktop]

On the sociogram, if I drag a node & release the mouse button outside the window, then the node is positioned at its initial dragStart point. (Though if I leave the stage and come back, it's positioned near the exit point.)

If there are edges connected to it, then the edges remain 'connected' to an area where the node left the window.

![node-edge](https://user-images.githubusercontent.com/39674/39140166-c54dc460-46f1-11e8-880d-9cc3321010eb.png)

It's only a minor annoyance; any further click, drag, or navigation gets things rendering correctly again.

Expected behavior: either update the edge to follow the re-positioned node, or reposition the node at the window exit point.

(Note: an un-positioned node dropped offscreen is currently replaced on the upper-right stack of nodes, which does make sense, rather than moving to the window exit point.)

**Comment by wwqrd** [comment]
This is an interesting one.

It seems like if you drag something offscreen, and then click the node that pinged back, it'll return to the exit point.

Might point to it being an artefact of rendering optimisations.

**Comment by wwqrd** [comment]
Un-positioned nodes follow a different execution path in that they are "added when dropped", whereas dragged nodes are "updated as moved", so probably isn't crossover there.

**Comment by rebeccamadsen** [comment]
Fixed in #689.
