### ISSUE TITLE
Sanitize and/or custom-parse all user input

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#472]
App should never evaluate user input (e.g., from a protocol file). Any input should be checked against a whitelist; any dynamic functionality should be come from validated & parsed input rather than evaluated directly.

This is especially true on desktop, where the current implementation requires node integration in the browser view.

**Comment by jthrilly** [comment]
# Areas of particular concern
- Skip logic processing allows a stringified function to be evaluated. In a node environment. This is bad.
- Custom react interfaces can be built and imported. These ultimately get evaluated, which is also bad.

# Proposed solutions to make protocol files safer

- Remove node code to main thread, and communicate with node modules only via IPC calls. this is the priority, because arbitrary execution in a node environment could be very bad.
- Remove string eval for skip logic entirely, and depend on network querying. This functionality is somewhat speculative, and we can reintroduce it if/when we get more design input.

**Comment by bryfox** [comment]
`webPreferences.nodeIntegration` in [browserWindow](https://electronjs.org/docs/api/browser-window) is the main mechanism for proposed solution 1 above.

There's another challenge with implementing this that I ran into on Server: Webpack's `electron-renderer` target assumes the presence of `require`. So in addition to removing node APIs from renderer code, I think we'd need to customize the webpack config further.

**Comment by wwqrd** [comment]
Also worth noting from a conversation @jthrilly and I had: if we decided to drop support for Electron that would really limit this scope of this issue.

**Comment by bryfox** [comment]
For some of the 'arbitrary functionality' use cases like skip logic, I also wonder if delegating to a web worker (without nodeIntegration) would solve most of the problems. Input data is contained; output data is limited to a well-formed object (or boolean...); the worker itself has limited exposure, but has the flexibility to do anything else a web worker can do. (For skip logic that needs tighter integration with the environment, we have the object interface in the protocol, which already sidesteps the eval problem.)

**Comment by jthrilly** [comment]
> For some of the 'arbitrary functionality' use cases like skip logic, I also wonder if delegating to a web worker (without nodeIntegration) would solve most of the problems.

I have looked into this idea too, and I think it has a lot of potential. We can use the messaging mechanism to provide a boolean response value, and a timeout to avoid bad UX. We could also post limited interview data (the interview network?), although careful consideration would need to be made of potential leakages.

The only issues I could think of are that it might not be compatible with the Cordova environment on all devices (does the iOS web view support workers?), and that it doesn't help us to resolve the custom react interface issue (where we would still need to disable node integration, unless we can think of a better idea). Here, we could pursue Steve's idea, perhaps, although I don't know how exactly that would work.

**Comment by jthrilly** [comment]
Okay, so an update from the meeting yesterday:

- We do have clear use cases for custom functions in the protocol to handle things like node labels (skip functions were seen as less important). 
- This means we can either implement a custom JSON based format for expressing the common use-cases for custom labels (this will be complicated: typical use-cases will be concatenating two other variables [first name and first initial of last name with a space in-betwee], appending a counter or string or emoji to variable [nickname + emoji based on the value of some other property, or nickname + consecutive number] 
- or allow running javascript in a context where there is no node integration (either a web worker or a web view with node integration disabled).

- We have decided to remove the ability to write custom interfaces and bundle them with the protocol for now.

- Another option was discussed, which was some sort of "advanced mode" that is off by default, and which is required to be turned on to be able to run a protocol that has directly evaluated code. We could double down on this feature by also permanently disallowing protocols that contain directly evaluated code to be installed via http, meaning they must be transferred to network canvas through a secure paired link with an installation of server. 

I found this article incredibly helpful: https://github.com/electron/electron/blob/master/docs/tutorial/security.md

**Comment by bryfox** [comment]
I've opened #505 as a stopgap solution for the first immediate concern. The second listed above is arbitrary interface code, which we no longer need to support. Can someone point me in the direction of that implementation?

I've also merged #504, which removes that vulnerability surface (arbitrary/untrusted web content loading in the app), and will update the security document.

I think the remaining discussion items here can be used to open more specific issues as we build out new features.

**Comment by wwqrd** [comment]
Maybe a library like: https://github.com/Matt-Esch/string-template would be enough complexity for labels? If not we could go full [handlebars](https://handlebarsjs.com/)?

**Comment by jthrilly** [comment]
I created this issue to describe requirements for custom labels more clearly: https://github.com/codaco/Network-Canvas/issues/610

**Comment by bryfox** [comment]
The immediate problems reported by this issue were addressed. Comments here provide good background; we can funnel discussion to specific, concrete issues starting with #610.
