### ISSUE TITLE
MDNS advertisements sometimes not seen on Android

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#482]
On Android, mdns advertisements sometimes suddenly stop arriving as expected. The only way to get them working again is to wipe the device — full restarts of app don't help. I don't have specific repro steps, but this happened three times while investigating mdns issues.

I'm testing on a macOS emulator (Pixel C, API 26).

- `adb logcat -s ZeroConf` indicated listeners were added but native callbacks never heard.
- `dns-sd -B _network-canvas._tcp .` (and other clients) confirmed advertisements were going out

**Comment by jthrilly** [comment]
Eek. Once you have reproduction steps, I will test this on a physical device and we can investigate/create an upstream issue.

**Comment by bryfox** [comment]
I tested #483 on a device (Nexus 5X, 8.1.0); was flaky there as well. On a couple of occasions, I needed a few (3-5) app restarts to see advertised services. (Perhaps the 'wipe data' step in the description isn't actually required for the emulator, and more relaunches would have worked.) Tried flushing chrome DNS & resetting network settings to no avail.

Still no specific repro steps, but it's not too hard to repro on my device just by relaunching.

Discovery with [a third party app](https://play.google.com/store/apps/details?id=com.melloware.zeroconf&hl=en) which doesn't appear to use jmdns seems to be working fine.

**Comment by jthrilly** [comment]
So to reproduce, I just need to have the app open and toggle service advertisements on and off until they stop appearing?

I notice there is another cordova plugin for zeroconf. After we exhaust the route of filing an upstream bug report, we could experiment with replacing the plugin.

**Comment by jthrilly** [comment]
Hm, this would seem to be a quite significant issue then! Definitely a blocker. 

I'm going to try testing this against different API versions until we have enough of a picture to be able to file a bug report upstream.

**Comment by bryfox** [comment]
The two cordova plugins I see both rely on JmDNS. Android does have a [native API](https://developer.android.com/training/connect-devices-wirelessly/nsd#discover) for the versions we're supporting; writing a plugin with that might be faster than troubleshooting where the problem lies. Certainly a prototype would be, just to see if there's any change in behavior.

It's entirely possible there's something wrong with Server advertising; I'm just using the third-party zeroconf browser mentioned earlier as a basis for ruling that less likely.

Curious to see what your tests show.

**Comment by jthrilly** [comment]
That's a great lead @bryfox. It looks like this cordova plugin actually implements the native API you linked to: https://github.com/ionic-team/cordova-plugin-discovery

Its abandoned, with no documentation, and likely isn't in working form. BUT it looks like the android side of this is relatively simple. We could potentially use it as a starting point for updating our own fork of the cordova zeroconf plugin. There are relatively few methods to implement, and the API is documented well. We are okay with the API level limitation, too, so we don't need to support JmDNS at all for backward compatibility.

Would you like me to have a go at this, or do you think we should persist with what we have? Personally I am seduced by the idea of using the new native API, and I think it would be forking our own version of the plugin for.

**Comment by bryfox** [comment]
Looks like they pasted in the example code from the android docs as a comment. If I were going to fork, I'd fork from the plugin we're using now, which we've seen work well on iOS.

Have you been able to reproduce the flakiness on your tablets? (I'd like to know that someone else has this problem, especially since my phone isn't technically supported.) If so, then yes, I think a quick prototype with native APIs is the best next step. I'm happy to do it, or have you do it.

**Comment by bryfox** [comment]
I think there are two issues here:

1. Device discovery fails silently, period (e.g., happens even on fresh restart)
2. Device discovery fails after reloading component (corresponds to an unwatch/watch pair in ZeroConf)

The former happens mostly on the emulator. I have no idea why (and wiping data hasn't even been effective today), but if it's limited to emulators, I'm not going to burn more time now.

The latter happens repeatably on device. I've added a prototype implementation of `DiscoveryListener` to the plugin, which seems to 'rediscover' services reliably. I can proceed with the new/forked plugin if that still makes sense.

I would love to hear if others' experiences differ from the above.

**Comment by jthrilly** [comment]
I would love to say I've seen it too, but I didn't encounter this when developing the initial listening functionality. 

With regard to the "reloading component": do you mean to say that the plugin (re)instantiation causes this? So changing the view and then returning to the server discovery page? If so, I will test this more extensively.

As far as "what to do", I think this goes in the errata for this release, and perhaps the re-write using `DiscoveryListener` becomes a target for Alpha.5.

**Comment by bryfox** [comment]
> changing the view and then returning to the server discovery page

Yes, that causes it. The plugin uses the same underlying instance (of its 'browser'), but discovery never happens again even though `watch()` appears to be called again.
