### ISSUE TITLE
UX: Pairing code entry

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#492]
Subtask of #474.

When users pair to servers, they enter a pairing code displayed on Server's GUI. Here's the mockup of client-side entry:

<img width="568" alt="code" src="https://user-images.githubusercontent.com/39674/39757569-88ce6926-52cd-11e8-9569-3923ad5085d7.png">

### Requirements

Goal: help the user enter a long-ish password correctly the first time.

Ideally, this supports all common text editing functionality (direct entry, paste, select all, delete range...) and can highlight known problems with the input — e.g., user  entered 'O' instead of '0', or another character outside the possible set. The 'paste' case is useful assuming a desktop client may be running on the same machine as server.

### Possible approaches

1. Multiple text inputs
    - User won't be able to 'select all' (or range)
    - delete use case: could provide clear button instead
    - paste use case (same machine): intercept [super]-v, and apply/overwrite values?

2. Single text input (possibly with background image for styling)
    - less-flexible UX
    - can't highlight error for single char
    - background image spacing need to work with zoom? and tied to font: platform differences?

3. Some hybrid of 1 & 2: (1) by default; allow switch to (2) for pasting?

4. Multiple ContentEditable[-toggled] elements
    - Most flexible; most complex
    - When not content-editable, can select ranges; clicking makes each element editable
    - Require document-level keyboard handling, selection management
    - Have to work 'outside' React for at least some of this

### Next Steps

Need to choose an approach above.

I implemented most of (1) above, then realized the limitations of text selection. It's pretty simple, and if the limitations are OK for v1, perhaps we stay there for now. Same-machine pasting and deleting may be rare cases, as far as I know.

(2) feels like it optimizes for the uncommon cases.

(4) might produce the best UX, but I'm not sure it's worth the effort or complexity, at least in v1.

Thoughts welcome!

**Comment by jthrilly** [comment]
I feel like approach (1) is the winner, for a couple of reasons.

- We can keep the segmented look, without the complexity in styling.
- Pasting is doable, by catching and handling the onPaste event for any of the inputs. 
- Copying out of this control is not something users will need to do.
- Select all can be handled by "clear", as you pointed out.

I think this should be implementable as a single react component that manages all the individual inputs, and the logic between them. Other needed functionalities would be:

- Backspace on an empty input moves the cursor to the preceding input
- Cursor automatically advances as data is entered
- It isn't the highest priority, but I'd like it if we could ensure this is somewhat accessible. When I was researching input masks, I found a lot of information about how poorly they are handled by screen readers. If we can do better, that would be excellent.

**Comment by bryfox** [comment]
Great, thank you for the direction. I'll leave the original description for reference.

TODOs:

- [ ] Support paste
- [ ] Add 'clear' button/link
- [x] support backspace
- [x] auto-advance cursor
- [ ] research additional accessibility requirements
