### ISSUE TITLE
Can't remove node from prompt because panel has collapsed

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#495]
When using the "already mentioned" panel, if all the nodes are dragged to the current prompt, the panel disappears. This is intended behavior, designed to remove screen clutter.

However, if the user begins to drag a node in the main node list, the "already mentioned" panel should reappear, since it is a viable drop target for nodes that originated there.

**Comment by jthrilly** [comment]
The general case here is that valid drop targets should become visible when the drag begins. I'm not sure how this could be implemented given our current component hierarchy.

One option would be to create some duplication of code, and have a component that combines the drag/drop functionality with the show/hide functionality of the panel.

**Comment by bryfox** [comment]
I can't reproduce this issue. Here are the steps I took (tested Mac & iOS sim):

1. Load dev protocol (fresh session)
2. Advance to Name Generator stage
3. Drag Carl to *Main* list
4. Advance prompt using swiper
5. Observe Carl in *Already Mentioned* list
6. Drag Carl to *Main* list; observe *Already Mentioned* disappears
7. Start dragging Carl; observe *Already Mentioned* (with empty list) re-appears
8. Drop Carl in  *Already Mentioned*

If, before step 7, I drop Baz in *Main*, and then start dragging Baz, then *Already Mentioned* does not reappear. I think that's expected.

Are there certain conditions that cause this to fail?

**Comment by rebeccamadsen** [comment]
I still can't reproduce this one either.

**Comment by jthrilly** [comment]
Let's close then!
