### ISSUE TITLE
Improve communication granularity of pairing protocol

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#497]
From [#488](https://github.com/codaco/Network-Canvas/pull/488#pullrequestreview-121101186):

> The UI for key entry appears on NC device before the pairing request has been acknowledged on Server. I presume this is because this is when the key is actually being generated behind the scenes, but it didn't "feel" quite right. Cancelling the pairing request also doesn't notify the client in any way that pairing has been refused.

We could use polling, long-lived connection, or change to message passing in order to provide these details to the client.

**Comment by bryfox** [comment]
As discussed, the 'long-lived' connection is the simplest approach to support this part of the flow. Subtasks:

- [ ] Do not respond to client until user has accepted/dismissed pairing request
- [ ] ...or until a 30s timeout on server, which should automatically dismiss
- [ ] Client: probably update views; a simple loading screen doesn't indicate that action must be taken on server
- [ ] Client: handle new error cases (display to user)
- [ ] Client: implement connection cancellation
    - I was postponing this to see what [React suspense](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html) might bring, but the long-lived request kind of demands it now; will need to switch from fetch to XHR or a lib, since abortable fetch isn't a reality on our platforms yet.
- [ ] Handle connection cancellations on server

**Comment by jthrilly** [comment]
> Client: implement connection cancellation

Hopefully I understand what you mean here (the client must respond to the user dismissing the pairing dialog on Server). With this, do you think it would be too much of an abuse to just use HTTP response codes? 403 or 401 perhaps?

**Comment by bryfox** [comment]
> the client must respond to the user dismissing the pairing dialog on Server

This is actually the case I was trying to describe with "Client: handle new error cases", and yes, that's basically what I've implemented so far. In the case of dismissal or timeout on the server, the API returns an error code and client presents a message (either 'cancelled' or 'timed out') to the user. (In terms of appropriate status code — 4xx vs 5xx or even 2xx — I'm leaning towards 5xx, but they're all a little weird in this scenario).

The flip side (and what I was trying to describe with "implement connection cancellation") is a client aborting the request, e.g. when a user closes the pairing modal on Network Canvas before acknowledging the pairing on Server.
