### ISSUE TITLE
Reset all app data menu item ("Global reset").

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#501]
As discussed in #498, we need a global reset option for Network Canvas so that server pairing data, and global app settings, can be reset once the "reset session" menu item is removed.

This needs to be implemented within the current menu system until the new one is ready.

**Comment by bryfox** [comment]
Based on more discussion in #498:
- [ ] Rename the existing item ("session" -> "app data")
- [ ] Add reset to native electron menu
