### ISSUE TITLE
Android (sometimes?) MDNS missing hostname

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#510]
When my Android device discovers an advertising server, it's missing the hostname. (I thought this was working in earlier tests, but perhaps that was prior to labeling changes.)

- <strike>[ ] Could use a TXT record from Server to provide a label</strike>
- [x] Fall back to IP address if not available
- [ ] Use instance name from advertisement

See also changes coming in #482.

**Comment by jthrilly** [comment]
Can you tell me more about how this works? Does the client do a DNS lookup to get the hostname (with the result presumably corresponding to the `SERVER_RESOLVED` event? If so, does the above error mean we just getting `SERVER_ANNOUNCED` but the hostname resolution is failing? 

One thing that is supposed to speed this up is limiting to IPv4, which I think is worth trying. Aside from that, I think there might be some known issues with Android resolving hosts in the `.local` domain (I found this linked from the zeroconf issue tracker: https://issuetracker.google.com/issues/36916949). Can we learn anything by experimenting with different domains?

**Comment by bryfox** [comment]
See https://github.com/codaco/Server/issues/101. I think the correct approach is to use MDNS instance names, and not rely on hostname at all. Server can use hostname as a default instance name.
