### ISSUE TITLE
nodelist order keeps changing on scroll

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#524]
Add a bunch of nodes (e.g. mock nodes) to a list. Note the visible names. Try to scroll that list a bit. When you stop scrolling, note the visible names. Often, they are the same as before, or maybe a few names are updated but many are the same.

Likely related, you could infinitely scroll the list and not reach the end.

**Comment by wwqrd** [comment]
Sounds like something is going wonky with react-transition-group? keys?
