### ISSUE TITLE
Implement animations on new start screen

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#528]
The new start screen should animate when moving between sub-views and when triggering certain events:

- Switching between new interview and resuming in-progress
- Starting an interview (should trigger the "zoom to fill screen" animation used extensively in Arcitect
- Opening the server pairing view

Most of these are covered by the principle mockups.

**Comment by rebeccamadsen** [comment]
Possibly superseded by, but at least related to #848.
