### ISSUE TITLE
Ability to delete protocols and in progress interviews

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#529]
Users should be able to delete protocols from the device, and they should be able to discard/delete in-progress interviews.

- Deleting protocols could be managed by long-pressing the card representing the protocol. Care will need to be taken to handle in-progress sessions using this protocol. We will need to warn that user that the protocol the session refers to cannot be found, and perhaps think about ways to allow them to export data. This could be linked to functionality for exporting data en masse from the start screen.
- Deleting in progress interviews should use the "drag to bin" mechanic from the node list.

**Comment by bryfox** [comment]
Superseded  by #550.
