### ISSUE TITLE
Implement "Finish Interview" UI

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#544]
This needs more definition to begin. Notes from jthrilly:

> This again has no fixed design at present. Some starting points for an implementation are a menu item or a full blown interface, which is configurable in architect. Right now, I’m excited by the possibilities of the latter.

#543 covers data export; that's out of scope for this issue even if it ends up being part of this interface.

**Comment by bryfox** [comment]
For the next release, we can use a simple version of a Finish Interview interface as a natural point to export (single session) data.

- this can be automatically added (as last stage) without needing configuration
  - though maybe with a simple flag to disable it (or can we use skip logic?)
- interface should contain an 'export' button (assuming there's a server to export to) which exports and closes session.
- interface should contain a 'finish' button which closes session

**Comment by jthrilly** [comment]
> this can be automatically added (as last stage) without needing configuration
> though maybe with a simple flag to disable it (or can we use skip logic?)

I don't think we will need to disable it.

> interface should contain an 'export' button (assuming there's a server to export to) which exports and closes session.

Worth pointing out that "export" could be either (1) uploading to a server, or (2) writing a file in a network file format. Perhaps with a choice between either.

> interface should contain a 'finish' button which closes session

We also had an idea of setting a session flag (`exported`?) to indicate that the session had finished and data had been exported.

**Comment by bryfox** [comment]
>  "export" could be either (1) uploading to a server, or (2) writing a file in a network file format

This could be (one or more of) multiple servers as well (#543)... for this release, I've assumed a single (default) server.

Is file export I should integrate into this interface right now? (Should the Download Data menu item be moved here?)

> setting a session flag

I've added it `lastExportedAt` property to the session.

Here's what it looks like now ([feature/finish-interface](https://github.com/codaco/Network-Canvas/tree/feature/finish-interface)):

![export](https://user-images.githubusercontent.com/39674/41785007-51e09b7c-760f-11e8-9986-dd974dcb9215.png)

**Comment by jthrilly** [comment]
> Is file export I should integrate into this interface right now? (Should the Download Data menu item be moved here?)

Yes, that's actually a really good suggestion.

Looking great!
