### ISSUE TITLE
Better definition and handling of protocol metadata

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#545]
Currently:
- redux protocols are initialized from mocks.
- there's a loose association between session & protocol (URL-based)
- an updated protocol (new version) overwrites the existing version (I think)

Requirements:
~~- Sessions need to be associated with a protocol version~~

Questions:
~~- Should protocols with multiple versions be shown separately in the 'start session' interface? (Once download, are old versions available for starting new sessions?)~~

**JRM**: I updated the above to avoid confusion about multiple concurrently installed versions of the same protocol. This is no longer something we want to support.

New Requirements:
- Updating a protocol "version" (now defined as a "last modified" property in protocol.js) in a client will prompt the user that continuing will delete all existing interview sessions using this protocol.

Relates to https://github.com/codaco/Server/issues/107.

**Comment by wwqrd** [comment]
I also think that maybe the protocol / session modules could do with a bit of revision, it seems like there are multiple overlaps which could be streamlined so that behaviour is better isolated between the modules. Something like:

# loading a protocol (new session)
1. [open] createSession 
1. loadProtocol / factoryProtocol
1. updateSessionMeta
1. [on change] updateSession

# loading a session
1. [open] setSession
1. loadProtocol / factoryProtocol
1. updateSessionMeta
1. [on change] updateSession

**Comment by jthrilly** [comment]
In addition to agreeing with Steve about restructuring the behavior for protocol loading, I updated the above to be consistent with our current understanding.

**Comment by bryfox** [comment]
@wwqrd can you provide some more detail on how you see the redux state evolving? I think your comments above are describing user workflows; how would those responsibilities be separated between the modules?

Here are some questions I had after looking at it:

- Should we lean more on epics to handle composed flows like download/import/load/set?
  - Conceptually (to me), starting a session would mean loading the protocol, then creating a session. (Currently, if I import an invalid protocol, the app creates a 'zombie' session that can't be resumed.)
  - ...and resuming a session would mean setting the session, then loading the needed protocol.
  - ...but thinking of it like this probably hinders the desired isolation
- When downloading from the Server API, there's additional metadata that makes the above more complicated; one example is remote protocol ID in #556. I assume that's where the `protocols` module will fit in? i.e., `addProtocol()`?
- Does factory protocol handling need to be separate? There seem to be a lot of differences in actions and reducers, but I wonder if that's one of the places we can simplify once we're handling metadata appropriately.

**Comment by wwqrd** [comment]
@bryfox I'm describing the redux actions/epics.

At the moment it's handled inconsistently in sessions, depending on how the protocol is loaded (session vs from file vs from factory protocol).

I think it could be streamlined into to probably a single additional action (`updateSessionMeta`) which both handles the side-effects of `LOAD_PROTOCOL` in `src/ducks/modules/sessions.js`, whilst also compiling the protocol meta data.
