### ISSUE TITLE
Harmonize NodeList and CardList components

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#549]
We should harmonize/combine these components, since they provide very similar functionality. In fact, they differ only in the entities that they render, which could conceivably be passed to the component as props.

Key areas of functionality:

- Sorting. The (optional) ability to sort by one or more properties. Implemented using the `sorty` library.
- Filtering. (optional) ability to filter the list using fuzzy matching of one or more properties of each entity.
- Scrolling. Scroll behaviors and styles associated with a list that might overflow the screen. Potentially also supporting #548
- Transitions. NodeList uses an animated transition to reflect changes in data. CardList should benefit from this, too. Could the in and out animations be specified as props somehow?

Areas of divergence: 

- Drag and drop. NodeLists use it, but CardList does not (although this feature is required for the resume interview screen).
- Color. NodeList provides the ability to specify the color of nodes contained within. I think this should be deprecated in favor of using the node type to detect color. Overriding is still possible through CSS.

**Comment by jthrilly** [comment]
This was discussed in #555 in relation to sorting.

The NameGeneratorList interface uses `<CardList />` rather than `<NodeList />` and implements filtering and sorting on top of that. The [basic api](https://github.com/codaco/Network-Canvas/blob/cfd0fa93fc6ad33fb97b3b72231912966182e3af/public/protocols/development.netcanvas/protocol.json#L950-L964) looks like this:

```
          "sortOptions": {
            "sortOrder": {
              "name": "ASC"
            },
            "sortableProperties": [
              {
                "label": "Pupil Name",
                "variable": "name"
              },
              {
                "label": "Pupil Age",
                "variable": "age"
              }
            ]
          }
```

What I think we should do, is refactor this interface to use

**Comment by wwqrd** [comment]
It looks like `<NodeList />` and `<CardList />` are both simple views for a list of nodes.

In the case of `<NameGeneratorList />`, sorting an filtering is handled by a parent component called `<ListSelect />` which contains UI controls and `<CardList />, which receives the managed node array:

```
// pseudocode
const ListSelect = () => (
  <div>
    <SortControls />
    <CardList nodes={sortedNodes}/>
  </div>
);
```

So I think what we want here is:

1. Generalise `<ListSelect />`, to maybe take a component argument:

`<ListSelect component={NodeList} />`

Which will require harmonising `<NodeList />` and `<CardList />` to have the same interface where possible, perhaps passing down any specific props:

`<ListSelect component={NodeList} listSelectSpecificProp nodeListSpecificProp={foo} />`

`const ListSelect = ({ listSelectSpecificProp, component: Component, ...rest }) => (
  <Component {...rest} />
);`

2. Update `<ListSelect />` to accept an initial configuration that accepts multiple properties matching sorting elsewhere:

```
"sortOptions": {
  "sortOrder": [
    { property: 'name', direction: 'asc' },
  ],
  ...
}
```

3. Update `<ListSelect />` to use `/utils/sortOrder` internally

**Comment by wwqrd** [comment]
I'm going to implement 2. as part of https://github.com/codaco/Network-Canvas/pull/555
