### ISSUE TITLE
add fifo sorting to node containers

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#553]
Generalize the [sociogram fifo sort](https://github.com/codaco/Network-Canvas/pull/552#issuecomment-396948823) for other node containers, such as NodeList.

**Comment by jthrilly** [comment]
Should happen as part of #549

**Comment by bryfox** [comment]
I think this was implemented with #555. NodeList, Sociogram, and other components use `utils/sortOrder` either directly or in selectors.

**Comment by jthrilly** [comment]
> I think this was implemented with #555. NodeList, Sociogram, and other components use `utils/sortOrder` either directly or in selectors.

Correct!
