### ISSUE TITLE
Duplicate protocols appear in setup list

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#558]
Downloaded protocols are saved with unique (uuid) filenames, so we can't rely on path to determine whether a protocol already exists in state.

#556 contains an interim fix for protocols imported from Server (based on remote ID), but this is still an issue with protocols downloaded by URL.

This is probably relevant to the discussion of redux state shape in #545.

**Comment by jthrilly** [comment]
So as part of redesigning the redux actions for loading protocols, the canonical protocol name should be available for evaluation after the protocol is temporarily extracted, so it can be validated before the extracted protocol is moved to the final protocol location within the app.
