### ISSUE TITLE
Support export to multiple/different servers

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#560]
From #543: "UI: Select a server to export to".

The user may have multiple paired servers. They may want to pair to more than one, or select a specific server to export to.

Need UX design: should this optimize for exporting to a single server, and store the 'chosen' server in settings, or should the export interfaces be more flexible?

**Comment by jthrilly** [comment]
How about reproducing something similar to the server browser UI from the pairing flow? Icons representing available options, with the default one "selected" (perhaps something as simple as a visual emphasis, like the opacity for paired/unpaired).

**Comment by bryfox** [comment]
No longer needed; see #661. Export will be straightforward without changes.
