### ISSUE TITLE
Old protocol files/directories are never removed

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#567]
If a user imports an updated protocol, the previous version should be removed. Currently, no previous protocols are removed (even on app data reset).

**Comment by wwqrd** [comment]
We should probably clear updated protocols when the overwrite an existing one.

But generally, the data is stored in an application's temp directory, should we manually clear that?

**Comment by wwqrd** [comment]
~We should probably clear updated protocols when the overwrite an existing one.~
This isn't necessary as destination paths are newly generated each time.
