### ISSUE TITLE
Protocols: Parse/validate before import

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#568]
Downloaded protocols (saved to tmp/**/*.netcanvas) are moved to the user directory (IMPORT) before being parsed or validated (LOAD).

Protocols should be extracted, parsed, and validated before imported to the user directory (and redux state).

We're still investigating validation using json-schema; for now, should just ensure that protocol.json parses correctly and that the resulting object has a `name`.

Optional: rename the [uuid].netcanvas base to something deterministic based on protocol name so that old directories don't need to be cleaned up (#567). (Server uses a sha256 hash of unicode-normalized name.)

**Comment by jthrilly** [comment]
Implemented with `feature/file-import`
