### ISSUE TITLE
Migrate 'factory' protocols to standard protocols

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#570]
If factory protocols were treated as standard protocols (albeit ones that are automatically imported to the user data directory), then we no longer need special handling for factory protocol types (in redux state, actions, file handling, and app routing).

To bootstrap the factory protocols, files can be copied (from app dir) at startup and the corresponding redux state updated.

- Because these are actively developed, they should be restored easily/automatically on reload (at least during development).
- [TBD] Users shouldn't be prevented from overwriting those protocols (e.g., we don't need to make 'Teaching Protocol' a reserved name)

**Comment by jthrilly** [comment]
@wwqrd - any thoughts on this?

**Comment by jthrilly** [comment]
I've taken care of this, by removing the concept of factory protocols.
