### ISSUE TITLE
Better handling of download error responses from Server

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#573]
Protocol Downloads use [request](https://github.com/request/request), which uses an `encoding` property on the request to indicate the expected response type. It appears to ignore response `Content-Type`s.

Server's convention is to deliver files as application/zip (which keeps API compatibility), but an application/json response for errors.  So a user may see an error message along the lines of:

```
"401 - {"type":"Buffer","data":[123,34,99,111,100,101,34,58,34,73,110,118,97,108,105,100,67,114,101,100,101,110,116,105,97,108,115,34,44,34,109,101,115,115,97,103,101,34,58,34,34,125]}"
```

As a workaround, we could parse our own messages higher in the stack (since the full response is added to the error object), or just work from status codes and not use Server's messaging.

**Comment by wwqrd** [comment]
It looks like you can access content-type from the request docs?

```
request
  .get('http://google.com/doodle.png')
  .on('response', function(response) {
    console.log(response.headers['content-type']) // 'image/png'
  })
  .pipe(fs.createWriteStream('doodle.png'))
```

Maybe it's this that's causing us issues:

> encoding - encoding to be used on setEncoding of response data. If null, the body is returned as a Buffer. Anything else (including the default value of undefined) will be passed as the encoding parameter to toString() (meaning this is effectively utf8 by default). (Note: if you expect binary data, you should set encoding: null.)

We set that to null so all data is always returned as Buffers.

**Comment by bryfox** [comment]
As of #646, protocol downloads from Server will no longer use `request`.
