### ISSUE TITLE
Updating a protocol should invalidate in-progress interviews

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#575]
A protocol may be updated by downloading a protocol with a duplicate name. We don't support running multiple protocol versions concurrently, so this should invalidate past sessions.

- [ ] UI: If outstanding sessions exist, warn user on import, and provide option to cancel update
  - Depends on #568: need to parse protocol before import
- [ ] Mark sessions as invalid in state (or possibly remove)
- [ ] Update UI for displaying invalid session cards (perhaps allow export but not resume?)

**Comment by jthrilly** [comment]
Alternative to this is to prompt when installing a protocol that has active sessions that have not been exported.
