### ISSUE TITLE
Form wizard display issues on Android

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#581]
While working on #551, I found a couple of minor issues with the form wizard on Android that I wasn't able to immediately fix. (Happens on master, prior to changes from #565).

- <strike>Native text selection UI renders at some offset from the text (see screenshot, where I've selected some of the nickname input)</strike>
  - <strike>Tested on an emulator; should verify this is an issue on an actual device</strike>
  - Not reproducible on my device
- When I hit the "next" button and there's an input error, the field loses focus (and keyboard disappears).

![form-wizard-selection](https://user-images.githubusercontent.com/39674/42241973-67330a54-7eda-11e8-95ca-f51bc7f12feb.png)

**Comment by bryfox** [comment]
For handling the second issue described, I tried disabling the form wizard submit when errors exist, but the field still blurred. (Makes sense; tapping anywhere in the viewport blurs it.)

It looks like we could re-focus the error input from an onSubmitFail handler in the form wizard. But I think that means, unless we directly manipulate the DOM, we'd be passing `ref`s through a couple of layers to get at the 'first visible input'. It doesn't seem like `Form` should know anything about that. Since the error displays inline on change, maybe this is better left alone; blurring on tap isn't that unusual.

**Comment by jthrilly** [comment]
Yeah, I'm inclined to leave it. I don' think it is necessarily an awful thing, and actually makes more sense in certain situations.
