### ISSUE TITLE
Ego identification interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#583]
Corresponding issue in NC for: https://github.com/codaco/Server/issues/129

We need an interface for use in roster studies where the participant can select themselves from an external data source. Needs thought about the best way to achieve this, and should coincide with us thinking about how we model ego more generally, since there are several other interfaces that store data on ego.

**Comment by pfsj** [comment]
This issue can most likely be solved by using a select node sociogram to assign an "isEgo" attribute to identify the participant from other nodes in the network. This property can then be used to filter future questions if that is necessary.
