### ISSUE TITLE
Per-dyad form

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#586]
An interface that shows an arbitrary form for each dyad in the current network, and assigns form values to the edge connecting these two nodes. Just to make it explicitly clear: this interface stores data on edges, not nodes.

**Comment by rebeccamadsen** [comment]
This is completely separate from the sociogram interface? i.e. we need to show a list of edges to users, so they can modify a form for each edge?

**Comment by jthrilly** [comment]
This is a whole different interface, yes. Imagine a form that is generated for each edge in the network.

**Comment by rebeccamadsen** [comment]
This was added in #851, right?

**Comment by jthrilly** [comment]
> This was added in #851, right?

Yep, that's right!
