### ISSUE TITLE
download graphml errors: missing variables from registry for default node form

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#587]
Creating a protocol with the default form in Architect, and adding a node in NC using that protocol, means that downloading graphml will fail with this error message:

`The variable registry seems to be missing "type" of: "uid" in node.person, "type" in node.person, "stageId" in node.person, "promptId" in node.person.`

I think these are all variables we create on nodes in NC. To address this, either (1) Architect defines these in the variable registry (which doesn't seem right), or (2) we have a separate method to define system generated variables (not by checking the registry), or (3) we don't export system generated variables.

**Comment by wwqrd** [comment]
I think that these shouldn't really be in the protocol - that's for user defined variables. Since they are required by the app we can assume that they will always be there as fixed types.

**Comment by bryfox** [comment]
From #597, some of the fields to consider (which aren't documented as public/exportable):
- stageId
- promptId
- createdIndex
- timeCreated
