### ISSUE TITLE
In NameGenerator nodes can be positioned from NodeBin even when `allowPositioning` is set to false

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#591]
```
layout: {
  allowPositioning: false,
}
```

Correctly prevents already placed nodes from being positioned, but still allows them to be place from the NodeBin.

If this is the intended behaviour it is questionable because mis-placed nodes can't be repositioned.

Suggest hiding the NodeBin for this setting.

**Comment by jthrilly** [comment]
It should hide the node bin, as you suggest. I the layout variable has no value, and allow positioning is false, it is logical to me that the nodes should not be displayed (as opposed to putting them in a pile, for example).
