### ISSUE TITLE
Node form should be optional on name generator

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#592]
A protocol may intend to not show the “add new node” button on a name generator.

- [x] Make 'form' an optional prop
- [x] Update [docs](https://github.com/codaco/Network-Canvas/wiki/Name-Generator#interface-specific-api)
- [x] Document a way in protocol to specify overriding the default form with "no form"
- [x] Remove fallback behavior in implementation and documentation

**Comment by bryfox** [comment]
Related: https://github.com/codaco/Architect/issues/136

**Comment by wwqrd** [comment]
Based on changes here https://github.com/codaco/Architect/pull/219, behaviour should now be as follows:
- Node form can be a required prop.
- If set to null then there should be no form on the Name Generator
