### ISSUE TITLE
Exporting app-generated variables

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#597]
The app currently exports variables that are defined and generated internally (`stageId`, `promptId`, `createdIndex`, `timeCreated`, uids, etc.); these aren't (yet) documented as public fields.

Each variable type must be defined in the registry so that data can be correctly exported. If an *internal* variable needs to be exported, a user (or Architect) shouldn't have to define its type in the protocol.

**Comment by rebeccamadsen** [comment]
Related to #587
