### ISSUE TITLE
Windows app icons appear corrupted in taskbar (all apps)

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#602]
From alpha5 QA builds:
![server-arch](https://user-images.githubusercontent.com/39674/42537907-3e42c87a-8464-11e8-8a89-01bc40f3bd5a.png)

![windows-taskbar](https://user-images.githubusercontent.com/39674/42537738-c8b4551a-8463-11e8-8b48-b50d966dd64c.png)

From alpha4 release (built on a different machine):
![nc](https://user-images.githubusercontent.com/39674/42537739-c8c2113c-8463-11e8-87f4-e14a67b8dd72.png)

Icons look fine to me elsewhere (e.g., on the tiled start menu).

Icons are sourced from [build-resources](https://github.com/codaco/Network-Canvas/blob/master/build-resources/icon.ico).

**Comment by jthrilly** [comment]
Things to try:

- Update electron builder and electron
- Update svg2png and icon-gen in case this is a malformed image format issue
- Experiment with reexporting the images through other apps.

**Comment by jthrilly** [comment]
Bryan found this: https://github.com/akabekobeko/npm-icon-gen/issues/86

Seems to be the root cause.

**Comment by bryfox** [comment]
> Experiment with reexporting the images through other apps.

These are the steps I'm taking, using [Gimp](https://www.gimp.org) (2.10, macOS)

- Open icon.ico in Gimp
- File -> Export As...
- Click "Export" (replace file)
- Click "Export" (accepting defaults)

**Comment by bryfox** [comment]
- https://github.com/codaco/Network-Canvas/pull/607
- https://github.com/codaco/Architect/pull/144
- https://github.com/codaco/Server/pull/134
