### ISSUE TITLE
Sociogram: Radii set incorrectly

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#632]
If a Sociogram's "concentricCircles" is a string (which is currently the default in Architect), then the background won't render correctly. (e.g., will render "10" + 1 == "101" circles.)

- [x] parse value to int
- [x] Probably add some NaN & bounds checking (what's a sensible limit?)
- export number from Architect (see https://github.com/codaco/Architect/issues/204)

**Comment by wwqrd** [comment]
I think this is an Architect issue, it should be set as a number.

**Comment by bryfox** [comment]
Since we want to support protocols edited outside of Architect and our approach elsewhere in the app is to be lenient with input, I'll handle the first two above in NC.
