### ISSUE TITLE
node form 'add another' does not return to top

### ISSUE THREAD

**Issue by berniehogan** [codaco/Network-Canvas#642]
when adding another node using the 'add another' check box (which I still think is weirder than something like 'add another' as a separate button rather than a toggle), and the 'finish' button is depressed then:
- the original node is added (good)
- the form is reset to default (good)
- the form does not return to the top of the pane (bad). 

I would both request that 'add another' is a button rather than a toggle and that when pressed, the focus returns to the top of the node form.

**Comment by bryfox** [comment]
- [x] focus returns to the top of the node form (#647)
- [ ] make 'add another' a button rather than a toggle

**Comment by jthrilly** [comment]
We actually had this as a button previously, and it didn't work with the full screen form. Let's keep the checkbox for now.
