### ISSUE TITLE
Opening a protocol fails on windows

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#645]
![capture](https://user-images.githubusercontent.com/1387940/44003914-8b05157a-9e52-11e8-899f-e35acf42ae06.PNG)

**Comment by jthrilly** [comment]
https://github.com/electron/electron/issues/7657

**Comment by bryfox** [comment]
On the alpha.6 windows release, I'm able to open protocols from the factory links, from Server, from import URLs, and when resuming sessions. Maybe it's something specific to that protocol? Can you share the file you're trying to load?

**Comment by jthrilly** [comment]
I think it is actually something specific to that Windows installation, unfortunately. The discussion around this error seems to point to something with Electron assets, but knowledge seems sparse on this error. I feel like it might be more appropriate to sit on this for now, and see if it continues to occur on this machine with future releases, that potentially update Electron. 

Details of this error:

- Factory protocols, although external protocols also didn't load.
- The app launched as normal, which is different. This error usually occurs at startup for others.
- The only difference between this machine and other W10 test machines is that it runs the slow release insider build of Windows, for checking for future breaking changes. This could turn out to be the ultimate culprit, of course.

**Comment by jthrilly** [comment]
Seems to be resolved as of Alpha 7
