### ISSUE TITLE
Update export to transpose variable name with id in attributes

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#648]
In order to help fix this issue: https://github.com/codaco/Architect/issues/208, we're going to change the variable registry format. This means that on export variable names will need to be associated with corresponding variables on each node/edge.

### protocol change

previously:

```
"variableRegistry": {
  "node": {
    "person": {
      "variables": {
        "nickname": {
          "type": "text",
          ...
```

new:

```
"variableRegistry": {
  "node": {
    "person": {
      "variables": {
        "1234-1234-1234-1234": { // uid for variable
          "type": "text",
          "name": "nickname" // export name
          ...
```

This means that data will be stored in the network as follows, and on export '1234-1234-1234-1234' will need to be transposed to 'nickname':

```
"network": {
  "nodes": [
    { "type": "person", attributes: { "1234-1234-1234-1234": "jimmy" } },
    ...
```

**Comment by jthrilly** [comment]
Just a note that we will flatten nodes so that properties within the attributes object are at the top level.

```
"network": {
  "nodes": [
    {
      "type": "person", 
      "1234-1234-1234-1234": "jimmy"
    },
   ...
```
becomes: 
```
"network": {
  "nodes": [
    {
      "type": "person", 
      "nickname": "jimmy"
    },
   ...
```

**Comment by bryfox** [comment]
Flattening JSON nodes means that we'll still have the potential for `uid` collisions with external model attributes. Other 'private' props shouldn't be exported, but we need to export `uid`s to describe relationships between nodes and edges.

I think either (a) Server will need to update its import format, or (b) we need to document `uid` (or some variant like `__uid` or anything named `nc_*`) as reserved.

**Comment by wwqrd** [comment]
Interesting point!

So if external data had the same end property name, I would expect the intention to be that these are the same property - with the suggested change they are considered separate until they are finally merged.

Perhaps this shouldn't happen on export and Network Canvas should transpose the property names as they are added to the network?

**Comment by bryfox** [comment]
>  transpose the property names as they are added to the network

Thinking of uid specifically, since it must be unique, I think we've (you've) identified good examples why this would cause other problems (https://github.com/codaco/Network-Canvas/issues/397#issuecomment-369609115; https://github.com/codaco/Network-Canvas/pull/615#issuecomment-408383557). And in general, app-generated props (e.g. stageId & timeCreated) have semantics that we could never enforce in user data. The intent of #620 was to keep user data & app metadata separate; which seems good to me.

Graphml export is fine, since it inherently separates uid from attributes. Are there other planned export formats where this would cause a problem? ...We can update the format for Server without much trouble, though having a reserved `nc_*` space would certainly be convenient, especially if we ever want to expose other app props to the user on export.

**Comment by wwqrd** [comment]
I don't think this will interfere with uids for nodes? This issue refers to a wholly separate id that refers to variable types.

**Comment by bryfox** [comment]
Sorry, I had misunderstood your "transpose the property names as they are added to the network" comment. If those are UUIDs, then I think I'd expect the same, and transposing as they're added to the network makes sense. Better to have as few surprises at export time as possible.

**Comment by bryfox** [comment]
My earlier uid comment was still focused on the flattening comment (exporting `{ "type": "person", "nickname": "jimmy"}` vs `{ "type": "person", attributes: { "nickname": "jimmy" } }`). If we flatten on export, any property inside `attributes` may conflict with a property outside (in this example, `type`).

**Comment by wwqrd** [comment]
I'm interpreting the above conversation to mean that when assigning a value to a variable on a node, it should be referenced by the intended variable name, not the variable id as it's stored in the protocol.

Protocol:
```
"variableRegistry": {
  "node": {
    "person": {
      "variables": {
        "1234-1234-1234-1234": { // uid for variable
          "type": "text",
          "name": "nickname" // export name
          ...
```

Network (as stored in Network Canvas session):
```
"network": {
  "nodes": [
    { "type": "person", attributes: { "nickname": "jimmy" } },
    ...
```

**Comment by wwqrd** [comment]
I think this is the wrong approach, it has so many implications for other Network Canvas features like sorting, searching, skip logic.

Example:
```js
/*
 * These features `additionalAttributes`, `additionalProperties`,
 * `matchProperties` will need updating to lookup the variable
 * registry before looking at the network. Does this seem sensible?
 */
{
  "id": "7cl2",
  "text": "Within the past 6 months, who has been supportive?",
  ...
  "additionalAttributes": {
    "ba5397013f9cf10a08ac193cc197c7f97d2d8374": true
  },
  "cardOptions": {
    "additionalProperties": [
      {
        "label": "Name",
        "variable": "6ae999552a0d2dca14d62e2bc8b764d377b1dd6c"
      },
    ]
  },
  "searchOptions": {
    "matchProperties": [
      "7428c4145a49b9d07e4f88033b7fc97aa98b6b99", 
      "6ae999552a0d2dca14d62e2bc8b764d377b1dd6c"
    ],
  },
}
```

Additionally, once a property is added to the network, is should be considered disconnected from the variable registry - unless we are considering the "name" property an id, in which case we confusingly have two ids.

I'd like to re-suggest handling the naming of variables on export. This will leave all functionality untouched, as variables are stored by ID until they are exported. In the case of external data, we would have to make an exception and treat the "name" as an id to then make it compatible with the protocol again.

**Comment by jthrilly** [comment]
It does seem to add several layers of overhead to simple (and common) tasks in network canvas. 

I think the only use-case that is potentially disadvantaged by doing this "on export" is the hand-crafted protocol, where the user will need to take care to update all references to a variable name when renaming it. However in this case we can expect that they will have access to tools to make this easier.

Is there a way we can provide a warning, or other feedback, when a variable is used that doesn't exist in the variable registry?

**Comment by jthrilly** [comment]
> Where would we want to provide a warning or feedback? On downloading graphml? Or loading a protocol? Or somewhere else?

So this would be for the use-case I described above, where the protocol is "hand crafted" and the creator has made a mistake.

Having thought about it more though, I would like this to be part of protocol validation, which should happen on installation. That is, a protocol that uses a variable in its configuration that is not defined in the variable registry should be invalid and not installable.
