### ISSUE TITLE
Node labels in the Sociogram NodeBucket flicker

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#667]
The node bucket on the sociogram flashes incorrect data on master branch. I don't see this happening in alpha.6.

Before drop:
![1](https://user-images.githubusercontent.com/39674/45394775-6f65d500-b600-11e8-8eb6-2b183752380c.png)

After drop (frame sequence):
![2](https://user-images.githubusercontent.com/39674/45394776-6f65d500-b600-11e8-99cd-0affdb8f8811.png)
![3](https://user-images.githubusercontent.com/39674/45394777-6ffe6b80-b600-11e8-8795-e2046d0dcade.png)
![4](https://user-images.githubusercontent.com/39674/45394779-6ffe6b80-b600-11e8-85d9-a838d93909c1.png)

**Comment by jthrilly** [comment]
@bryfox - do you think this is caused by recalculating the label property (and therefore rendering the node)? Seems like the only likely culprit.

**Comment by bryfox** [comment]
- This only happens with protocols using the custom label worker
- The underlying issue is there in alpha.6 as well, but something has slowed so that it's become visible (on my machine)
- I can reproduce by making the worker return the label asynchronously after a delay
