### ISSUE TITLE
Support network queries in node label worker?

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#668]
Extracted from https://github.com/codaco/Network-Canvas/issues/620#issuecomment-409717568

A nodeLabel worker is given a copy of the network as one input for custom labels. On the development protocol (in alpha.6), the existing nodeLabelWorker illustrates this by appending "😎" when two nodes are connected on the sociogram.

This no longer works in alpha.7; edges associate nodes using UIDs, but those aren't included in the node data provided.

The [Counter use case](https://github.com/codaco/Network-Canvas/blob/v4.0.0-alpha.6/public/protocols/development.netcanvas/nodeLabelWorker.js#L27-L29) is another place this might crop up; we should not require a deep compare to find the node in a collection.

**Comment by jthrilly** [comment]
I'm not sure why this would have changed. Why is the UID property excluded? 

I will have a look at this later today if possible, but if someone else gets to this first, this is something we will want to restore to Alpha 7.

**Comment by bryfox** [comment]
This was [part of the changes in #652](https://github.com/codaco/Network-Canvas/pull/652/files#diff-a35572d748b24c87ff2b128e2e73e393R43).

We can send the node's UID over as a separate argument to fix this specific worker example. But for the rest of the network nodes, I don't think I have any new suggestions beyond the comment linked above. Either we break encapsulation (send the full object over and document private props), or reserve and document a child prop which can include UID and anything else needed.

**Comment by jthrilly** [comment]
> This was [part of the changes in #652](https://github.com/codaco/Network-Canvas/pull/652/files#diff-a35572d748b24c87ff2b128e2e73e393R43).

Woops. My bad.

> We can send the node's UID over as a separate argument to fix this specific worker example. But for the rest of the network nodes, I don't think I have any new suggestions beyond the comment linked above. Either we break encapsulation (send the full object over and document private props), or reserve and document a child prop which can include UID and anything else needed.

My gut says that UID is all that will be needed, so I would be inclined to include this in the object passed to the worker, and document it.

What do you think would be best?

**Comment by bryfox** [comment]
That works for me. I think naming it with a prefix might be better than trying to reserve `uid` or even `_uid`... maybe `networkcanvas_id`?

**Comment by jthrilly** [comment]
Yeah, that works.
