### ISSUE TITLE
Better error for content item without assetPath?

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#671]
Architect shouldn't produce content items without assetPaths (i.e. an 'image' content item, without a corresponding image url), but perhaps in the vain of the robustness principle, we could avoid this error? In the screenshot below all content items were valid bar one:

<img width="1223" alt="content item without asset should be invalid" src="https://user-images.githubusercontent.com/776599/45423890-a08be700-b68c-11e8-8f5a-1f9e7cc46ff3.png">

**Comment by jthrilly** [comment]
If Architect is updated to always produce a valid config for this screen, this error won't happen unless the user is using a custom protocol, at which point it should be a hard failure. I take your point that from the participant perspective it would be better to show _something_ but I think the individual stage is the right level of granularity to fail at.
