### ISSUE TITLE
If an edge is deleted from variable registry, it's still possible to add it in sociogram

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#673]
Strictly speaking this is an invalid protocol and should be prevented in Architect.

When an edge type is deleted from the registry after being utilised in interfaces (in architect), this protocol still appears to work in NC.

Is this the right behaviour in NC (robustness principle)? These edges can also be exported.

Registry:
<img width="465" alt="delete edge 1" src="https://user-images.githubusercontent.com/776599/45424642-0b3e2200-b68f-11e8-9a63-556d96b236cf.png">

Network:
<img width="748" alt="delete edge 2" src="https://user-images.githubusercontent.com/776599/45424647-0d07e580-b68f-11e8-8082-130e2aa313b4.png">

Export:
<img width="836" alt="screen shot 2018-09-12 at 13 30 25" src="https://user-images.githubusercontent.com/776599/45425010-134a9180-b690-11e8-95a5-36e30ed19b89.png">

This will become a related issue once merged https://github.com/codaco/Architect/pull/214 - key becomes id, and name is a property in the registry.

**Comment by jthrilly** [comment]
My personal opinion is that this should cause the sociogram stage that creates these edges to fail to render with a message that the edge type isn't defined in the variable registry. Similar to #671
