### ISSUE TITLE
Name Generator with invalid node subject should fail with descriptive error message

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#674]
Like #673, this is an invalid protocol and should be prevented in Architect.

When an node type is deleted from the registry after being utilised in interfaces (in architect), the following error appears in Name Generator:

<img width="1249" alt="delete node 1" src="https://user-images.githubusercontent.com/776599/45425388-1a25d400-b691-11e8-9876-bf60509a3ce0.png">

 Sociogram appears to work:

<img width="1247" alt="delete node 2" src="https://user-images.githubusercontent.com/776599/45425408-29a51d00-b691-11e8-853a-88bd349f3295.png">

Is this the right behaviour (for either) in NC (robustness principle)?

**Comment by jthrilly** [comment]
As in #673, the sociogram stage should also fail to render.

**Comment by wwqrd** [comment]
Should the name generator also fail explicitly? The current error is related but not an intentional check. Given we are opting for errors in all these cases - maybe we should just blanket fail the whole protocol if it's invalid in any way? So maybe this is something to leave until we implement that (in a distributable way) in Architect?

**Comment by jthrilly** [comment]
I think there's a case for more granularity than whole protocol validity, especially during development. But yeah when we are settled on a protocol format, perhaps a blanket validation would be possible. Another consideration of that would be the performance of the validation itself.

On this issue specifically, the Name Generator should more explicitly check for this condition, and then fail more deliberately with a more useful message.
