### ISSUE TITLE
Protocol without any stages should fail at the loading stage

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#675]
Like #673 and #674 this is an invalid protocol and should be prevented in Architect.

Is this the right behaviour in NC?

<img width="1255" alt="permissive reading - no stages" src="https://user-images.githubusercontent.com/776599/45425429-3f1a4700-b691-11e8-931d-61f031169a2a.png">

**Comment by jthrilly** [comment]
I think this one should probably fail on load. If there are no stages, the protocol is invalid and can't/shouldn't be loaded. Present an error message to the user that the protocol is invalid, just like if there was a parsing error.
