### ISSUE TITLE
Cannot import protocols with large assets (Cordova)

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#684]
Related to #681, but I don't yet know if the fix will be the same.

I'm unable to import the ~24MB development protocol on my iPad. From initial testing, it looks like the video is saved, so the download and extraction step shouldn't be the problem. But the behavior is the same as #681 on my device; after a wait, the app will reload.

**Comment by bryfox** [comment]
This is a different code path than #681. It's happening as files are extracted. Currently, we keep a sequence of promises, and read all files into memory [or crash trying].

This should be solvable with the streaming interfaces for jszip and the file plugin's fileWriter.

**Comment by jthrilly** [comment]
Where is the 24mb protocol located? Is it part of the `example-protocols` repo? If so, another issue might be that these protocols haven't been updated in forever.

**Comment by bryfox** [comment]
The factory `development.netcanvas` is ~24MB; I'm using that file (imported to Server) as an example of a large protocol.
