### ISSUE TITLE
Update Electron and Node versions

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#699]
As part of maintenance and security updates, we should update all three apps to the latest possible version of Electron. This will require also updating the node and npm versions to keep them in step with electron. I suggest 5.08 of electron, since 6.x is so new and has at least one breaking change with electron-builder.

- [x] Update NC to newer electron version
- [x] Update Server to newer electron version
- [x] Update Architect to newer electron version
- [x] Ensure all package.json and readme references are to the correct electron and Node versions.
- [x] Ensure tests, CI, and any other peripheral scripts have been updated for the new environment.
----

Further information specific to Server can be found here: https://github.com/codaco/Server/issues/232

**Comment by bryfox** [comment]
Also update the documented npm version in package.json and README: package-lock is currently from v6.4.1.

**Comment by jthrilly** [comment]
There were issues associated with conducting this upgrade, so it is being postponed until upstream fixes emerge for those issues.

Namely:

- mdns was broken in electron 3.0 with node 10
- the archiving utility used by Architect was broken in web pack 4.20

**Comment by bryfox** [comment]
A couple of other notes:
- Node 10.2 is the version incompatible with MDNS (Electron 3.0.x)
- To keep things simple, we should match the app's Node version to that used by Electron across all apps (not just Server); that was the cause of the missing dylib issues

**Comment by rebeccamadsen** [comment]
Resolved in #962, codaco/Architect#573, and codaco/Server#257.
