### ISSUE TITLE
Server export needs to transpose variable IDs to names

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#718]
Follow-on to #648. #713 fixed graphml download, but the transposition should probably be a separate step.

- [x] Refactor id to name translation (output: plain object)
- [x] Update server export to use this format
- ~Update graphml export to use this format~

Edit: After looking at the GraphML export, I don't think it makes sense to refactor it to use the format. It would reduce some duplication, but increase the work done since it's tightly coupled to the types defined in the variable registry. A better approach might be to refactor in the future to use centralized 'selection' logic.

**Comment by bryfox** [comment]
Notes:
- external data will need to use the inverse operation (either when imported or added)
- I assume we'll allow external data props to 'pass through' even when not defined in the variable registry, so this should be lenient w.r.t. variable definitions

**Comment by bryfox** [comment]
Can anyone confirm or refute the assumption about external props above? I'd forgotten that we have some [stricter export rules waiting in the wings](https://github.com/codaco/Network-Canvas/blob/master/src/utils/ExportData.js#L282-L285).

In short: when we import external data which contains one or more properties that are not defined in the variable registry, how do we treat those "external properties"?

Should they be passed through to data export (and user worker scripts)? Should we drop them on import?

**Comment by jthrilly** [comment]
> Can anyone confirm or refute the assumption about external props above? I'd forgotten that we have some [stricter export rules waiting in the wings](https://github.com/codaco/Network-Canvas/blob/master/src/utils/ExportData.js#L282-L285).

I thought about this some, and I think the most sensible thing to do would be to discard, on import, any properties in external data nodes that don't have a corresponding definition in the variable registry.

That way, any interfaces that create nodes from external data will be able to more simply copy these properties to a new node. Discarding the other properties as the external data is imported will also work better with any potential dynamic external data sources. 

This will also work with our plan of populating new nodes with default values for every variable in the variable registry (#710)
