### ISSUE TITLE
NG Autocomplete styling refactor?

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#722]
- [x] Border-radius definition is invalid in [search](https://github.com/codaco/Network-Canvas/blob/master/src/styles/components/_search.scss#L9)
- [x] Number offset in node icon
- [x] `--collapsed-square-size` was removed; need to restore, but actual value tbd since node size is now tied to vmin; may need to replace with dynamic calculation if approximation isn't good enough

![ngac](https://user-images.githubusercontent.com/39674/46883570-74e15580-ce20-11e8-8c76-d9bbeb4107b0.png)

Edit: See comments; we may want to revise the design.

**Comment by bryfox** [comment]
Close button styling has also changed; need to reinstate something like the original cross styles (see https://github.com/codaco/Network-Canvas/pull/712#discussion_r224878776)

**Comment by jthrilly** [comment]
I think we should perhaps take the opportunity to revise the UI for this interface, and perhaps create dedicated components for some of these UI elements.

Another possible enhancement would be to reimplement the animation using the FLIP approach that Steve has explored in Architect.

**Comment by bryfox** [comment]
See also #735, which highlights an issue with the current behavior, and which might be solvable with the revised design.
