### ISSUE TITLE
Software keyboard causing pairing dialog to be pushed to top

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#730]
Using the software keyboard to enter the pairing code causes the UI to be pushed upwards, with no way to get it back down.

![img_0003](https://user-images.githubusercontent.com/1387940/46954745-44502480-d089-11e8-9f85-ac7e59fc8800.PNG)

**Comment by jthrilly** [comment]
Issue does not impact Android, although android deals with this by zooming the page out, making the pairing code difficult to see.

**Comment by bryfox** [comment]
See https://bugreport.apple.com/web/?problemID=37497842 (via https://github.com/apache/cordova-ios/issues/417); removing `viewport-fit=cover` does solve the issue for now, and doesn't seem to be strictly needed in our case?
