### ISSUE TITLE
Binary attributes set on a name generator do not trigger highlighting on a sociogram

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#731]
Steps to repro:
- Create a boolean variable for a node type
- Assign the value "true" as an additional attribute on a name generator prompt for this node type
- Create a sociogram prompt with the highlight variable set to this boolean variable.
- Observe that nodes created on the name generator prompt (which should have a highlight variable value of true) are not highlighted

**Comment by wwqrd** [comment]
Name Generator sets attribute with a boolean, Sociogram appears to set it with undefined.

<img width="723" alt="screen shot 2018-10-15 at 15 36 02" src="https://user-images.githubusercontent.com/776599/46957771-2a661000-d090-11e8-8003-1b3f1145e46c.png">

<img width="888" alt="screen shot 2018-10-15 at 15 36 11" src="https://user-images.githubusercontent.com/776599/46957776-2df99700-d090-11e8-962e-6fc7b21863be.png">

**Comment by jthrilly** [comment]
It actually looks like this works for the teaching protocol, so I am exploring the idea that this is related to the new UUID variable transposition.
