### ISSUE TITLE
Large hit box for forwards button in timeline navigation triggers animation, but not forwards action.

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#733]
Clicking in the highlighted region triggers button animation, but actually opens the menu (which is the correct action for clicking the timeline itself).

<img width="361" alt="screen shot 2018-10-15 at 15 41 49" src="https://user-images.githubusercontent.com/776599/46958384-9eed7e80-d091-11e8-85f6-c7ce99f0a3d6.png">

Similar issue with the back button.

**Comment by jthrilly** [comment]
I noticed this, along with the clipping issue. I'm looking into it now.
