### ISSUE TITLE
Add nodes count text misaligned on search box

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#734]
Close button looks like it's misaligned too:

<img width="935" alt="screen shot 2018-10-15 at 15 58 12" src="https://user-images.githubusercontent.com/776599/46959133-38696000-d093-11e8-8ff3-60756befe1ee.png">

**Comment by rebeccamadsen** [comment]
Related to #722.

**Comment by wwqrd** [comment]
Already covered 👍
