### ISSUE TITLE
Form & prompt interaction can produce unexpected results

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#741]
Setup:
- I have a name generator with the default Person form
- I have a prompt with `additionalAttributes` that overlap with the form attributes (for argument's sake, it includes all of them)

Observed:
- When I create a new node using the form, the form values override the additionalAttributes
- However, this means that the node (once created) is filtered out of the current prompt, and isn't displayed (which seems unexpected; at least, there's no indication of success)

Let's now say I have a 'current network' panel:
- My newly-created Person does display in that panel after creation
- If I drag into the main list, then the form attributes I filled out are replaced by the prompt's additionalAttributes
- If I edit the Person node (again, using the form) then that person will once again be filtered out of the main list and moved back to the panel.
- Note I can't add my node to the network without replacing form attributes with the prompt's additionalAttributes

All of the above may be the desired behavior, and there may be a use case for prompt attributes overriding user input. However, we may want to at least improve documentation or UX in places.

**Comment by jthrilly** [comment]
Resolved by changes to selectors.
