### ISSUE TITLE
Data reset fails while session is in progress (Electron)

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#742]
Steps (using electron):
1. Start a new session (e.g., with the development protocol)
2. Click the menu item `Develop > Clear storage data`
3. Confirm by clicking OK

Observed:
- app reloads, but still on protocol URL (a new session is created with no network)
- The "resume interview" screen errors on partially-constructed session:

```
SessionList.js:89 Uncaught TypeError: Cannot read property 'nodes' of undefined
    at details (SessionList.js:89)
    at CardList.js:42
    at Array.map (<anonymous>)
    at CardList (CardList.js:35)
```

**Comment by jthrilly** [comment]
This will be because NC has special code to handle resetting app data, including resetting the route. This is not connected up for the native menus. I'm thinking a dirty workaround will be to somehow reset the electron addressbar.

**Comment by bryfox** [comment]
This worked in prior versions; here's the effective diff:

```
-                mainWindow.webContents.session.clearStorageData({}, () => {
-                  mainWindow.loadURL(appUrl);
-                });

+                window.webContents.session.clearStorageData(() => {
+                  window.webContents.reload();
+                });
```
