### ISSUE TITLE
Server address changes aren't handled gracefully

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#743]
If the Server's pairing URL changes for some reason (e.g., an address change), a user is currently required to unpair and re-pair. In the future, port may also change, since it may be user-configurable.

Note:
- A Server may have multiple valid URLs
- A given URL may be invalid for a Server at any given time
- A given URL may be occupied by a service other than the Server's device service

**Comment by wwqrd** [comment]
- Could we speed up the process of displaying "Server unavailable"? i.e. When we open the setup panel we can immediately see something like a "Server offline" status?
- Could we automatically add new urls to the paired server when a service is advertised for a known server?
- What happens when there are two different services advertised simultaneously?

**Comment by bryfox** [comment]
> When we open the setup panel we can immediately see something like a "Server offline" status?

This is done currently, assuming it's truly unreachable:

![screen shot 2018-10-18 at 9 35 16 am](https://user-images.githubusercontent.com/39674/47158235-384aa980-d2b9-11e8-9214-01e2dbccd4b6.png)

> Could we automatically add new urls to the paired server when a service is advertised for a known server?

Yes. To confirm identities, we'd probably need some sort of confirmation protocol. The question is then what to do with the prior address. Do we assume it's no longer valid and discard it, or do we keep both and attempt future connections over both? Probably the former if we have to choose, but should there be some confirmation or configuration UI? Is displaying the connection URL enough?

> What happens when there are two different services advertised simultaneously?

During discovery, all discovered servers are shown. With the current single-server UX changes, though, you don't enter discovery if you already have a paired server. To support the previous idea, we'll need to start discovery once a server is unreachable.

**Comment by jthrilly** [comment]
> During discovery, all discovered servers are shown. With the current single-server UX changes, though, you don't enter discovery if you already have a paired server. To support the previous idea, we'll need to start discovery once a server is unreachable.

Perhaps this is the key to this issue. How about the following:

- If a server is unreachable, display a new UI which is a version of the pairing dialog. It would allow the user to either select a currently advertising server to replace the one that is uncontactable, OR manually type an address which will then become the defect location of this server.

**Comment by wwqrd** [comment]
> This is done currently, assuming it's truly unreachable

This is the kind of thing I was imagining:

![offline](https://user-images.githubusercontent.com/776599/47206981-f5083d80-d381-11e8-8cdf-b7a8e6f8a1e9.png)

We should keep the timeout message too, and maybe add a "connecting" animation?

**Comment by jthrilly** [comment]
Workflow I want to adopt for this is to unpair and repair at the new address, and have the ability to push to any paired server with the protocol for the interview session installed.
