### ISSUE TITLE
Refine protocol requirements

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#758]
This issue will be updated to capture small clarifications, updates, and additions to protocol validation which can be captured either by Schema changes or scripted verification. This is an extension of #697.

### Enumerable values
- [x] `stage type`
- [x] `SkipLogic.action`
- [x] `SkipLogic.operator`
- [x] `filter.join`
- [x] `filter.rules.options.operator`
- [x] `filter.rules.type`
- [x] `forms.fields.component`
- [x] `validation` keys
- [x] enum for Information items.type (text, video, image, audio)
- <strike>enum for iconVariant?</strike>
- [x] enum for subject.type: only node or edge (note: this is effectively ignored by NC for now.)
- [x] enum for rule.type: alter, ego, edge

### Numerical

- [x] `SkipLogic.value` must be a positive integer

### Other

- [x] `items` is required if Stage type is Information
- [x] some fields are required for other Stage types? (`prompts`?)
- [x] `SkipLogic.value` is required unless `SkipLogic.operator` is `ANY` or `NONE`
- [x] `filter.rules.options.value` is required unless `options.operator` is `EXISTS` or `NOT_EXISTS`
- [x] `lastModified` should have date format enforced
- [x] `filter.rules[].options[].type` is required
- [x] `variables` should be optional for variableRegistry edges

### Variable registry

- [x] form field `component`s must correspond to an appropriate type of `variable` (e.g., a `Checkbox` variable should be defined as boolean in the registry). See [wiki](https://github.com/codaco/Network-Canvas/wiki/Variable-Types)
- [x] `filter.rules[].options[].attribute` should be defined for the associated `filter.rules[].options[].type`
- [ ] `filter.rules[].options[].value` should be of type `filter.rules[].options[].type` (https://github.com/codaco/Architect/issues/251)
    - see comment/question below

The following must refer to valid entries in the variable registry.

- [x] `node.displayVariable` (e.g., nickname)
- [x] `filter.rules[].options[].type`
- [x] `subject.type` must match one of `variableRegistry[subject.entity]`
- [x] `forms[key].entity` + `forms[key].type`
- [x] `forms.fields[].variable`
- [x] `stages[].prompts[].cardOptions.additionalProperties[]`
- [x] `stages[].prompts[].sortOptions.sortOrder[].property`
- [x] `stages[].prompts[].sortOptions.sortableProperties[]`
- [x] `prompts[].additionalAttributes`
- [x] `prompts[].variable` (OrdinalBin)
- [x] `promps[].layout.layoutVariable` (Sociogram)

### Validations

Some types of validation only make sense for some variable types... should these be included?

- min/maxSelected: only for ones with options
- min/maxLength: only for ones without options (otherwise an author-time error... how should this be handled?)
- min/maxValue: only for numeric without options

...The above seem like better candidates to simply issue a warning in NC (and not apply validations where they don't make sense), rather than rejecting a protocol.

- Mutually exclusive requirements (that rule out any possible values)?

### Other

- [x] `stage.form` must exist in `forms`
- [x] Within every collection, `id` must be unique
    - stages[]
    - panels[]
    - rules[]
    - prompts[]
    - items[]
- [x] Within each registry type, `variable.name` must be unique (https://github.com/codaco/Architect/issues/299)
- <strike>additionalAttributes value must be included in variable.options if type is ordinal or categorical?</strike>
    - no, probably want to allow a default value that isn't presented to the user

**Comment by bryfox** [comment]
> `filter.rules[].options[].type` is required

This is [documented as required in the wiki](https://github.com/codaco/Network-Canvas/wiki/Skip-Logic#skip-logic-api), but doesn't seem to actually be required for an egoRule as the registry is never consulted. Should this be required in the Schema for all rules? Only for some?

**Comment by bryfox** [comment]
> `filter.rules[].options[].value` should be of type `filter.rules[].options[].type`

How much type inference/checking should we do? [As noted in the related issue](https://github.com/codaco/Architect/issues/251#issue-368293729), it's unclear how to handle some of our defined types.

**Comment by bryfox** [comment]
I've implemented enforcement of unique `id` props. I'm not planning on implementing verification that type & variable keys (now UUIDs, when from Architect) are unique; the validator relies on `JSON.parse`. We should document the unique requirement, but it won't be checked.

**Comment by bryfox** [comment]
> forms.fields.component

See https://github.com/codaco/Network-Canvas/issues/764#issuecomment-437049780; if we want to rely on lazy definition of form types, I'll remove the enum for this fragment.

**Comment by jthrilly** [comment]
Yes, I think so.
