### ISSUE TITLE
Move subject definition to 'stage' for all interfaces

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#759]
We've had some discussion about changing how `subject` is defined.

Currently, it may be defined at either the stage or prompt level; we may want to standardize on one subject per stage. (This might reduce confusion with conflicting subjects in forms and panels.)

**Comment by jthrilly** [comment]
Interfaces that define subject at root level:
- name generator
- ordinal bin
- categorical bin (planned)
- ego form (planned)
- alter form (planned)

Interfaces that define subject at prompt level:
- sociogram
- name generator list
- name generator roster

Special cases:
- Narrative interface. This will have a dedicated API for mapping network actors and properties to visual aspects of the sociogram.

**Comment by jthrilly** [comment]
Just to confirm: we want to move from prompt level, to stage (root) level definitions of the interface subject.
