### ISSUE TITLE
When a sociogram 'creates' a type, it should automatically display it

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#760]
Unless there's a compelling reason not to, we should default to displaying the edge type that is created by a sociogram. Other types may be displayed as well, but a protocol should not need to duplicate the type in the `create` and `display` property.

**Comment by jthrilly** [comment]
I think this is a very logical suggestion. However the question is weather we should handle this in architect or NC. The behaviour could be handled from a user-facing perspective with a change to the prompt editing interface in architect, without changing the API for network canvas. I think when Steve and I designed this, we were thinking primarily about expressibility, and therefore minimising assumptions.

@wwqrd?

**Comment by wwqrd** [comment]
From the discussion in slack I think the consensus was to do both:
- Network Canvas should assume that the created edge gets displayed
- Architect should include the created edge in the display edges property automatically (and immutably)

From the user's point of view, we probably always want to show the created edge - in which case the NC change makes sense. But on the other hand, I think it could lead to unexpected behaviour.

**Comment by jthrilly** [comment]
In Architect:

The UI for this section can be simplified to the following:

Section 1: 

Create an edge of the following type (dropdown allowing edge creation)

Section 2: 

Display these edge types:

- [x] value from section 1 (not able to be unselected)
- [ ] ... all other edge types
