### ISSUE TITLE
Skip logic should support skipping to a specific stage

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#762]
Currently skip logic determines if a given stage should be shown or skipped. 

If a series of screens all depend on the same logic (for example, if there are a number of screens only to be shown to an ego with a certain attribute), the skip logic must be duplicated across these screens.

There are two possible solutions:

- Abstract the definition of skip logic in a similar way to node forms. This would allow one definition to be applied to multiple stages, making the management easier. This has the advantage of maintaining the current approach to skip logic.
- Build new functionality into the skip logic system that allows skipping to a specific named stage in the case that the logic test fails.

**Comment by rebeccamadsen** [comment]
Either solution would work, though I think I lean towards abstracting the skip logic definitions. The ordering of the stages could change, meaning that the stage the user named may no longer occur after the stage being skipped.

**Comment by jthrilly** [comment]
Given we have moved away from abstractions like the node forms in recent months, I think a better solution here would be to support duplicating existing skip logic.

Either way, this is a low priority issue for now.
