### ISSUE TITLE
form 'entity' and 'type' don't seem to be needed

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#763]
Our generated and factory protocols contain `entity` and `type` properties on each form. Based on existing behavior, they don't seem to be needed.

Behavior in Architect:
- I can only create forms for nodes, not other entities like edges
- When I add a form to a stage, I'm forced to choose one of the same `type` (e.g., Person)

Behavior in NC:
- Form always creates a node, regardless of entity
- Form always creates a node of type corresponding to the `subject`, regardless of form type

Will there ever be a case where this shouldn't match 'node' and the stage subject's type, respectively?

**Comment by jthrilly** [comment]
We will have some new interfaces that might change this:

- Per-dyad form - Display a form for each dyad connected by an edge of type X, and assign the value of the form to said edge.
- Ego form - Same as above, but for ego.

This would seem to give us the need for entity to be one of node, ego, or edge, and type to be the specifier for ego or edge.

**Comment by bryfox** [comment]
Makes sense, thanks!
