### ISSUE TITLE
Categorical bin animation tweaks

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#794]
Should the expanding hover move other bins (and rows) around?
![jostle mov](https://user-images.githubusercontent.com/776599/48716948-5edd6680-ec10-11e8-8643-af84ed459a94.gif)

Should the transition be animated on drop?
![snap mov](https://user-images.githubusercontent.com/776599/48716994-73b9fa00-ec10-11e8-9d1e-70d7d3bfd76b.gif)

**Comment by jthrilly** [comment]
Other tweaks:

- The size of bins is too small for bin n < 4. 
- Text size is too large for the collapsed bins. Either the collapsed bins should be larger, or the text size should shrink (or both?).
- Node size in the expanded bin is too large. Could probably use a .66 scale factor.

**Comment by rebeccamadsen** [comment]
Text size for all collapsed bins, or for the smaller bins when there is an expanded bin open?
