### ISSUE TITLE
Extract GraphML export to a separate repo + submodule

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#796]
Server will need to export GraphML files as well.

**Comment by bryfox** [comment]
https://github.com/codaco/network-exporters

**Comment by bryfox** [comment]
Issues to solve:

- Server should likely run this in the main process; will need to abstract DOM building or use something like [xmldom](https://www.npmjs.com/package/xmldom) (but see next point).
- Scalability; server needs to support [much larger networks](https://github.com/codaco/Server/issues/107#issuecomment-395065757).
  - Probably need a streaming/fs interface rather than a string builder
  - Need to see if DOM building is an option at largest sizes

If the document/DOM approach isn't viable, then will need to find some other way of encapsulating the general logic so that this can be shared.

**Comment by bryfox** [comment]
With the test (mock) data in Server, the DOM-building approach exhausts the heap somewhere around 2500-3000 sessions (with very small node objects), short of the example 'large network' size. Performance growth looks linear, though.

Maybe there's a compromise that could still make use of DOMParser and avoid a different abstraction. Something like:
- traverse nodes once to build a attribute map
- stream what we have so far
- for some nodes (in chunks):
    - build up a collection of [xml] nodes
    - serialize & stream that collection
- repeat for edges

**Comment by jthrilly** [comment]
When you say it exhausts the heap, are we talking the node js memory limit (~2gb)?

**Comment by bryfox** [comment]
Yes. (`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`)

**Comment by jthrilly** [comment]
If it weren't such a pain that might actually be funny.

**Comment by jthrilly** [comment]
So perhaps this is totally the wrong way of looking at this, but if we get to ~3k sessions with 1.76gb of heap (and admittedly modest network size), and performance growth is roughly linear, wouldn't increasing the heap size to 6 or even 8gb (I know, I know) get us there? 

It does seem to be possible on the electron side to do this. 

Some thoughts:

- This is not a ridiculous amount of RAM for a server app to use during a memory intensive operation - quite the opposite. Plus, even 8gb of RAM (dynamically allocated) is going to be reasonable on the majority of suitable machines in 2021.
- The need to export 4.5k sessions with almost a million edges will be _extremely infrequent_. This could even be a special option that we present to the user if an export operation fails, or when we detect a large number of sessions present. 

Thoughts?

**Comment by jthrilly** [comment]
@wwqrd has an alternate suggestion: ditching the DOM building approach entirely. The schema for GraphML is simple, so it might work. I've asked him to comment here to flesh it out a little.

**Comment by wwqrd** [comment]
Maybe we should use a strings/files/streams since the schema is so simple and flat? The schema was probably designed with this kind of issue in mind.

**Comment by bryfox** [comment]
Server contains the refactored code; not yet shared in a separate repo.
