### ISSUE TITLE
Narrative Interface: Convex hulls layer component

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#797]
We would like to be able to show convex hull style overlays on the network. We can implement this as a layer much like `<ConcentricCircles />` comprises of a `<NodeLayout />` and an `<EdgeLayout />`.

- Create new convex hulls component
- Positions must sync up with `<NodeLayout />` component.
- Groups are defined by attributes on the nodes
- Should be able to configure which groups are shown (and settings like colors) via props 

## Narrative Interface (Background)

The narrative interface is primarily an exploratory tool rather than a data gathering one (with the caveat that we would ultimately like to record any interactions).

This feature will be implemented as a variation/extension of the Sociogram Interface, with additional layer components.

Relates to: https://github.com/codaco/Network-Canvas/issues/258

**Comment by wwqrd** [comment]
Possible library: https://github.com/mapbox/concaveman

**Comment by rebeccamadsen** [comment]
Resolved in #802 via #808.
