### ISSUE TITLE
Narrative Interface: Annotations layer component

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#799]
We would like to allow the participant/researcher to annotate on the network by drawing on it.

We can implement this as a layer much like `<ConcentricCircles />` comprises of a `<NodeLayout />` and an `<EdgeLayout />`.

- Create new annotation component
- Participant should be able to draw on the network using touch/mouse.
- Lines should fade over time: longer lines should fade more slowly.
- Positions must sync up with `<NodeLayout />` component (in this case we mainly need to think about how the coordinates system works to enable playback at a later date).

## Narrative Interface (Background)

The narrative interface is primarily an exploratory tool rather than a data gathering one (with the caveat that we would ultimately like to record any interactions).

This feature will be implemented as a variation/extension of the Sociogram Interface, with additional layer components.

Relates to: https://github.com/codaco/Network-Canvas/issues/258

**Comment by rebeccamadsen** [comment]
Will the annotations and moving nodes around be "enabled" settings on the interface at the same time, or are they incompatible with one another?

**Comment by jthrilly** [comment]
They are enabled at the same time. 

Ideal behaviour would be that starting a touch/drag event on a node will trigger that nodes touch/drag interactivity, while starting a touch/drag event on the background will trigger the annotation.

**Comment by rebeccamadsen** [comment]
Resolved in #802 via #805.
