### ISSUE TITLE
Narrative Interface: Control panel component

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#800]
The narrative interface is an exploratory interface, we need a control panel in order to toggle element visibility and what kinds of interactions are available.

- Create control panel component
- Should have default settings (configurable in Architect)
- Should be able to toggle which edges are visible
- Should be able to toggle which node attributes are highlighted
- Should be able to turn on annotation mode/node dragging mode (depends on: https://github.com/codaco/Network-Canvas/issues/799)
- Should be able to toggle which convex hulls are shown (depends on: https://github.com/codaco/Network-Canvas/issues/797)
- Should be able to reset settings back to default

## Narrative Interface (Background)

The narrative interface is primarily an exploratory tool rather than a data gathering one (with the caveat that we would ultimately like to record any interactions).

This feature will be implemented as a variation/extension of the Sociogram Interface, with additional layer components.

Relates to: https://github.com/codaco/Network-Canvas/issues/258

**Comment by rebeccamadsen** [comment]
"Default settings" being what's defined in the "preset"? If so, does switching to a different preset effectively "forget" the user's edge/attributes/hulls toggles?

**Comment by rebeccamadsen** [comment]
Resolved in #802 via #823.
