### ISSUE TITLE
showExistingNodes scope does not match Architect

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas#832]
NC works with `showExistingNodes` at the stage level (in the dev protocol, schema, and selector); Architect creates the property for each prompt. One of the apps (and documentation, if needed) should be updated to match.

**Comment by rebeccamadsen** [comment]
Related to codaco/Architect#355

**Comment by bryfox** [comment]
Sorry, I missed that one; this is a duplicate.
