### ISSUE TITLE
Refinements to narrative interface

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#839]
Feedback suggested a number of refinements to the narrative interface

- We would like to add the ability for narrative annotations to persist. This should be implemented as a 'pin' toggle button in the preset switcher area.
- Remove multiple colors for node highlighting in favour of either a radio group allowing a single attribute to be selected to be shown, or a checkbox group. In either case, node selected state should be white.

**Comment by rebeccamadsen** [comment]
Should the "pin" toggle button keep all annotations past, present and future, just the annotations created after the "pinned" is clicked (future), just the still visible and future annotations, or something else? If still visible annotations are kept, should they be restored to full visibility or somehow maintained in a partially visible state?

I think the easiest to implement would be to keep "future" annotations, but I'm interested in the "right" answer.

Is there a consensus on the radio group versus checkbox group for node highlighting, or just to try one and see how it is received?

**Comment by jthrilly** [comment]
> Should the "pin" toggle button keep all annotations past, present and future, just the annotations created after the "pinned" is clicked (future), just the still visible and future annotations, or something else? If still visible annotations are kept, should they be restored to full visibility or somehow maintained in a partially visible state?

It should turn off the fading entirely, and set any existing annotations to full opacity. It should work with anything on the screen currently, and also anything drawn afterwards.

Also, let's call it a "freeze" button, and have a snowflake icon.

> Is there a consensus on the radio group versus checkbox group for node highlighting, or just to try one and see how it is received?

Let's do radio group.

> Should the Links and Groups be updated to checkbox/radiogroups as well, or possibly disable the toggle effect when clicking on the Edge label and category labels? You can get in a funny state by allowing toggling edges and categories from the header and the content of the drop downs.

No I think these should stay as they are.
