### ISSUE TITLE
incorrect stage navigated to when filtering menu

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#864]
If you filter the stage menu, and then select one of the stages showing, it navigates to the index of the filtered list instead of the stage you selected. Steps to reproduce:

1. In a development protocol session, open stage menu.
2. Filter for a later stage, like "sociogram".
3. Click on sociogram in the stage list.

It navigates to stage 0, or NG Closeness.

**Comment by jthrilly** [comment]
Good catch!
