### ISSUE TITLE
should NC have a "quit" option when full screen

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#872]
In full screen mode, the only way to quit NC in Windows is to alt-tab and close it on the taskbar, or "End Task" through the "Task Manager". Is that a problem for our users? I know we've been back and forth on this one.

**Comment by jthrilly** [comment]
You can press the 'alt' key, and then use the native menu to exit full screen. I'm going to add back in an exit app and a toggle fullscreen option.

**Comment by rebeccamadsen** [comment]
Resolved with #894
