### ISSUE TITLE
Sort by last opened on the Start Interview screen?

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#876]
Should we sort the protocols on the start interview screen by last opened or last imported? Currently the most recently imported protocol is at the back.

Relates to: #550

**Comment by rebeccamadsen** [comment]
That would make sense to me.

**Comment by jthrilly** [comment]
Yes, I think so.

#550 should include the ability to sort and filter the resume interview screen anyway, so let's handle it there.

**Comment by jthrilly** [comment]
Okay, I ended up resolving this by making the currently selected protocol sticky between restarts. I don't think we need sorting of protocol cards as long as we have that. We can return to it later in response to feedback.
