### ISSUE TITLE
Ability to push interview data to any paired server with current session protocol

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#884]
We need the ability for a NC client to push to any paired server that has the current session's interview protocol available. 

This may already be implemented, but we have to validate.

**Comment by jthrilly** [comment]
To put this another way: we shouldn't care if the currently paired server is the one we got the protocol from. If it has the same protocol installed, we should try to push data to it.

**Comment by rebeccamadsen** [comment]
I think this already works. I can add a protocol to NC locally, and then pair to a Server, and if the protocol exists on Server I can push to it. NC gives me this error message if the protocol does not exist on Server:

`The associated protocol does not exist on this server`

**Comment by jthrilly** [comment]
Thanks - that's good info!

**Comment by jthrilly** [comment]
Going to leave open so that I handle the case where the protocol isn't installed.
