### ISSUE TITLE
Implement bulk file export

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas#897]
Bulk interview export is only implemented with export to Server. This should be extended to creating a zip file or multiple single files containing graphML or CSV.

Prerequisites:

- Shared GraphML export code #796

**Comment by rebeccamadsen** [comment]
Is this is intended for exporting multiple sessions from NC on the session list? If so, are we restricting the export to sessions from the same protocol as Server does?

**Comment by jthrilly** [comment]
> Is this is intended for exporting multiple sessions from NC on the session list? If so, are we restricting the export to sessions from the same protocol as Server does?

Yes this is intended for the sessions list.

In this instance, since we won't be including "merging" (union) functionality in NC, I think its fine for the zip to contain sessions from different protocols. They key thing is to allow quick export of lots of data from the app in a single file so that it can be easily transferred.

**Comment by rebeccamadsen** [comment]
We aren't merging? What other options are being simplified here?

**Comment by jthrilly** [comment]
> We aren't merging? What other options are being simplified here?

Yeah, so what I mean is that we aren't using the "export union of all networks" function. In NC, we just want the "export the network from each interview separately" option.

I would like to export the export options in the Settings menu of Network Canvas, in their own group. These would include everything here:

<img width="1256" alt="Screen Shot 2020-01-31 at 12 14 55 PM" src="https://user-images.githubusercontent.com/1387940/73531527-580ccf00-4423-11ea-926a-4549776c6093.png">


Would you like me to make a quick UI mockup of the flow?

**Comment by jthrilly** [comment]
Just to add that this issue has overlaps with:

- Extending graphML to support ego attribute data, and metadata: https://github.com/codaco/network-exporters/issues/1
- Support CSV export from network canvas: https://github.com/codaco/Network-Canvas/issues/1007

Both should be possible now we have the network export submodule in place. CSV export requires the zip functionality you will need to develop for this issue, but should otherwise just work. 

I'm going to do some work on the GraphML issue to get the specification locked down, but once it is added to the submodule it can be deployed to Server and NC at the same time.

**Comment by rebeccamadsen** [comment]
Definitely has overlaps. I'm thinking CSV export comes before this, but wanted to make sure we're thinking about this in terms of how much of CSV export workflow moves from Server to network-exporters.

What are you thinking for the UI flow? Is it just in the Settings menu? Is the "Include Ego" option also included? Are the (coming) "Create label column" and "resequence IDs" options going to be included in NC?

**Comment by jthrilly** [comment]
> Definitely has overlaps. I'm thinking CSV export comes before this, but wanted to make sure we're thinking about this in terms of how much of CSV export workflow moves from Server to network-exporters.

Basically, the actual CSV encoding part should be in the network-exporters submodule. I want that submodule to provide a standard interface for export tasks between Server and NC: `exportNetwork(<options>)`, type thing.  CSV is just an encoding choice (so an option).

I think the zipping will be too platform specific to put in there too, but you might be able to share electron code between Server and NC and use the environment shim to then just write a cordova version of it.

Because of the need for zipping even when exporting a single CSV network, I think it might be best to handle that first rather then CSV.

> What are you thinking for the UI flow? Is it just in the Settings menu? Is the "Include Ego" option also included? Are the (coming) "Create label column" and "resequence IDs" options going to be included in NC?

The actual export task will be triggered from the two existing locations: (1) Single network export from the finish interview screen, and (2) bulk OR single network export from the manage sessions screen.

The interface the user sees on this screen should be as streamlined as possible. We don't want to present lots of choices on export, as we do in Server. Basically, all of the options should be read from the values in the settings menu. This includes 'resequence IDs', 'include Ego data', and so on.
