### ISSUE TITLE
radio group scrolls off visible page

### ISSUE THREAD

**Issue by rebeccamadsen** [codaco/Network-Canvas#967]
Radio group can cause a form to scroll beyond the user's view.

To replicate: on an interface that auto scrolls on error (like AlterForm or EgoForm), create a form with multiple radio groups, so the page will overflow and need scrolling. In NC, or in preview mode in Architect, select an option for the radio groups. Selecting an option in the later radio groups, past the initial visible height of the page, will cause the view to auto scroll too far and render the form unusable.

For example, here's early in the form:
![ego-question](https://user-images.githubusercontent.com/16093053/65069293-64066180-d958-11e9-9d84-64f060ca3357.png)

Here is after selecting an answer on the third question:
![ego-question-2](https://user-images.githubusercontent.com/16093053/65069303-67015200-d958-11e9-886a-bbf3acd171ff.png)

Note: This appears to be Windows specific.

**Comment by jthrilly** [comment]
Could you try and reproduce this in the newer electron version we are testing? I have had a look and can reproduce, but am baffled by what I'm seeing.

**Comment by jthrilly** [comment]
Also, I can confirm that this is also an issue on macOS, so not windows specific.

**Comment by jthrilly** [comment]
Found the issue - for security (and accessibility) reasons, browsers scroll to make an input visible when it becomes highlighted. 

We position the real radio input absolutely, and slightly off of the bottom of the screen. Removing `position: absolute` from the input fixes this, with no visible consequences. 

I am investigating if the checkbox component needs similar treatment, and will issue a PR.
