### ISSUE TITLE
De-emphasise the outdated protocol messaging

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#981]
> emphasise that the user doesn't need to take any action if they don't want to in the dialog text. just generally be more reassuring. And visually, perhaps somehow reduce the emphasis of the warning state from the protocol card. One suggestion was bringing the warning icon inline (perhaps after the protocol name?) or just making it smaller

**Comment by jthrilly** [comment]
> smaler

I am so bad at wording.

**Comment by wwqrd** [comment]
At least you didn't write "more smol"
