### ISSUE TITLE
Update scaling control to use +/- buttons

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas#985]
Because headings and body text scale at different rates a button control is preferred.

<img width="1207" alt="Screenshot 2019-10-17 at 16 00 34" src="https://user-images.githubusercontent.com/776599/67021360-6bf02780-f0f7-11e9-8195-d8a8c4319c54.png">

**Comment by jthrilly** [comment]
This is obsoleted by newer UI
